import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Recipes below are original Georgian writing, built around common, widely-known
// infant/toddler feeding combinations. Note: babies under 12 months generally don't
// need dedicated snacks between milk feeds/meals (standard, widely-published pediatric
// guidance), so FROM_6/FROM_9 items here are single-ingredient finger foods suitable
// as an extra offering, not a required snack. Nutrient values are computed from a
// reusable per-100g reference table built from USDA FoodData Central figures
// (public domain / CC0).
const recipes = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 6-8 MONTHS (FROM_6) — SNACK
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბანანის ჩხირები',
    titleEn: 'Banana Sticks',
    descriptionKa: 'მწიფე ბანანი გაფცქვენით და გრძელ ჩხირებად დაჭერით. ბავშვი ხელით ადვილად მოიჭერს. BLW-სთვის იდეალურია, რადგან ბანანი ბუნებრივად რბილია.',
    descriptionEn: 'Peel ripe banana and cut into long sticks. Baby can easily grip by hand. Ideal for BLW as banana is naturally soft.',
    ingredientsKa: ['მწიფე ბანანი - 55 გ'],
    ingredientsEn: ['Ripe banana - 55g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 49, proteinGrams: 1, fatGrams: 0.2, carbsGrams: 12.5, fiberGrams: 1.4,
    ironMg: 0.14, vitaminCmg: 4.8, vitaminB6mg: 0.22, folateMcg: 11, potassiumMg: 197, magnesiumMg: 15,
    blwNoteKa: 'ბუნებრივად რბილია — ხელით მოსაჭერად საუკეთესო პირველი საკვები.',
    blwNoteEn: 'Naturally soft — an excellent first self-feeding food.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ, თუ ჯერ პიურეზე ხართ.',
    pureeNoteEn: 'Mash with a fork if still on purees.',
  },
  {
    titleKa: 'ავოკადოს ნაჭრები',
    titleEn: 'Avocado Pieces',
    descriptionKa: 'მწიფე ავოკადო გაფცქვენით და გრძელ ნაჭრებად დაჭერით. ბუნებრივი ცხიმებით მდიდარი სნექია. ახლადმომზადებული მიეცით — ავოკადო სწრაფად ჟანგდება.',
    descriptionEn: 'Peel ripe avocado and cut into long pieces. A snack rich in natural fats. Serve freshly prepared — avocado darkens quickly.',
    ingredientsKa: ['რბილი ავოკადო - 35 გ'],
    ingredientsEn: ['Soft avocado - 35g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 56, proteinGrams: 1, fatGrams: 5.1, carbsGrams: 3, fiberGrams: 2.3,
    vitaminCmg: 3.5, vitaminEmg: 0.72, vitaminKmcg: 7.4, vitaminB6mg: 0.09, folateMcg: 28, potassiumMg: 170, magnesiumMg: 10,
    blwNoteKa: 'ჭრილობის ზედაპირზე ცოტა ლიმონის წვენი შეაპკურეთ, რომ არ გაშავდეს, სანამ მიირთმევს.',
    blwNoteEn: 'A little lemon juice on the cut surface keeps it from browning before baby eats it.',
    pureeNoteKa: 'ჩანგლით სრულად გლუვად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash completely smooth with a fork.',
  },
  {
    titleKa: 'ორთქლზე მომზადებული მსხალი',
    titleEn: 'Steamed Pear',
    descriptionKa: 'მსხალი გაფცქვენით, გული ამოიღეთ და ორთქლზე 5-7 წუთი მოხარშეთ, სანამ რბილი გახდება. გრძელ ჩხირებად დაჭერით. მიეცით ოდნავ გაგრილებული.',
    descriptionEn: 'Peel pear, remove core and steam for 5-7 minutes until soft. Cut into long sticks. Serve slightly cooled.',
    ingredientsKa: ['მსხალი - 60 გ'],
    ingredientsEn: ['Pear - 60g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 34, proteinGrams: 0, fatGrams: 0.1, carbsGrams: 9.1, fiberGrams: 1.9,
    vitaminCmg: 2.6, folateMcg: 4, potassiumMg: 70,
    blwNoteKa: 'დარწმუნდით, რომ ჩხირი ორთქლის შემდეგ საკმარისად რბილია, რომ ორ თითს შორის ადვილად გაჭყლიტოთ.',
    blwNoteEn: 'Make sure the stick is soft enough after steaming to squash easily between two fingers.',
    pureeNoteKa: 'ბლენდერით გლუვ ფაფად აქციეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'ორთქლზე მომზადებული ვაშლი',
    titleEn: 'Steamed Apple',
    descriptionKa: 'ვაშლი გაფცქვენით, გული ამოიღეთ და ორთქლზე 7-10 წუთი მოხარშეთ სრულ დარბილებამდე. გრძელ ჩხირებად დაჭერით. მიეცით ოდნავ გაგრილებული.',
    descriptionEn: 'Peel apple, remove core and steam for 7-10 minutes until fully soft. Cut into long sticks. Serve slightly cooled.',
    ingredientsKa: ['ვაშლი - 60 გ'],
    ingredientsEn: ['Apple - 60g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 31, proteinGrams: 0, fatGrams: 0.1, carbsGrams: 8.3, fiberGrams: 1.4,
    vitaminCmg: 2.8, folateMcg: 2, potassiumMg: 64,
    blwNoteKa: 'ნედლი ვაშლი მაგარია და საშიშია დახრჩობის კუთხით — ყოველთვის ორთქლზე დაარბილეთ.',
    blwNoteEn: 'Raw apple is hard and a choking risk — always steam-soften it first.',
    pureeNoteKa: 'ბლენდერით გლუვ ფაფად აქციეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'ატმის ნაჭრები',
    titleEn: 'Peach Pieces',
    descriptionKa: 'მწიფე ატამი გაფცქვენით, კურკა ამოიღეთ. თუ ძალიან რბილია, ახალი მიეცით. თუ მაგარია, ორთქლზე ოდნავ დაარბილეთ. გრძელ ნაჭრებად დაჭერით.',
    descriptionEn: 'Peel ripe peach and remove pit. If very soft, serve fresh. If firm, soften slightly by steaming. Cut into long pieces.',
    ingredientsKa: ['მწიფე ატამი - 60 გ'],
    ingredientsEn: ['Ripe peach - 60g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 23, proteinGrams: 1, fatGrams: 0.2, carbsGrams: 5.7, fiberGrams: 0.9,
    vitaminCmg: 4, vitaminAmcg: 10, potassiumMg: 114,
    blwNoteKa: 'აირჩიეთ ძალიან მწიფე ატამი — მაგარი ნაწილები დახრჩობის რისკს ზრდის.',
    blwNoteEn: 'Choose a very ripe peach — firm parts increase choking risk.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or blend.',
  },
  {
    titleKa: 'მანგოს ჩხირები',
    titleEn: 'Mango Sticks',
    descriptionKa: 'მწიფე მანგო გაფცქვენით და გრძელ ჩხირებად დაჭერით. ვიტამინ C-ითა და A-ით მდიდარი სნექია. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Peel ripe mango and cut into long sticks. A snack rich in vitamin C and A. Serve freshly prepared.',
    ingredientsKa: ['მწიფე მანგო - 55 გ'],
    ingredientsEn: ['Ripe mango - 55g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 33, proteinGrams: 0, fatGrams: 0.2, carbsGrams: 8.3, fiberGrams: 0.9,
    vitaminCmg: 20, vitaminAmcg: 30, folateMcg: 24, potassiumMg: 92,
    blwNoteKa: 'მანგო სრიალაა — ერთ ბოლოზე ცოტა კანი დატოვეთ სამარჯვად, თუ შესაძლებელია.',
    blwNoteEn: 'Mango is slippery — leaving a bit of skin at one end as a handle can help.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or blend.',
  },
  {
    titleKa: 'ტკბილი კარტოფილის ჩხირები',
    titleEn: 'Sweet Potato Sticks',
    descriptionKa: 'ტკბილი კარტოფილი გაფცქვენით და ჩხირებად დაჭერით. ორთქლზე 10-12 წუთი მოხარშეთ სრულ დარბილებამდე. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel sweet potato and cut into sticks. Steam for 10-12 minutes until fully soft. Serve slightly cooled.',
    ingredientsKa: ['ტკბილი კარტოფილი - 65 გ'],
    ingredientsEn: ['Sweet potato - 65g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 59, proteinGrams: 1, fatGrams: 0.1, carbsGrams: 13.5, fiberGrams: 2.1,
    ironMg: 0.45, calciumMg: 25, vitaminCmg: 12.7, vitaminAmcg: 625, vitaminB6mg: 0.19,
    potassiumMg: 309, magnesiumMg: 18,
    blwNoteKa: 'ჩხირი საჩვენებელი თითივით სქელი გააკეთეთ, რომ ბავშვს ხელით მოსახელთებელი იყოს.',
    blwNoteEn: 'Cut the stick as thick as an adult finger, so it\'s easy for baby to grip.',
    pureeNoteKa: 'ბლენდერით გლუვ, სქელ პიურედ აქციეთ.',
    pureeNoteEn: 'Blend into a smooth, thick puree.',
  },
  {
    titleKa: 'ბროკოლის ყვავილები',
    titleEn: 'Broccoli Florets',
    descriptionKa: 'ბროკოლი ყვავილებად გაყავით. ორთქლზე 5-7 წუთი მოხარშეთ — ძალიან რბილი, მაგრამ ფაფად კი არ უნდა იქცეს. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Divide broccoli into florets. Steam for 5-7 minutes — should be very soft but not mushy. Serve slightly cooled.',
    ingredientsKa: ['ბროკოლი - 65 გ'],
    ingredientsEn: ['Broccoli - 65g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 23, proteinGrams: 2, fatGrams: 0.3, carbsGrams: 4.7, fiberGrams: 2.1,
    ironMg: 0.47, calciumMg: 26, vitaminCmg: 42.2, vitaminAmcg: 20, vitaminKmcg: 91.7,
    folateMcg: 70, potassiumMg: 190,
    blwNoteKa: 'ღეროზე შემორჩენილი ყვავილები ბუნებრივ სახელურს ქმნის, რომ ბავშვმა ადვილად აიღოს.',
    blwNoteEn: 'Florets left on a bit of stalk make a natural handle for baby to grip.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ დამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'ყვავილოვანი კომბოსტოს ყვავილები',
    titleEn: 'Cauliflower Florets',
    descriptionKa: 'ყვავილოვანი კომბოსტო ყვავილებად გაყავით. ორთქლზე 7-10 წუთი მოხარშეთ სრულ დარბილებამდე. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Divide cauliflower into florets. Steam for 7-10 minutes until fully soft. Serve slightly cooled.',
    ingredientsKa: ['ყვავილოვანი კომბოსტო - 65 გ'],
    ingredientsEn: ['Cauliflower - 65g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 15, proteinGrams: 1, fatGrams: 0.3, carbsGrams: 2.7, fiberGrams: 1.5,
    vitaminCmg: 28.8, vitaminKmcg: 10.1, folateMcg: 29, potassiumMg: 92,
    blwNoteKa: 'ღეროზე შემორჩენილი ყვავილები ბუნებრივ სახელურს ქმნის.',
    blwNoteEn: 'Florets left on a bit of stalk make a natural handle.',
    pureeNoteKa: 'ბლენდერით ძალიან გლუვ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a very smooth puree.',
  },
  {
    titleKa: 'ავოკადო და ბანანი',
    titleEn: 'Avocado and Banana',
    descriptionKa: 'ავოკადო და ბანანი ჩანგლით ერთად დაჭყლიტეთ ან ცალ-ცალკე ჩხირებად დაჭერით. ჯანსაღი ცხიმებისა და კალიუმის შესანიშნავი წყაროა.',
    descriptionEn: 'Mash avocado and banana together with a fork, or cut separately into sticks. An excellent source of healthy fats and potassium.',
    ingredientsKa: ['ავოკადო - 30 გ', 'ბანანი - 30 გ'],
    ingredientsEn: ['Avocado - 30g', 'Banana - 30g'],
    ageGroups: ['FROM_6'], mealType: 'SNACK', allergens: [],
    calories: 75, proteinGrams: 1, fatGrams: 4.5, carbsGrams: 9.4, fiberGrams: 2.8,
    ironMg: 0.08, vitaminCmg: 5.6, vitaminEmg: 0.62, vitaminKmcg: 6.3, vitaminB6mg: 0.2,
    folateMcg: 30, potassiumMg: 253, magnesiumMg: 17,
    blwNoteKa: 'ცალ-ცალკე ჩხირებად შესთავაზეთ, რომ ბავშვმა თავად აირჩიოს ტექსტურა.',
    blwNoteEn: 'Offer as separate sticks so baby can explore each texture independently.',
    pureeNoteKa: 'ერთად ჩანგლით გლუვად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash together smoothly with a fork.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 9-11 MONTHS (FROM_9) — SNACK
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბანანის ბლინები',
    titleEn: 'Banana Pancakes',
    descriptionKa: 'ბანანი კარგად დაჭყლიტეთ. კვერცხი ავურიეთ და შეუმატეთ. ზეთის გარეშე ან მინიმალური ზეთით პატარა ბლინები გამოაცხვეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Mash banana well. Beat egg and add. Cook small pancakes with no or minimal oil. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ბანანი - 1 მწიფე (60 გ)', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Banana - 1 ripe (60g)', 'Egg - 1'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['egg'],
    calories: 131, proteinGrams: 7, fatGrams: 5.7, carbsGrams: 14.2, fiberGrams: 1.6,
    ironMg: 1.03, calciumMg: 28, vitaminCmg: 5.2, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminB6mg: 0.24, vitaminB12mcg: 0.65, folateMcg: 36, zincMg: 0.65, potassiumMg: 215, magnesiumMg: 16, phosphorusMg: 99,
    blwNoteKa: 'პატარა, მრგვალი ბლინები ბავშვისთვის ხელით მისაღებად მოხერხებულია.',
    blwNoteEn: 'Small round pancakes are convenient for self-feeding.',
    pureeNoteKa: 'ბლინი ჩანგლით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash pancake with a fork.',
  },
  {
    titleKa: 'მოცვის შვრიის მაფინები',
    titleEn: 'Blueberry Oat Muffins',
    descriptionKa: 'შვრიის ფქვილი, ბანანი და მოცვი შეურიეთ. მინი მაფინის ფორმებში ჩაასხით. 180°C-ზე 15-18 წუთი გამოაცხვეთ. ოდნავ გაგრილებული ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Mix oat flour, banana and blueberries. Pour into mini muffin forms. Bake at 180°C for 15-18 minutes. Serve slightly cooled in age-appropriate pieces.',
    ingredientsKa: ['მოცვი - 35 გ', 'შვრიის ფქვილი - 55 გ', 'ბანანი - 1 მწიფე (55 გ)'],
    ingredientsEn: ['Blueberry - 35g', 'Oat flour - 55g', 'Banana - 1 ripe (55g)'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 291, proteinGrams: 9, fatGrams: 5.3, carbsGrams: 53.9, fiberGrams: 5.8,
    ironMg: 2.62, vitaminCmg: 8.2, vitaminKmcg: 6.8, vitaminB6mg: 0.22, folateMcg: 29,
    zincMg: 1.76, potassiumMg: 224, magnesiumMg: 94, phosphorusMg: 237,
    blwNoteKa: 'მინი მაფინი ბავშვის ხელში ხვდება — მარტივია ხელით კვებისთვის.',
    blwNoteEn: 'Mini muffin fits in baby\'s hand — easy for self-feeding.',
    pureeNoteKa: 'მაფინი ჩანგლით დაჭყლიტეთ ან ოდნავ გამდელეთ.',
    pureeNoteEn: 'Mash muffin with fork or soften slightly.',
  },
  {
    titleKa: 'ავოკადო ტოსტზე',
    titleEn: 'Avocado on Toast',
    descriptionKa: 'მთლიანი მარცვლის პური შეწვით. ავოკადო ჩანგლით დაჭყლიტეთ და პურზე წაუსვით. ასაკის შესაბამის ზომებად დაჭერით. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Toast whole grain bread. Mash avocado with fork and spread on bread. Cut into age-appropriate sized pieces. Serve freshly made.',
    ingredientsKa: ['ავოკადო - 30 გ', 'მთლიანი მარცვლის პური - 1 ნაჭერი (30 გ)'],
    ingredientsEn: ['Avocado - 30g', 'Whole grain bread - 1 slice (30g)'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 122, proteinGrams: 5, fatGrams: 5.4, carbsGrams: 14.9, fiberGrams: 4.1,
    ironMg: 0.75, vitaminCmg: 3, vitaminEmg: 0.62, vitaminKmcg: 6.3, vitaminB6mg: 0.13,
    folateMcg: 37, potassiumMg: 146, magnesiumMg: 33,
    blwNoteKa: 'ტოსტი გრძელ, თითის ტოლ ზოლებად დაჭერით.',
    blwNoteEn: 'Cut toast into long, finger-width strips.',
    pureeNoteKa: 'ავოკადო პურის გარეშეც შეიძლება, ჩანგლით დაჭყლეტილი.',
    pureeNoteEn: 'Avocado can also be served plain, mashed with a fork, without the bread.',
  },
  {
    titleKa: 'იოგურტი ბანანით',
    titleEn: 'Yogurt with Banana',
    descriptionKa: 'ბანანი ჩანგლით დაჭყლიტეთ. ბუნებრივ იოგურტს შეუმატეთ და ავურიეთ. კოვზით ასაკის შესაბამის ზომებად მიეცით. შაქრის გარეშე.',
    descriptionEn: 'Mash banana with fork. Add to natural yogurt and mix. Serve by spoon in age-appropriate amounts. Without sugar.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 70 გ', 'ბანანი - 30 გ'],
    ingredientsEn: ['Natural yogurt - 70g', 'Banana - 30g'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 69, proteinGrams: 3, fatGrams: 2.4, carbsGrams: 10.1, fiberGrams: 0.8,
    ironMg: 0.08, calciumMg: 85, vitaminCmg: 2.6, vitaminB6mg: 0.12, vitaminB12mcg: 0.35,
    folateMcg: 6, potassiumMg: 216, magnesiumMg: 8, phosphorusMg: 67,
    blwNoteKa: 'შესთავაზეთ წინასწარ დატვირთული კოვზი, თავად ვერ ცოცხავს ჯერ სწორად.',
    blwNoteEn: 'Offer a pre-loaded spoon — baby can\'t yet scoop it independently.',
    pureeNoteKa: 'ბანანი კარგად დაჭყლიტეთ, გლუვად შეურიეთ.',
    pureeNoteEn: 'Mash banana well and mix in smoothly.',
  },
  {
    titleKa: 'ორთქლზე მომზადებული სტაფილო',
    titleEn: 'Steamed Carrot',
    descriptionKa: 'სტაფილო გაფცქვენით და გრძელ ჩხირებად დაჭერით. ორთქლზე 10-15 წუთი მოხარშეთ სრულ დარბილებამდე. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel carrot and cut into long sticks. Steam for 10-15 minutes until fully soft. Serve slightly cooled.',
    ingredientsKa: ['სტაფილო - 65 გ'],
    ingredientsEn: ['Carrot - 65g'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: [],
    calories: 23, proteinGrams: 0, fatGrams: 0.1, carbsGrams: 5.3, fiberGrams: 2,
    vitaminCmg: 2, vitaminAmcg: 554, vitaminKmcg: 5.6, potassiumMg: 153,
    blwNoteKa: 'დარწმუნდით, რომ ჩხირი ორ თითს შორის ადვილად იჭყლიტება — მაგარი სტაფილო დახრჩობის რისკია.',
    blwNoteEn: 'Make sure the stick squashes easily between two fingers — firm carrot is a choking risk.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ დაამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'მარწყვის ნაჭრები',
    titleEn: 'Strawberry Pieces',
    descriptionKa: 'მარწყვი კარგად გარეცხეთ. 9 თვის ბავშვისთვის მეოთხედებად დაჭერით. 10+ თვის ბავშვისთვის ნახევრებად. ახლადგარეცხილი, ოთახის ტემპერატურაზე მიეცით.',
    descriptionEn: 'Wash strawberries well. For 9-month baby cut into quarters. For 10+ months cut in halves. Serve freshly washed at room temperature.',
    ingredientsKa: ['მწიფე მარწყვი - 45 გ'],
    ingredientsEn: ['Ripe strawberry - 45g'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['strawberry'],
    calories: 14, proteinGrams: 0, fatGrams: 0.1, carbsGrams: 3.5, fiberGrams: 0.9,
    vitaminCmg: 26.5, folateMcg: 11, potassiumMg: 69,
    blwNoteKa: 'მთლიანი პატარა მარწყვი დახრჩობის რისკია — ყოველთვის დაჭერით.',
    blwNoteEn: 'Whole small strawberries are a choking risk — always cut them.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or blend.',
  },
  {
    titleKa: 'ხაჭო ატმით',
    titleEn: 'Cottage Cheese with Peach',
    descriptionKa: 'ატამი გაფცქვენით, კურკა ამოიღეთ და წვრილად დაჭერით ან ჩაჭყლიტეთ. ხაჭოს შეუმატეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Peel peach, remove pit and finely chop or mash. Add to cottage cheese. Serve in age-appropriate amounts.',
    ingredientsKa: ['ხაჭო - 65 გ', 'ატამი - 55 გ'],
    ingredientsEn: ['Cottage cheese - 65g', 'Peach - 55g'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 76, proteinGrams: 8, fatGrams: 1.6, carbsGrams: 7.4, fiberGrams: 0.8,
    calciumMg: 54, vitaminCmg: 3.6, vitaminAmcg: 9, vitaminB12mcg: 0.28, potassiumMg: 172,
    phosphorusMg: 99, sodiumMg: 237,
    blwNoteKa: 'შესთავაზეთ წინასწარ დატვირთული კოვზი ან ატამი ცალკე ნაჭრებად.',
    blwNoteEn: 'Offer a pre-loaded spoon, or the peach in separate pieces.',
    pureeNoteKa: 'ორივე ერთად ჩანგლით გლუვად აურიეთ.',
    pureeNoteEn: 'Mix both together smoothly with a fork.',
  },
  {
    titleKa: 'ტკბილი კარტოფილის ჩხირები',
    titleEn: 'Sweet Potato Sticks',
    descriptionKa: 'ტკბილი კარტოფილი გაფცქვენით და ჩხირებად დაჭერით. ორთქლზე 10-12 წუთი მოხარშეთ. 9-11 თვის ბავშვი ჩხირს დამოუკიდებლად მოიჭერს.',
    descriptionEn: 'Peel sweet potato and cut into sticks. Steam for 10-12 minutes. A 9-11 month baby can independently grip the stick.',
    ingredientsKa: ['ტკბილი კარტოფილი - 65 გ'],
    ingredientsEn: ['Sweet potato - 65g'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: [],
    calories: 59, proteinGrams: 1, fatGrams: 0.1, carbsGrams: 13.5, fiberGrams: 2.1,
    ironMg: 0.45, calciumMg: 25, vitaminCmg: 12.7, vitaminAmcg: 625, vitaminB6mg: 0.19,
    potassiumMg: 309, magnesiumMg: 18,
    blwNoteKa: 'ამ ასაკში ბავშვს პინცეტისებრი ჩაჭიდება უვითარდება — ჩხირი ცოტა უფრო წვრილიც შეიძლება.',
    blwNoteEn: 'At this age the pincer grasp is developing — sticks can be a bit thinner too.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ დაამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'შვრიის მინი მაფინები',
    titleEn: 'Mini Oat Muffins',
    descriptionKa: 'შვრიის ფქვილი და ბანანი შეურიეთ. მინი ფორმებში ჩაასხით. 180°C-ზე 15 წუთი გამოაცხვეთ. ოდნავ გაგრილებული ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Mix oat flour and banana. Pour into mini forms. Bake at 180°C for 15 minutes. Serve slightly cooled in age-appropriate pieces.',
    ingredientsKa: ['შვრიის ფქვილი - 55 გ', 'ბანანი - 1 მწიფე (60 გ)'],
    ingredientsEn: ['Oat flour - 55g', 'Banana - 1 ripe (60g)'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 276, proteinGrams: 9, fatGrams: 5.2, carbsGrams: 50, fiberGrams: 5.1,
    ironMg: 2.63, vitaminCmg: 5.2, vitaminB6mg: 0.24, folateMcg: 30, zincMg: 1.76,
    potassiumMg: 215, magnesiumMg: 95, phosphorusMg: 237,
    blwNoteKa: 'მინი მაფინი ხელში ხვდება — მარტივია ხელით კვებისთვის.',
    blwNoteEn: 'Mini muffin fits in the hand — easy for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ოდნავ გამდელეთ.',
    pureeNoteEn: 'Mash with fork or soften slightly.',
  },
  {
    titleKa: 'ავოკადო და მსხალი',
    titleEn: 'Avocado and Pear',
    descriptionKa: 'ავოკადო გრძელ ნაჭრებად დაჭერით. მსხალი ორთქლზე მოხარშეთ (ან თუ ძალიან მწიფეა, ახლადაც შეიძლება) და ასევე ნაჭრებად. ცალ-ცალკე მიეცით.',
    descriptionEn: 'Cut avocado into long pieces. Steam pear (or serve fresh if very ripe) and also cut into pieces. Serve separately.',
    ingredientsKa: ['ავოკადო - 30 გ', 'მსხალი - 55 გ'],
    ingredientsEn: ['Avocado - 30g', 'Pear - 55g'],
    ageGroups: ['FROM_9'], mealType: 'SNACK', allergens: [],
    calories: 79, proteinGrams: 1, fatGrams: 4.5, carbsGrams: 10.9, fiberGrams: 3.7,
    vitaminCmg: 5.4, vitaminEmg: 0.62, vitaminKmcg: 6.3, vitaminB6mg: 0.08, folateMcg: 28,
    potassiumMg: 209, magnesiumMg: 9,
    blwNoteKa: 'ცალ-ცალკე შესთავაზეთ, რომ ბავშვმა თითოეული ტექსტურა ცალკე შეისწავლოს.',
    blwNoteEn: 'Offer separately so baby can explore each texture on its own.',
    pureeNoteKa: 'ორივე ერთად ჩანგლით გლუვად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash both together smoothly with a fork.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 12-18 MONTHS (FROM_12) — SNACK — inspired by USDA MyPlate Kitchen
  // yogurt-parfait and energy-bite recipes (myplate.food/recipes)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ჩიას პუდინგი',
    titleEn: 'Chia Pudding',
    descriptionKa: 'ჩიას თესლი რძეში ჩაყარეთ, კარგად ავურიეთ. 15-20 წუთი ან ღამით დაისვენეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Add chia seeds to milk, stir well. Rest for 15-20 minutes or overnight. Serve in age-appropriate amounts.',
    ingredientsKa: ['ჩიას თესლი - 10 გ', 'რძე - 100 მლ'],
    ingredientsEn: ['Chia seeds - 10g', 'Milk - 100ml'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 110, proteinGrams: 5, fatGrams: 6.4, carbsGrams: 9, fiberGrams: 3.4,
    ironMg: 0.77, calciumMg: 176, vitaminDmcg: 1.3, vitaminB12mcg: 0.45, zincMg: 0.46,
    potassiumMg: 173, magnesiumMg: 34, phosphorusMg: 170, omega3Mg: 1780,
  },
  {
    titleKa: 'იოგურტი მოცვით',
    titleEn: 'Yogurt with Blueberry',
    descriptionKa: 'ბუნებრივი იოგურტი თასში ჩაასხით. მოცვი ზემოდან დაუმატეთ — ნახევარი მთელი, ნახევარი ჩაჭყლეტილი. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Pour natural yogurt into a bowl. Add blueberries on top — half whole, half crushed. Serve in age-appropriate amounts.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 90 გ', 'მოცვი - 35 გ'],
    ingredientsEn: ['Natural yogurt - 90g', 'Blueberry - 35g'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 75, proteinGrams: 3, fatGrams: 3.1, carbsGrams: 9.3, fiberGrams: 0.8,
    calciumMg: 109, vitaminCmg: 3.4, vitaminKmcg: 6.8, vitaminB12mcg: 0.45, potassiumMg: 166, phosphorusMg: 86,
  },
  {
    titleKa: 'მინი შვრიის მაფინები',
    titleEn: 'Mini Oat Muffins',
    descriptionKa: 'შვრიის ფქვილი და ბანანი კარგად შეურიეთ. მინი ფორმებში ჩაასხით. 180°C-ზე 15-18 წუთი გამოაცხვეთ. ოდნავ გაგრილებული ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Mix oat flour and banana well. Pour into mini forms. Bake at 180°C for 15-18 minutes. Serve slightly cooled in age-appropriate pieces.',
    ingredientsKa: ['შვრიის ფქვილი - 65 გ', 'ბანანი - 1 მწიფე (60 გ)'],
    ingredientsEn: ['Oat flour - 65g', 'Banana - 1 ripe (60g)'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 316, proteinGrams: 10, fatGrams: 6.1, carbsGrams: 56.6, fiberGrams: 5.8,
    ironMg: 3.08, vitaminCmg: 5.2, vitaminB6mg: 0.24, folateMcg: 33, zincMg: 2.08,
    potassiumMg: 215, magnesiumMg: 110, phosphorusMg: 280,
  },
  {
    titleKa: 'ავოკადოს ტოსტი',
    titleEn: 'Avocado Toast',
    descriptionKa: 'პური შეწვით. ავოკადო ჩანგლით გლუვად დაჭყლიტეთ და პურზე წაუსვით. ასაკის შესაბამის ზომებად დაჭერით. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Toast bread. Mash avocado smoothly with fork and spread on bread. Cut into age-appropriate sized pieces. Serve freshly made.',
    ingredientsKa: ['ავოკადო - 35 გ', 'პური - 1 ნაჭერი (25 გ)'],
    ingredientsEn: ['Avocado - 35g', 'Bread - 1 slice (25g)'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 122, proteinGrams: 3, fatGrams: 5.9, carbsGrams: 15.2, fiberGrams: 3,
    ironMg: 0.9, vitaminCmg: 3.5, vitaminEmg: 0.72, vitaminKmcg: 7.4, vitaminB6mg: 0.09,
    folateMcg: 65, potassiumMg: 170, magnesiumMg: 10,
  },
  {
    titleKa: 'ხაჭო მარწყვით',
    titleEn: 'Cottage Cheese with Strawberry',
    descriptionKa: 'მარწყვი გარეცხეთ და წვრილ ნაჭრებად დაჭერით. ხაჭოს შეუმატეთ. ასაკის შესაბამის ზომებად მიეცით. კალციუმისა და ვიტამინ C-ის შესანიშნავი კომბინაციაა.',
    descriptionEn: 'Wash strawberries and cut into small pieces. Add to cottage cheese. Serve in age-appropriate amounts. An excellent combination of calcium and vitamin C.',
    ingredientsKa: ['ხაჭო - 75 გ', 'მარწყვი - 35 გ'],
    ingredientsEn: ['Cottage cheese - 75g', 'Strawberry - 35g'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['dairy', 'strawberry'],
    calories: 74, proteinGrams: 9, fatGrams: 1.8, carbsGrams: 5.2, fiberGrams: 0.7,
    calciumMg: 62, vitaminCmg: 20.6, vitaminB12mcg: 0.32, folateMcg: 8, potassiumMg: 132, phosphorusMg: 114, sodiumMg: 273,
  },
  {
    titleKa: 'ბანანის ენერგეტიკული ბურთულები',
    titleEn: 'Banana Energy Balls',
    descriptionKa: 'ბანანი კარგად დაჭყლიტეთ. შვრია შეუმატეთ და კარგად შეურიეთ. პატარა ბურთულები ჩამოაყალიბეთ. მაცივარში 30 წუთი შედეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Mash banana well. Add oats and mix well. Shape into small balls. Refrigerate for 30 minutes. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ბანანი - 1 მწიფე (60 გ)', 'შვრიის ფანტელი - 45 გ'],
    ingredientsEn: ['Banana - 1 ripe (60g)', 'Oats - 45g'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 228, proteinGrams: 8, fatGrams: 3.3, carbsGrams: 43.5, fiberGrams: 6.3,
    ironMg: 2.27, calciumMg: 24, vitaminCmg: 5.2, vitaminEmg: 0.31, vitaminB6mg: 0.28,
    folateMcg: 37, zincMg: 1.8, potassiumMg: 408, magnesiumMg: 96, phosphorusMg: 235,
  },
  {
    titleKa: 'ვაშლის ნაჭრები არაქისის კარაქით',
    titleEn: 'Apple Slices with Peanut Butter',
    descriptionKa: 'ვაშლი თხელ ნაჭრებად დაჭერით. არაქისის კარაქი თხელი ფენით წაუსვით. ახლადმომზადებული მიეცით. არაქისი ერთ-ერთი მთავარი ალერგენია — პირველად მცირე რაოდენობით სცადეთ.',
    descriptionEn: 'Cut apple into thin slices. Spread thin layer of peanut butter. Serve freshly made. Peanut is a major allergen — try in small amounts first.',
    ingredientsKa: ['ვაშლი - 55 გ', 'არაქისის კარაქი - 1 ჩ/კ (5 გ)'],
    ingredientsEn: ['Apple - 55g', 'Peanut butter - 1 tsp (5g)'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['peanut'],
    calories: 58, proteinGrams: 1, fatGrams: 2.6, carbsGrams: 8.6, fiberGrams: 1.6,
    vitaminCmg: 2.5, vitaminEmg: 0.45, folateMcg: 2, zincMg: 0.14, potassiumMg: 91, magnesiumMg: 8,
  },
  {
    titleKa: 'ყველის კუბიკები',
    titleEn: 'Cheese Cubes',
    descriptionKa: 'პასტერიზებული ყველი პატარა კუბიკებად დაჭერით. ასაკის შესაბამის ზომებად მიეცით. კალციუმით მდიდარი, ადვილად მოსამზადებელი სნექია.',
    descriptionEn: 'Cut pasteurized cheese into small cubes. Serve in age-appropriate sized pieces. A calcium-rich, easy-to-prepare snack.',
    ingredientsKa: ['პასტერიზებული ყველი - 25 გ'],
    ingredientsEn: ['Pasteurized cheese - 25g'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 101, proteinGrams: 6, fatGrams: 8.3, carbsGrams: 0.3,
    calciumMg: 180, vitaminAmcg: 66, vitaminB12mcg: 0.21, zincMg: 0.78, phosphorusMg: 128, sodiumMg: 155,
  },
  {
    titleKa: 'მოცვის ბლინები',
    titleEn: 'Blueberry Pancakes',
    descriptionKa: 'კვერცხი ავურიეთ. მოცვი დაუმატეთ. ზეთის მინიმალური რაოდენობით პატარა ბლინები გამოაცხვეთ. ოდნავ გაგრილებული ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Beat egg. Add blueberries. Cook small pancakes with minimal oil. Serve slightly cooled in age-appropriate pieces.',
    ingredientsKa: ['მოცვი - 45 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Blueberry - 45g', 'Egg - 1'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['egg'],
    calories: 103, proteinGrams: 7, fatGrams: 5.6, carbsGrams: 7.1, fiberGrams: 1.1,
    ironMg: 0.88, calciumMg: 28, vitaminCmg: 4.4, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminKmcg: 8.7, vitaminB12mcg: 0.65, folateMcg: 24, zincMg: 0.65, potassiumMg: 35, phosphorusMg: 99,
  },
  {
    titleKa: 'ხილის თეფში',
    titleEn: 'Fruit Plate',
    descriptionKa: 'ბანანი, მსხალი და მარწყვი ასაკის შესაბამის ზომებად დაჭერით. ერთ თეფშზე მოაწყვეთ. ახლადგაჭრილი მიეცით. ვიტამინებისა და ბოჭკოების შესანიშნავი წყაროა.',
    descriptionEn: 'Cut banana, pear and strawberry into age-appropriate sized pieces. Arrange on one plate. Serve freshly cut. An excellent source of vitamins and fiber.',
    ingredientsKa: ['ბანანი - 25 გ', 'მსხალი - 25 გ', 'მარწყვი - 30 გ'],
    ingredientsEn: ['Banana - 25g', 'Pear - 25g', 'Strawberry - 30g'],
    ageGroups: ['FROM_12'], mealType: 'SNACK', allergens: ['strawberry'],
    calories: 46, proteinGrams: 1, fatGrams: 0.2, carbsGrams: 11.8, fiberGrams: 2,
    ironMg: 0.07, vitaminCmg: 20.9, vitaminB6mg: 0.1, folateMcg: 14, potassiumMg: 164, magnesiumMg: 7,
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 18-36 MONTHS (FROM_24) — SNACK — inspired by USDA MyPlate Kitchen
  // yogurt-parfait, energy-bite and muffin snacks (myplate.food/recipes)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'იოგურტის გრანოლა ბოული',
    titleEn: 'Yogurt Granola Bowl',
    descriptionKa: 'ბუნებრივი იოგურტი თასში ჩაასხით. გრანოლა ზემოდან დაუმატეთ. ბანანის ნაჭრები ზემოდან. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Pour natural yogurt into bowl. Add granola on top. Add banana pieces on top. Serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 110 გ', 'გრანოლა - 25 გ', 'ბანანი - 30 გ'],
    ingredientsEn: ['Natural yogurt - 110g', 'Granola - 25g', 'Banana - 30g'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['dairy', 'gluten'],
    calories: 212, proteinGrams: 7, fatGrams: 8.7, carbsGrams: 28, fiberGrams: 2.5,
    ironMg: 0.7, calciumMg: 133, vitaminCmg: 2.6, vitaminB6mg: 0.12, vitaminB12mcg: 0.55,
    folateMcg: 6, potassiumMg: 278, magnesiumMg: 41, phosphorusMg: 105,
  },
  {
    titleKa: 'ვაშლი არაქისის კარაქით',
    titleEn: 'Apple with Peanut Butter',
    descriptionKa: 'ვაშლი თხელ ნაჭრებად დაჭერით. არაქისის კარაქი გვერდზე დადეთ — ბავშვი ნაჭერს ჩაუყავს. ახლადმომზადებული მიეცით. ენერგიისა და ჯანსაღი ცხიმების შესანიშნავი სნექია.',
    descriptionEn: 'Cut apple into thin slices. Place peanut butter on the side — child dips the slice. Serve freshly made. An excellent snack for energy and healthy fats.',
    ingredientsKa: ['ვაშლი - 55 გ', 'არაქისის კარაქი - 1-2 ჩ/კ (8 გ)'],
    ingredientsEn: ['Apple - 55g', 'Peanut butter - 1-2 tsp (8g)'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['peanut'],
    calories: 76, proteinGrams: 2, fatGrams: 4.1, carbsGrams: 9.2, fiberGrams: 1.8,
    vitaminCmg: 2.5, vitaminEmg: 0.72, folateMcg: 2, zincMg: 0.23, potassiumMg: 111, magnesiumMg: 13,
  },
  {
    titleKa: 'ყველი და ხილი',
    titleEn: 'Cheese and Fruit',
    descriptionKa: 'პასტერიზებული ყველი კუბიკებად ან ზოლებად დაჭერით. სეზონური ხილი ასაკის შესაბამის ზომებად. ერთ თეფშზე მოაწყვეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Cut pasteurized cheese into cubes or strips. Cut seasonal fruit into age-appropriate pieces. Arrange on one plate. Serve freshly made.',
    ingredientsKa: ['პასტერიზებული ყველი - 28 გ', 'ვაშლი - 55 გ'],
    ingredientsEn: ['Pasteurized cheese - 28g', 'Apple - 55g'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 141, proteinGrams: 7, fatGrams: 9.4, carbsGrams: 8, fiberGrams: 1.3,
    calciumMg: 202, vitaminCmg: 2.5, vitaminAmcg: 74, vitaminB12mcg: 0.23, folateMcg: 2,
    zincMg: 0.87, potassiumMg: 59, phosphorusMg: 143, sodiumMg: 174,
  },
  {
    titleKa: 'ბანანის შვრიის მაფინი',
    titleEn: 'Banana Oat Muffin',
    descriptionKa: 'ბანანი კარგად დაჭყლიტეთ. შვრიის ფქვილი შეუმატეთ. ფორმებში ჩაასხით. 180°C-ზე 18-20 წუთი გამოაცხვეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Mash banana well. Add oat flour. Pour into forms. Bake at 180°C for 18-20 minutes. Serve freshly made.',
    ingredientsKa: ['ბანანი - 2 მწიფე (100 გ)', 'შვრიის ფქვილი - 75 გ'],
    ingredientsEn: ['Banana - 2 ripe (100g)', 'Oat flour - 75g'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 392, proteinGrams: 12, fatGrams: 7.1, carbsGrams: 72.3, fiberGrams: 7.5,
    ironMg: 3.64, vitaminCmg: 8.7, vitaminB6mg: 0.4, folateMcg: 44, zincMg: 2.4,
    potassiumMg: 358, magnesiumMg: 135, phosphorusMg: 323,
  },
  {
    titleKa: 'ენერგეტიკული ბურთულები',
    titleEn: 'Energy Balls',
    descriptionKa: 'შვრია, დაჭყლეტილი ბანანი და თესლები (სეზამი, ჩია, სელი) შეურიეთ. პატარა ბურთულები ჩამოაყალიბეთ. მაცივარში 30 წუთი შედეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Mix oats, mashed banana and seeds (sesame, chia, flax). Shape into small balls. Refrigerate for 30 minutes. Serve freshly made.',
    ingredientsKa: ['შვრიის ფანტელი - 55 გ', 'ბანანი - 1 მწიფე (60 გ)', 'თესლები (სეზამი/ჩია/სელი) - 15 გ'],
    ingredientsEn: ['Oats - 55g', 'Banana - 1 ripe (60g)', 'Seeds (sesame/chia/flax) - 15g'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 345, proteinGrams: 13, fatGrams: 10.3, carbsGrams: 53.4, fiberGrams: 11.1,
    ironMg: 3.94, calciumMg: 90, vitaminCmg: 5.2, vitaminEmg: 0.39, vitaminB6mg: 0.3,
    folateMcg: 43, zincMg: 2.95, potassiumMg: 451, magnesiumMg: 159, phosphorusMg: 378, omega3Mg: 2250,
  },
  {
    titleKa: 'ხაჭო მოცვით',
    titleEn: 'Cottage Cheese with Blueberry',
    descriptionKa: 'ხაჭო თასში ჩაასხით. მოცვი ზემოდან დაუმატეთ. სასურველია ოდნავ ჩაჭყლეტილი, რომ ფერი გამოვიდეს. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Pour cottage cheese into bowl. Add blueberries on top. Preferably slightly crushed to release color. Serve freshly made.',
    ingredientsKa: ['ხაჭო - 90 გ', 'მოცვი - 35 გ'],
    ingredientsEn: ['Cottage cheese - 90g', 'Blueberry - 35g'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['dairy'],
    calories: 96, proteinGrams: 10, fatGrams: 2.2, carbsGrams: 8.1, fiberGrams: 0.8,
    calciumMg: 75, vitaminCmg: 3.4, vitaminKmcg: 6.8, vitaminB12mcg: 0.39, potassiumMg: 121, phosphorusMg: 137, sodiumMg: 328,
  },
  {
    titleKa: 'ავოკადოს ტოსტი',
    titleEn: 'Avocado Toast',
    descriptionKa: 'პური შეწვით. ავოკადო ჩანგლით დაჭყლიტეთ. პურზე წაუსვით. სასურველია ოდნავ ლიმონი გამოწუროთ ზემოდან. ასაკის შესაბამის ზომებად დაჭერით.',
    descriptionEn: 'Toast bread. Mash avocado with fork. Spread on bread. Optionally squeeze a little lemon on top. Cut into age-appropriate sized pieces.',
    ingredientsKa: ['ავოკადო - 45 გ', 'პური - 1 ნაჭერი (25 გ)'],
    ingredientsEn: ['Avocado - 45g', 'Bread - 1 slice (25g)'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 138, proteinGrams: 3, fatGrams: 7.4, carbsGrams: 16.1, fiberGrams: 3.7,
    ironMg: 0.9, vitaminCmg: 4.5, vitaminEmg: 0.93, vitaminKmcg: 9.5, vitaminB6mg: 0.12,
    folateMcg: 73, potassiumMg: 218, magnesiumMg: 13,
  },
  {
    titleKa: 'მინი სენდვიჩი',
    titleEn: 'Mini Sandwich',
    descriptionKa: 'პური ნახევრად დაჭერით. ყველი თხელ ფენად დადეთ. კვერცხი მოჩლუნგებულ სახით მოხარშეთ და დაუმატეთ. ნახევარი ან მეოთხედი სენდვიჩი ასაკის შესაბამისად მიეცით.',
    descriptionEn: 'Cut bread in half. Place a thin layer of cheese. Add scrambled egg. Serve half or quarter sandwich according to age.',
    ingredientsKa: ['პური - 1 ნაჭერი (25 გ)', 'ყველი - 18 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Bread - 1 slice (25g)', 'Cheese - 18g', 'Egg - 1'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['gluten', 'dairy', 'egg'],
    calories: 216, proteinGrams: 13, fatGrams: 12.2, carbsGrams: 13, fiberGrams: 0.7,
    ironMg: 1.78, calciumMg: 158, vitaminAmcg: 128, vitaminDmcg: 1, vitaminB12mcg: 0.79,
    folateMcg: 60, zincMg: 1.21, phosphorusMg: 191, sodiumMg: 112,
  },
  {
    titleKa: 'ხილის თეფში',
    titleEn: 'Fruit Plate',
    descriptionKa: 'მარწყვი, ბანანი და მსხალი ასაკის შესაბამის ზომებად დაჭერით. ერთ თეფშზე ლამაზად მოაწყვეთ. ახლადგაჭრილი მიეცით. სეზონური ხილის ნებისმიერი კომბინაცია შეიძლება.',
    descriptionEn: 'Cut strawberry, banana and pear into age-appropriate pieces. Arrange nicely on one plate. Serve freshly cut. Any combination of seasonal fruit works.',
    ingredientsKa: ['მარწყვი - 35 გ', 'ბანანი - 25 გ', 'მსხალი - 25 გ'],
    ingredientsEn: ['Strawberry - 35g', 'Banana - 25g', 'Pear - 25g'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['strawberry'],
    calories: 48, proteinGrams: 1, fatGrams: 0.2, carbsGrams: 12.2, fiberGrams: 2.1,
    ironMg: 0.07, vitaminCmg: 23.8, vitaminB6mg: 0.1, folateMcg: 15, potassiumMg: 172, magnesiumMg: 7,
  },
  {
    titleKa: 'შვრიის ორცხობილა',
    titleEn: 'Oat Cookies',
    descriptionKa: 'ბანანი კარგად დაჭყლიტეთ. შვრია შეუმატეთ. ბრტყელი ორცხობილები ჩამოაყალიბეთ. 180°C-ზე 12-15 წუთი გამოაცხვეთ. ოდნავ გაგრილებული ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Mash banana well. Add oats. Shape flat cookies. Bake at 180°C for 12-15 minutes. Serve slightly cooled in age-appropriate pieces.',
    ingredientsKa: ['შვრიის ფანტელი - 65 გ', 'ბანანი - 1 მწიფე (60 გ)'],
    ingredientsEn: ['Oats - 65g', 'Banana - 1 ripe (60g)'],
    ageGroups: ['FROM_24'], mealType: 'SNACK', allergens: ['gluten'],
    calories: 306, proteinGrams: 12, fatGrams: 4.7, carbsGrams: 56.8, fiberGrams: 8.5,
    ironMg: 3.21, calciumMg: 35, vitaminCmg: 5.2, vitaminEmg: 0.46, vitaminB6mg: 0.31,
    folateMcg: 48, zincMg: 2.6, potassiumMg: 494, magnesiumMg: 131, phosphorusMg: 340,
  },
];

async function main() {
  console.log('🌱 Seeding 40 snack recipes...');

  let created = 0;
  let skipped = 0;

  for (const r of recipes) {
    const existing = await prisma.dish.findFirst({
      where: { titleKa: r.titleKa, mealType: 'SNACK', ageGroups: { equals: r.ageGroups as any } },
    });

    if (existing) {
      skipped++;
      console.log(`  ⏭  Already exists: ${r.titleKa}`);
      continue;
    }

    await prisma.dish.create({
      data: {
        titleKa: r.titleKa,
        titleEn: r.titleEn,
        descriptionKa: r.descriptionKa,
        descriptionEn: r.descriptionEn,
        ingredientsKa: r.ingredientsKa,
        ingredientsEn: r.ingredientsEn,
        ageGroups: r.ageGroups as any,
        mealType: r.mealType as any,
        allergens: r.allergens || [],
        calories: (r as any).calories ?? null,
        proteinGrams: (r as any).proteinGrams ?? null,
        fatGrams: (r as any).fatGrams ?? null,
        carbsGrams: (r as any).carbsGrams ?? null,
        fiberGrams: (r as any).fiberGrams ?? null,
        ironMg: (r as any).ironMg ?? null,
        calciumMg: (r as any).calciumMg ?? null,
        vitaminCmg: (r as any).vitaminCmg ?? null,
        vitaminAmcg: (r as any).vitaminAmcg ?? null,
        vitaminDmcg: (r as any).vitaminDmcg ?? null,
        vitaminEmg: (r as any).vitaminEmg ?? null,
        vitaminKmcg: (r as any).vitaminKmcg ?? null,
        vitaminB6mg: (r as any).vitaminB6mg ?? null,
        vitaminB12mcg: (r as any).vitaminB12mcg ?? null,
        folateMcg: (r as any).folateMcg ?? null,
        zincMg: (r as any).zincMg ?? null,
        potassiumMg: (r as any).potassiumMg ?? null,
        magnesiumMg: (r as any).magnesiumMg ?? null,
        phosphorusMg: (r as any).phosphorusMg ?? null,
        sodiumMg: (r as any).sodiumMg ?? null,
        omega3Mg: (r as any).omega3Mg ?? null,
        blwNoteKa: (r as any).blwNoteKa ?? null,
        blwNoteEn: (r as any).blwNoteEn ?? null,
        pureeNoteKa: (r as any).pureeNoteKa ?? null,
        pureeNoteEn: (r as any).pureeNoteEn ?? null,
      },
    });
    created++;
    console.log(`  ✓  ${r.titleKa}`);
  }

  console.log(`\n✅ Done: ${created} created, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
