import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const recipes = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 6-8 MONTHS (FROM_6)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბანანისა და შვრიის ფაფა',
    titleEn: 'Banana Oat Porridge',
    descriptionKa: 'შვრია მოხარშეთ წყალში 5-7 წუთი, სანამ კარგად დარბილდება. ბანანი დაჭყლიტეთ ჩანგლით. შეურიეთ ფაფას და საჭიროების შემთხვევაში დააბლენდერეთ. მიეცით თბილი, არა ცხელი.',
    descriptionEn: 'Cook oats in water for 5-7 minutes until soft. Mash banana with a fork. Mix into porridge and blend if needed. Serve warm, not hot.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'მწიფე ბანანი - 50 გ', 'წყალი ან დედის რძე/ფორმულა - 120 მლ', 'ზეითუნის ზეთი ან კარაქი - 1/4 ჩ/კ (სურვილისამებრ)'],
    ingredientsEn: ['Oat flakes - 20g', 'Ripe banana - 50g', 'Water or breast milk/formula - 120ml', 'Olive oil or butter - 1/4 tsp (optional)'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 112, proteinGrams: 3, fatGrams: 1.65, carbsGrams: 24, fiberGrams: 3.4,
    ironMg: 0.9, potassiumMg: 240, magnesiumMg: 28, vitaminB6mg: 0.22, folateMcg: 15,
    allergens: ['gluten'],
    blwNoteKa: 'მოამზადეთ უფრო სქელი და შესთავაზეთ წინასწარ დატვირთულ კოვზზე.',
    blwNoteEn: 'Make thicker and serve on a pre-loaded spoon.',
    pureeNoteKa: 'დააბლენდერეთ სრულიად გლუვ მასად, განსაკუთრებით 6 თვის დასაწყისში.',
    pureeNoteEn: 'Blend completely smooth, especially at the start of 6 months.',
  },
  {
    titleKa: 'ვაშლისა და დარიჩინის შვრიის ფაფა',
    titleEn: 'Apple Cinnamon Oatmeal',
    descriptionKa: 'ვაშლი დაჭერით და ორთქლზე მოამზადეთ 7-10 წუთი. შვრია მოხარშეთ წყალში. ვაშლი დაჭყლიტეთ და შეურიეთ ფაფას. დაუმატეთ დარიჩინი მხოლოდ გემოსთვის.',
    descriptionEn: 'Slice apple and steam for 7-10 minutes. Cook oats in water. Mash apple and mix into porridge. Add cinnamon just for flavor.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'ვაშლი, გაფცქვნილი - 60 გ', 'წყალი - 120 მლ', 'დარიჩინი - ძალიან მცირე მწიკვი'],
    ingredientsEn: ['Oat flakes - 20g', 'Apple, peeled - 60g', 'Water - 120ml', 'Cinnamon - tiny pinch'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 108, proteinGrams: 3, fatGrams: 1.4, carbsGrams: 23, fiberGrams: 3.85,
    ironMg: 0.8, potassiumMg: 190, vitaminCmg: 4.5, magnesiumMg: 25, folateMcg: 10,
    allergens: ['gluten'],
    blwNoteKa: 'დატოვეთ ოდნავ მარცვლოვანი ტექსტურა, თუ ბავშვი უკვე კარგად იღებს სქელ ფაფას.',
    blwNoteEn: 'Leave slightly grainy texture if baby already handles thick porridge well.',
    pureeNoteKa: 'ვაშლი და შვრია ერთად დააბლენდერეთ, რომ კანი/ნაჭრები არ დარჩეს.',
    pureeNoteEn: 'Blend apple and oats together so no skin or pieces remain.',
  },
  {
    titleKa: 'გოგრის შვრიის ფაფა',
    titleEn: 'Pumpkin Oat Porridge',
    descriptionKa: 'გოგრა ორთქლზე ან წყალში მოხარშეთ სრულ დარბილებამდე. შვრია მოხარშეთ ცალკე. შეურიეთ გოგრა და შვრია. დააბლენდერეთ სასურველ ტექსტურამდე.',
    descriptionEn: 'Steam or boil pumpkin until fully soft. Cook oats separately. Mix pumpkin and oats. Blend to desired texture.',
    ingredientsKa: ['გოგრა - 70 გ', 'შვრიის ფანტელი - 20 გ', 'წყალი - 120 მლ', 'დედის რძე/ფორმულა - 1 ჩ/კ ბოლოს (სურვილისამებრ)'],
    ingredientsEn: ['Pumpkin - 70g', 'Oat flakes - 20g', 'Water - 120ml', 'Breast milk/formula - 1 tsp at end (optional)'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 98, proteinGrams: 3, fatGrams: 1.4, carbsGrams: 20, fiberGrams: 3.5,
    vitaminAmcg: 375, vitaminCmg: 6.5, ironMg: 0.9, potassiumMg: 235, magnesiumMg: 26,
    allergens: ['gluten'],
    blwNoteKa: 'გააკეთეთ სქელი ფაფა და მიეცით კოვზით; ცალკე გოგრის ძალიან რბილი ზოლებიც შეიძლება.',
    blwNoteEn: 'Make thick porridge and serve by spoon; very soft pumpkin strips can be offered separately.',
    pureeNoteKa: 'გაათხელეთ წყლით ან რძით, თუ ფაფა ძალიან სქელია.',
    pureeNoteEn: 'Thin with water or milk if porridge is too thick.',
  },
  {
    titleKa: 'ავოკადოს შვრიის ფაფა',
    titleEn: 'Avocado Oatmeal',
    descriptionKa: 'შვრია მოხარშეთ კარგად დარბილებამდე. ავოკადო დაჭყლიტეთ გლუვად. შეურიეთ თბილ, ოდნავ გაგრილებულ ფაფას. არ აადუღოთ ავოკადო ფაფაში, რომ გემო არ გამწარდეს.',
    descriptionEn: 'Cook oats until well softened. Mash avocado smoothly. Mix into warm, slightly cooled porridge. Do not boil avocado in porridge to prevent bitter taste.',
    ingredientsKa: ['შვრიის ფანტელი - 18-20 გ', 'მწიფე ავოკადო - 35-40 გ', 'წყალი - 100-120 მლ', 'ლიმონი - რამდენიმე წვეთი (8 თვიდან, სურვილისამებრ)'],
    ingredientsEn: ['Oat flakes - 18-20g', 'Ripe avocado - 35-40g', 'Water - 100-120ml', 'Lemon - few drops (from 8 months, optional)'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 135, proteinGrams: 3, fatGrams: 7.25, carbsGrams: 16, fiberGrams: 5,
    folateMcg: 40, vitaminEmg: 1.5, potassiumMg: 290, ironMg: 1.05, magnesiumMg: 32,
    allergens: ['gluten'],
    blwNoteKa: 'სქელი ფაფა შესთავაზეთ კოვზზე; ავოკადოს რბილი გრძელი ნაჭერი შეიძლება ცალკეც.',
    blwNoteEn: 'Offer thick porridge on spoon; a soft long piece of avocado can be offered separately.',
    pureeNoteKa: 'შვრია და ავოკადო ერთად დააბლენდერეთ კრემისებრ მასად.',
    pureeNoteEn: 'Blend oats and avocado together into a creamy mass.',
  },
  {
    titleKa: 'მსხლისა და ფეტვის ფაფა',
    titleEn: 'Pear Millet Porridge',
    descriptionKa: 'ფეტვი კარგად გარეცხეთ. მოხარშეთ წყალში 15-18 წუთი, სანამ დარბილდება. მსხალი ორთქლზე მოამზადეთ ან ფაფაში ჩახარშეთ. დააბლენდერეთ საჭირო ტექსტურამდე.',
    descriptionEn: 'Rinse millet well. Cook in water for 15-18 minutes until soft. Steam pear or cook in porridge. Blend to desired texture.',
    ingredientsKa: ['ფეტვი - 20 გ', 'მსხალი, გაფცქვნილი - 60 გ', 'წყალი - 140 მლ'],
    ingredientsEn: ['Millet - 20g', 'Pear, peeled - 60g', 'Water - 140ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 118, proteinGrams: 3, fatGrams: 1.2, carbsGrams: 25, fiberGrams: 3.15,
    ironMg: 1.15, magnesiumMg: 28, potassiumMg: 190, vitaminCmg: 4, folateMcg: 13,
    allergens: [],
    blwNoteKa: 'უფრო სქელი მასა დადეთ კოვზზე ან პატარა რბილ გუნდებად.',
    blwNoteEn: 'Put thicker mass on spoon or shape into small soft balls.',
    pureeNoteKa: 'მოხარშვის შემდეგ კარგად დააბლენდერეთ, რადგან ფეტვი მარცვლოვანი რჩება.',
    pureeNoteEn: 'Blend well after cooking as millet tends to remain grainy.',
  },
  {
    titleKa: 'ატმის შვრიის ფაფა',
    titleEn: 'Peach Oat Porridge',
    descriptionKa: 'ატამს მოაშორეთ კანი და კურკა. ატამი ორთქლზე ოდნავ დაარბილეთ, თუ ძალიან რბილი არ არის. შვრია მოხარშეთ 5-7 წუთი. შეურიეთ და დააბლენდერეთ.',
    descriptionEn: 'Remove peach skin and pit. Slightly soften peach by steaming if not very soft. Cook oats for 5-7 minutes. Mix and blend.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'მწიფე ატამი - 60 გ', 'წყალი - 120 მლ'],
    ingredientsEn: ['Oat flakes - 20g', 'Ripe peach - 60g', 'Water - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 110, proteinGrams: 3, fatGrams: 1.4, carbsGrams: 23, fiberGrams: 3.35,
    vitaminCmg: 5.5, potassiumMg: 210, ironMg: 0.8, magnesiumMg: 25, vitaminAmcg: 20,
    allergens: ['gluten'],
    blwNoteKa: 'სქელი ფაფა კოვზზე; ძალიან რბილი ატმის გრძელი ნაჭერი მხოლოდ მაშინ, თუ ბავშვი მზად არის.',
    blwNoteEn: 'Thick porridge on spoon; a long piece of very soft peach only when baby is ready.',
    pureeNoteKa: 'ატამი და შვრია დააბლენდერეთ ერთგვაროვნად.',
    pureeNoteEn: 'Blend peach and oats uniformly.',
  },
  {
    titleKa: 'მანგოს შვრიის ფაფა',
    titleEn: 'Mango Oat Porridge',
    descriptionKa: 'შვრია მოხარშეთ წყალში დარბილებამდე. მანგო გაფცქვენით და დაჭყლიტეთ. შეურიეთ ფაფას და საჭიროების შემთხვევაში დააბლენდერეთ. მიეცით მაშინვე, ახალმომზადებული.',
    descriptionEn: 'Cook oats in water until soft. Peel and mash mango. Mix into porridge and blend if needed. Serve immediately, freshly made.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'მწიფე მანგო - 55-60 გ', 'წყალი - 120 მლ'],
    ingredientsEn: ['Oat flakes - 20g', 'Ripe mango - 55-60g', 'Water - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 118, proteinGrams: 3, fatGrams: 1.4, carbsGrams: 25, fiberGrams: 3.15,
    vitaminCmg: 20.5, vitaminAmcg: 35, potassiumMg: 200, ironMg: 0.8, folateMcg: 22,
    allergens: ['gluten'],
    blwNoteKa: 'სქელი ფაფა კოვზზე; ძალიან სრიალა მანგოს ნაჭერი ფრთხილად შესთავაზეთ.',
    blwNoteEn: 'Thick porridge on spoon; offer slippery mango piece carefully.',
    pureeNoteKa: 'მანგო და ფაფა ერთად დააბლენდერეთ კრემისებრ მასად.',
    pureeNoteEn: 'Blend mango and porridge together into a creamy mass.',
  },
  {
    titleKa: 'ტკბილი კარტოფილისა და შვრიის ფაფა',
    titleEn: 'Sweet Potato Oat Porridge',
    descriptionKa: 'ტკბილი კარტოფილი გაფცქვენით და ორთქლზე მოხარშეთ. შვრია მოხარშეთ წყალში. შეურიეთ და დააბლენდერეთ. საჭიროების შემთხვევაში გაათხელეთ წყლით.',
    descriptionEn: 'Peel sweet potato and steam. Cook oats in water. Mix and blend. Thin with water if needed.',
    ingredientsKa: ['ტკბილი კარტოფილი - 70 გ', 'შვრიის ფანტელი - 20 გ', 'წყალი - 120-140 მლ'],
    ingredientsEn: ['Sweet potato - 70g', 'Oat flakes - 20g', 'Water - 120-140ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 123, proteinGrams: 3, fatGrams: 1.4, carbsGrams: 27, fiberGrams: 4.3,
    vitaminAmcg: 425, potassiumMg: 295, ironMg: 0.9, vitaminCmg: 10, magnesiumMg: 29,
    allergens: ['gluten'],
    blwNoteKa: 'ტკბილი კარტოფილის ძალიან რბილი ზოლი შეიძლება ცალკე; ფაფა კოვზით.',
    blwNoteEn: 'Very soft sweet potato strip can be offered separately; porridge by spoon.',
    pureeNoteKa: 'გააკეთეთ გლუვი, სქელი პიურე.',
    pureeNoteEn: 'Make a smooth, thick puree.',
  },
  {
    titleKa: 'წიწიბურას ფაფა ბანანით',
    titleEn: 'Buckwheat Banana Porridge',
    descriptionKa: 'წიწიბურა კარგად გარეცხეთ. მოხარშეთ სრულ დარბილებამდე. დაუმატეთ დაჭყლეტილი ბანანი. დააბლენდერეთ, თუ ბავშვი ჯერ მარცვლოვან ტექსტურას ვერ იღებს.',
    descriptionEn: 'Rinse buckwheat well. Cook until fully soft. Add mashed banana. Blend if baby cannot yet handle grainy texture.',
    ingredientsKa: ['წიწიბურა (ფანტელი ან მოხარშული) - 20 გ', 'ბანანი - 50 გ', 'წყალი - 130-150 მლ'],
    ingredientsEn: ['Buckwheat (flakes or cooked) - 20g', 'Banana - 50g', 'Water - 130-150ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 118, proteinGrams: 3.4, fatGrams: 1.05, carbsGrams: 26, fiberGrams: 3.5,
    ironMg: 1.3, magnesiumMg: 40, potassiumMg: 250, vitaminB6mg: 0.19, folateMcg: 19,
    allergens: [],
    blwNoteKa: 'გაასქელეთ და შესთავაზეთ კოვზზე ან რბილ პატარა გუნდებად.',
    blwNoteEn: 'Thicken and offer on spoon or as small soft balls.',
    pureeNoteKa: 'დააბლენდერეთ კარგად, რადგან წიწიბურას მარცვლოვანი სტრუქტურა აქვს.',
    pureeNoteEn: 'Blend well as buckwheat has a grainy structure.',
  },
  {
    titleKa: 'მსხლისა და ავოკადოს კრემი',
    titleEn: 'Pear Avocado Cream',
    descriptionKa: 'მსხალი გაფცქვენით და მოაშორეთ გული. ავოკადო და მსხალი დაჭყლიტეთ. დააბლენდერეთ კრემისებრ მასად. მიეცით მომზადებისთანავე.',
    descriptionEn: 'Peel pear and remove core. Mash avocado and pear. Blend into creamy mass. Serve immediately after preparation.',
    ingredientsKa: ['მწიფე ავოკადო - 35 გ', 'მწიფე მსხალი, გაფცქვნილი - 60 გ', 'წყალი ან დედის რძე/ფორმულა - 1-2 ს/კ (სურვილისამებრ)'],
    ingredientsEn: ['Ripe avocado - 35g', 'Ripe pear, peeled - 60g', 'Water or breast milk/formula - 1-2 tbsp (optional)'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 120, proteinGrams: 1.25, fatGrams: 6.25, carbsGrams: 15, fiberGrams: 5,
    folateMcg: 35, vitaminEmg: 1.25, potassiumMg: 290, vitaminCmg: 5, magnesiumMg: 22,
    allergens: [],
    blwNoteKa: 'ავოკადოს გრძელი რბილი ნაჭერი და ძალიან რბილი მსხლის ნაჭერი შეიძლება ცალკე, მუდმივი მეთვალყურეობით.',
    blwNoteEn: 'Long soft avocado piece and very soft pear piece can be offered separately with constant supervision.',
    pureeNoteKa: 'დააბლენდერეთ სრულად, რომ სრიალა და ერთგვაროვანი იყოს.',
    pureeNoteEn: 'Blend completely to make smooth and uniform.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 9-11 MONTHS (FROM_9)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბროკოლის ომლეტი',
    titleEn: 'Broccoli Omelette',
    descriptionKa: 'ბროკოლი ორთქლზე მოხარშეთ და წვრილად დაჭერით. კვერცხი ავურიეთ. ზეითუნის ზეთზე გამოაცხვეთ ომლეტი ბროკოლით. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Steam broccoli and finely chop. Beat egg. Cook omelette with broccoli in olive oil. Prepare with age-appropriate texture.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ბროკოლი - 30-40 გ', 'ზეითუნის ზეთი - 1 ჩ/კ'],
    ingredientsEn: ['Egg - 1', 'Broccoli - 30-40g', 'Olive oil - 1 tsp'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
    blwNoteKa: 'ომლეტი დაჭერით პატარა, ლეკვის ტოლი ნაჭრებად, რომ ბავშვმა ხელით აიღოს.',
    blwNoteEn: 'Cut omelette into small finger-sized pieces for self-feeding.',
    pureeNoteKa: 'ომლეტი ბლენდერით დაამსხვილეთ ან ჩანგლით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash omelette with a fork or blend until fine.',
  },
  {
    titleKa: 'ბანანის ბლინები',
    titleEn: 'Banana Pancakes',
    descriptionKa: 'ბანანი კარგად დაჭყლიტეთ. კვერცხი და შვრიის ფქვილი შეურიეთ ბანანს. პატარა ბლინები გამოაცხვეთ ზეთის გარეშე ან მინიმალური ზეთით. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Mash banana well. Mix egg and oat flour into banana. Cook small pancakes with no or minimal oil. Prepare with age-appropriate texture.',
    ingredientsKa: ['ბანანი - 1 მწიფე', 'კვერცხი - 1 ცალი', 'შვრიის ფქვილი - 2-3 ს/კ'],
    ingredientsEn: ['Banana - 1 ripe', 'Egg - 1', 'Oat flour - 2-3 tbsp'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'პატარა, მრგვალი ბლინები ბავშვისთვის ხელით მისაღებად მოხერხებულია.',
    blwNoteEn: 'Small round pancakes are convenient for self-feeding.',
    pureeNoteKa: 'ბლინი ჩანგლით დაჭყლიტეთ ან ოდნავ გაათბეთ.',
    pureeNoteEn: 'Mash pancake with a fork or warm slightly.',
  },
  {
    titleKa: 'ისპანახის ომლეტი',
    titleEn: 'Spinach Omelette',
    descriptionKa: 'ისპანახი ოდნავ შეაცხვეთ ზეთში, სანამ დარბილდება. კვერცხი ავურიეთ და ისპანახს შეუმატეთ. ომლეტი გამოაცხვეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Lightly sauté spinach in oil until soft. Beat egg and add to spinach. Cook omelette. Prepare with age-appropriate texture.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ისპანახი - 30-40 გ'],
    ingredientsEn: ['Egg - 1', 'Spinach - 30-40g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
    blwNoteKa: 'ომლეტი პატარა ნაჭრებად დაჭერით ხელით კვებისთვის.',
    blwNoteEn: 'Cut omelette into small pieces for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or process in a blender.',
  },
  {
    titleKa: 'მოცვის პანკეიქები',
    titleEn: 'Blueberry Pancakes',
    descriptionKa: 'კვერცხი, შვრიის ფქვილი და მოცვი შეურიეთ. პატარა პანკეიქები გამოაცხვეთ. მიეცით ახალმომზადებული. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Mix egg, oat flour and blueberries. Cook small pancakes. Serve freshly made. Prepare with age-appropriate texture.',
    ingredientsKa: ['მოცვი - 30-40 გ', 'კვერცხი - 1 ცალი', 'შვრიის ფქვილი - 2-3 ს/კ'],
    ingredientsEn: ['Blueberry - 30-40g', 'Egg - 1', 'Oat flour - 2-3 tbsp'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'პანკეიქი პატარა ნაჭრებად — ბავშვი ხელით ადვილად მოიჭერს.',
    blwNoteEn: 'Cut pancake into small pieces — easy for baby to self-feed.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ოდნავ გამდელეთ.',
    pureeNoteEn: 'Mash with fork or soften slightly.',
  },
  {
    titleKa: 'კვერცხი ავოკადოთი',
    titleEn: 'Egg with Avocado',
    descriptionKa: 'კვერცხი გამოაცხვეთ მოჩლუნგებულ სახით ან ამოვარდნილ ყვითლით. ავოკადო დაჭყლიტეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით და მიირთვით ახლად მომზადებული.',
    descriptionEn: 'Cook egg scrambled or with soft yolk. Mash avocado. Prepare with age-appropriate texture and serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ავოკადო - 30-40 გ'],
    ingredientsEn: ['Egg - 1', 'Avocado - 30-40g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
    blwNoteKa: 'ავოკადოს ნაჭრები და კვერცხის ნაჭრები ცალ-ცალკე შესთავაზეთ ხელით კვებისთვის.',
    blwNoteEn: 'Offer avocado pieces and egg pieces separately for self-feeding.',
    pureeNoteKa: 'კვერცხი და ავოკადო ჩანგლით ერთად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash egg and avocado together with a fork.',
  },
  {
    titleKa: 'ხაჭო ბანანით',
    titleEn: 'Cottage Cheese with Banana',
    descriptionKa: 'ბანანი დაჭყლიტეთ ჩანგლით. ხაჭო ბანანს შეურიეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით და მიირთვით ახლად მომზადებული.',
    descriptionEn: 'Mash banana with fork. Mix cottage cheese with banana. Prepare with age-appropriate texture and serve freshly made.',
    ingredientsKa: ['ხაჭო - 60-80 გ', 'ბანანი - 40-50 გ'],
    ingredientsEn: ['Cottage cheese - 60-80g', 'Banana - 40-50g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['dairy'],
    blwNoteKa: 'ხაჭო-ბანანის ნარევი სქელი კოვზზე შესთავაზეთ.',
    blwNoteEn: 'Offer the thick cottage cheese and banana mix on a spoon.',
    pureeNoteKa: 'ბლენდერით დამუშავეთ სრულ გლუვობამდე.',
    pureeNoteEn: 'Process in blender until completely smooth.',
  },
  {
    titleKa: 'შვრიის მაფინები',
    titleEn: 'Oat Muffins',
    descriptionKa: 'შვრიის ფქვილი, კვერცხი და ბანანი შეურიეთ. ფორმებში ჩაასხით. 180°C-ზე გამოაცხვეთ 15-18 წუთი. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Mix oat flour, egg and banana. Pour into muffin forms. Bake at 180°C for 15-18 minutes. Prepare with age-appropriate texture.',
    ingredientsKa: ['შვრიის ფქვილი - 50-60 გ', 'კვერცხი - 1 ცალი', 'ბანანი - 1 მწიფე'],
    ingredientsEn: ['Oat flour - 50-60g', 'Egg - 1', 'Banana - 1 ripe'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'მაფინი ბავშვის ხელში ხვდება — მარტივია ხელით კვებისთვის.',
    blwNoteEn: 'Muffin fits in baby\'s hand — easy for self-feeding.',
    pureeNoteKa: 'მაფინი ჩანგლით დაჭყლიტეთ ან ოდნავ გამდელეთ.',
    pureeNoteEn: 'Mash muffin with fork or soften slightly.',
  },
  {
    titleKa: 'გოგრის ბლინები',
    titleEn: 'Pumpkin Pancakes',
    descriptionKa: 'გოგრა ორთქლზე მოხარშეთ და დაჭყლიტეთ. კვერცხი და შვრიის ფქვილი შეურიეთ. პატარა ბლინები გამოაცხვეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Steam pumpkin and mash. Mix in egg and oat flour. Cook small pancakes. Prepare with age-appropriate texture.',
    ingredientsKa: ['გოგრა - 60-70 გ', 'კვერცხი - 1 ცალი', 'შვრიის ფქვილი - 2-3 ს/კ'],
    ingredientsEn: ['Pumpkin - 60-70g', 'Egg - 1', 'Oat flour - 2-3 tbsp'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'პატარა, ნარინჯისფერი ბლინები ბავშვისთვის ვიზუალურადაც საინტერესოა.',
    blwNoteEn: 'Small orange pancakes are visually interesting for baby too.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დამუშავეთ.',
    pureeNoteEn: 'Mash with fork or process in blender.',
  },
  {
    titleKa: 'იოგურტი ხილით',
    titleEn: 'Yogurt with Fruit',
    descriptionKa: 'მარწყვი ჩანგლით დაჭყლიტეთ ან ბლენდერით დამუშავეთ. ბუნებრივ იოგურტს შეურიეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით და მიირთვით ახლად მომზადებული.',
    descriptionEn: 'Mash strawberries with fork or blend. Mix into natural yogurt. Prepare with age-appropriate texture and serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 60-80 გ', 'მარწყვი - 30-40 გ'],
    ingredientsEn: ['Natural yogurt - 60-80g', 'Strawberry - 30-40g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['dairy', 'strawberry'],
    blwNoteKa: 'იოგურტი კოვზზე შესთავაზეთ; მარწყვის პატარა ნაჭრებიც შეიძლება ცალკე.',
    blwNoteEn: 'Offer yogurt on spoon; small strawberry pieces can be offered separately.',
    pureeNoteKa: 'ბლენდერით გლუვ მასად დამუშავეთ.',
    pureeNoteEn: 'Process in blender until smooth.',
  },
  {
    titleKa: 'ბოსტნეულის კვერცხის მაფინი',
    titleEn: 'Vegetable Egg Muffin',
    descriptionKa: 'სტაფილო და ყაბაყი გაატარეთ სახეხელაზე. კვერცხი ავურიეთ ბოსტნეულთან. ფორმებში ჩაასხით და 180°C-ზე 15 წუთი გამოაცხვეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Grate carrot and zucchini. Beat egg with vegetables. Pour into forms and bake at 180°C for 15 minutes. Prepare with age-appropriate texture.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'სტაფილო - 20-30 გ', 'ყაბაყი - 20-30 გ'],
    ingredientsEn: ['Egg - 1', 'Carrot - 20-30g', 'Zucchini - 20-30g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
    blwNoteKa: 'პატარა მაფინი ბავშვი ხელით იჭერს — ხელით კვებისთვის იდეალურია.',
    blwNoteEn: 'Small muffin baby can grip — ideal for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დამუშავეთ.',
    pureeNoteEn: 'Mash with fork or process in blender.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 12-18 MONTHS (FROM_12)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ფრანგული ტოსტი',
    titleEn: 'French Toast',
    descriptionKa: 'კვერცხი ავურიეთ. მთლიანი მარცვლის პური ჩაასველეთ კვერცხში. ტეფლონის ტაფაზე ორივე მხრიდან გამოაცხვეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Beat egg. Soak whole grain bread in egg. Cook on non-stick pan on both sides. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'მთლიანი მარცვლის პური - 1-2 ნაჭერი'],
    ingredientsEn: ['Egg - 1', 'Whole grain bread - 1-2 slices'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'ჩიას პუდინგი',
    titleEn: 'Chia Pudding',
    descriptionKa: 'ჩიას თესლი რძეში ჩაყარეთ, ავურიეთ და 15-20 წუთი ან ღამე დაისვენეთ. სეზონური ხილი დაუმატეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Add chia seeds to milk, stir and rest for 15-20 minutes or overnight. Add seasonal fruit. Serve freshly made.',
    ingredientsKa: ['ჩიას თესლი - 10 გ', 'რძე - 100 მლ', 'სეზონური ხილი - სურვილისამებრ'],
    ingredientsEn: ['Chia seeds - 10g', 'Milk - 100ml', 'Seasonal fruit - optional'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['dairy'],
  },
  {
    titleKa: 'ავოკადოს ტოსტი კვერცხით',
    titleEn: 'Avocado Toast with Egg',
    descriptionKa: 'პური შეწვით. ავოკადო დაჭყლიტეთ და პურს წაუსვით. კვერცხი მოჩლუნგებულ ან ამოვარდნილ ყვითლით მოხარშეთ. ტოსტზე დადეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Toast bread. Mash avocado and spread on toast. Cook egg scrambled or with soft yolk. Place on toast. Serve freshly made.',
    ingredientsKa: ['ავოკადო - ნახევარი', 'კვერცხი - 1 ცალი', 'ტოსტის პური - 1 ნაჭერი'],
    ingredientsEn: ['Avocado - half', 'Egg - 1', 'Toast bread - 1 slice'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'შვრიის ვაფლები',
    titleEn: 'Oat Waffles',
    descriptionKa: 'შვრიის ფქვილი, კვერცხი და ოდნავ მარილი შეურიეთ. ვაფლის ფორმაში გამოაცხვეთ. მიეცით ახალმომზადებული ხილის კომპლოტთან ან ბუნებრივ იოგურტთან ერთად.',
    descriptionEn: 'Mix oat flour, egg and a pinch of salt. Bake in waffle maker. Serve freshly made with fruit compote or natural yogurt.',
    ingredientsKa: ['შვრიის ფქვილი - 60-70 გ', 'კვერცხი - 1 ცალი', 'წყალი ან რძე - 2-3 ს/კ'],
    ingredientsEn: ['Oat flour - 60-70g', 'Egg - 1', 'Water or milk - 2-3 tbsp'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'ყველისა და ისპანახის ომლეტი',
    titleEn: 'Cheese and Spinach Omelette',
    descriptionKa: 'ისპანახი ოდნავ შეაცხვეთ. კვერცხი ავურიეთ და გამოაცხვეთ. ომლეტზე ყველი დაყარეთ. გააკეცეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Lightly sauté spinach. Beat egg and cook. Add cheese on omelette. Fold. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1-2 ცალი', 'ყველი - 15-20 გ', 'ისპანახი - 20-30 გ'],
    ingredientsEn: ['Egg - 1-2', 'Cheese - 15-20g', 'Spinach - 20-30g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'dairy'],
  },
  {
    titleKa: 'მარწყვის იოგურტ ბოული',
    titleEn: 'Strawberry Yogurt Bowl',
    descriptionKa: 'მარწყვი ჩანგლით ან ბლენდერით დამუშავეთ. ბუნებრივ იოგურტს შეურიეთ. სეზონური ხილი დაუმატეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Process strawberries with fork or blender. Mix into natural yogurt. Add seasonal fruit. Serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 100-120 გ', 'მარწყვი - 40-50 გ'],
    ingredientsEn: ['Natural yogurt - 100-120g', 'Strawberry - 40-50g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['dairy', 'strawberry'],
  },
  {
    titleKa: 'მოცვის მაფინები',
    titleEn: 'Blueberry Muffins',
    descriptionKa: 'შვრიის ფქვილი, ბანანი, კვერცხი და მოცვი შეურიეთ. ფორმებში ჩაასხით. 180°C-ზე 18-20 წუთი გამოაცხვეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Mix oat flour, banana, egg and blueberries. Pour into forms. Bake at 180°C for 18-20 minutes. Serve freshly made.',
    ingredientsKa: ['მოცვი - 40-50 გ', 'შვრიის ფქვილი - 60-70 გ', 'ბანანი - 1 მწიფე'],
    ingredientsEn: ['Blueberry - 40-50g', 'Oat flour - 60-70g', 'Banana - 1 ripe'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['gluten'],
  },
  {
    titleKa: 'ბანანის ენერგეტიკული ბოული',
    titleEn: 'Banana Energy Bowl',
    descriptionKa: 'შვრია მოხარშეთ. ბანანი დაჭყლიტეთ. ბუნებრივი იოგურტი შეუმატეთ. შეურიეთ და მიეცით ახალმომზადებული. სეზონური ხილი ზემოდან დაუმატეთ.',
    descriptionEn: 'Cook oats. Mash banana. Add natural yogurt. Mix and serve freshly made. Top with seasonal fruit.',
    ingredientsKa: ['ბანანი - 1 ცალი', 'ბუნებრივი იოგურტი - 40-50 გ', 'შვრია - 30-40 გ'],
    ingredientsEn: ['Banana - 1', 'Natural yogurt - 40-50g', 'Oats - 30-40g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['dairy', 'gluten'],
  },
  {
    titleKa: 'წიწიბურას პანკეიქები',
    titleEn: 'Buckwheat Pancakes',
    descriptionKa: 'წიწიბურას ფქვილი კვერცხთან შეურიეთ. ოდნავ ზეთთან ერთად გამოაცხვეთ. პატარა, მრგვალი პანკეიქები გაკეთეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Mix buckwheat flour with egg. Cook with minimal oil. Make small round pancakes. Serve freshly made.',
    ingredientsKa: ['წიწიბურას ფქვილი - 60-70 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Buckwheat flour - 60-70g', 'Egg - 1'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
  },
  {
    titleKa: 'რკინით მდიდარი საუზმე',
    titleEn: 'Iron-Rich Breakfast',
    descriptionKa: 'კვერცხი მოჩლუნგებულ ყვითლით მოხარშეთ. ისპანახი ოდნავ შეაცხვეთ. ავოკადო დაჭყლიტეთ. ყველა ერთ თეფშზე დაწყვეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Cook egg with soft yolk. Lightly sauté spinach. Mash avocado. Plate everything together. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ისპანახი - 20-30 გ', 'ავოკადო - ნახევარი'],
    ingredientsEn: ['Egg - 1', 'Spinach - 20-30g', 'Avocado - half'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 18-36 MONTHS (FROM_24)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბოსტნეულის ომლეტი',
    titleEn: 'Vegetable Omelette',
    descriptionKa: 'ბროკოლი და სტაფილო მოხარშეთ და წვრილად დაჭერით. კვერცხი ავურიეთ. ომლეტი გამოაცხვეთ ბოსტნეულით. მიეცით უსაფრთხო ზომის ნაჭრებად.',
    descriptionEn: 'Cook and finely chop broccoli and carrot. Beat egg. Cook omelette with vegetables. Serve in safe-sized pieces.',
    ingredientsKa: ['კვერცხი - 2 ცალი', 'ბროკოლი - 30-40 გ', 'სტაფილო - 20-30 გ'],
    ingredientsEn: ['Egg - 2', 'Broccoli - 30-40g', 'Carrot - 20-30g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['egg'],
  },
  {
    titleKa: 'შვრიის ვაფლები ხილით',
    titleEn: 'Oat Waffles with Fruit',
    descriptionKa: 'შვრიის ფქვილი, კვერცხი და ოდნავ ვანილი შეურიეთ. ვაფლის ფორმაში გამოაცხვეთ. სეზონური ხილი ზემოდან დაუმატეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Mix oat flour, egg and a little vanilla. Bake in waffle maker. Top with seasonal fruit. Serve freshly made.',
    ingredientsKa: ['შვრიის ფქვილი - 70-80 გ', 'სეზონური ხილი - 50-60 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Oat flour - 70-80g', 'Seasonal fruit - 50-60g', 'Egg - 1'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'არაქისის კარაქის ტოსტი',
    titleEn: 'Peanut Butter Toast',
    descriptionKa: 'პური შეწვით. არაქისის კარაქი თხელი ფენით წაუსვით. ბანანის ნაჭრები ზემოდან დაუმატეთ. მიეცით უსაფრთხო ზომის ნაჭრებად.',
    descriptionEn: 'Toast bread. Spread thin layer of peanut butter. Add banana slices on top. Serve in safe-sized pieces.',
    ingredientsKa: ['ტოსტის პური - 1 ნაჭერი', 'არაქისის კარაქი - 1-2 ჩ/კ'],
    ingredientsEn: ['Toast bread - 1 slice', 'Peanut butter - 1-2 tsp'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['gluten', 'peanut'],
  },
  {
    titleKa: 'ხაჭოს ბლინები',
    titleEn: 'Cottage Cheese Pancakes',
    descriptionKa: 'ხაჭო, კვერცხი და ოდნავ ფქვილი შეურიეთ. პატარა ბლინები გამოაცხვეთ. მიეცით ახალმომზადებული ხილის კომპოტთან ან ბუნებრივ იოგურტთან ერთად.',
    descriptionEn: 'Mix cottage cheese, egg and a little flour. Cook small pancakes. Serve freshly made with fruit compote or natural yogurt.',
    ingredientsKa: ['ხაჭო - 80-100 გ', 'კვერცხი - 1 ცალი', 'ფქვილი - 2-3 ს/კ'],
    ingredientsEn: ['Cottage cheese - 80-100g', 'Egg - 1', 'Flour - 2-3 tbsp'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['dairy', 'egg', 'gluten'],
  },
  {
    titleKa: 'კვერცხისა და ყველის სენდვიჩი',
    titleEn: 'Egg and Cheese Sandwich',
    descriptionKa: 'კვერცხი მოჩლუნგებულ სახით მოხარშეთ. ყველი პურზე დადეთ. კვერცხი ზემოდან. პური ჩაჭრათ სამკუთხა ნაჭრებად. მიეცით ახალმომზადებული.',
    descriptionEn: 'Cook egg scrambled. Place cheese on bread. Add egg on top. Cut bread into triangle pieces. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ყველი - 20-30 გ', 'პური - 2 ნაჭერი'],
    ingredientsEn: ['Egg - 1', 'Cheese - 20-30g', 'Bread - 2 slices'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'dairy', 'gluten'],
  },
  {
    titleKa: 'ბანანისა და მოცვის მაფინები',
    titleEn: 'Banana Blueberry Muffins',
    descriptionKa: 'ბანანი დაჭყლიტეთ. შვრიის ფქვილი, კვერცხი, ბანანი და მოცვი შეურიეთ. ფორმებში ჩაასხით. 180°C-ზე 18-20 წუთი გამოაცხვეთ.',
    descriptionEn: 'Mash banana. Mix oat flour, egg, banana and blueberries. Pour into forms. Bake at 180°C for 18-20 minutes.',
    ingredientsKa: ['ბანანი - 1 მწიფე', 'მოცვი - 50-60 გ', 'შვრიის ფქვილი - 60-70 გ'],
    ingredientsEn: ['Banana - 1 ripe', 'Blueberry - 50-60g', 'Oat flour - 60-70g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['gluten'],
  },
  {
    titleKa: 'იოგურტის გრანოლა ბოული',
    titleEn: 'Yogurt Granola Bowl',
    descriptionKa: 'ბუნებრივი იოგურტი თასში ჩაასხით. გრანოლა ზემოდან დაუმატეთ. სეზონური ხილი ზემოდან. მიეცით ახალმომზადებული.',
    descriptionEn: 'Pour natural yogurt into bowl. Add granola on top. Top with seasonal fruit. Serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 100-120 გ', 'გრანოლა - 20-30 გ', 'სეზონური ხილი - 40-50 გ'],
    ingredientsEn: ['Natural yogurt - 100-120g', 'Granola - 20-30g', 'Seasonal fruit - 40-50g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['dairy', 'gluten'],
  },
  {
    titleKa: 'საბავშვო შაქშუქა',
    titleEn: 'Baby Shakshuka',
    descriptionKa: 'ბულგარული და პომიდვრი წვრილად დაჭერით. ზეთში შეაცხვეთ 5 წუთი. კვერცხი ჩასხით ზემოდან. დააფარეთ სახურავი და 3-4 წუთი მოხარშეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Finely chop bell pepper and tomato. Sauté in oil for 5 minutes. Add egg on top. Cover and cook for 3-4 minutes. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'პომიდვრი - 40-50 გ', 'ბულგარული წიწაკა - 30-40 გ'],
    ingredientsEn: ['Egg - 1', 'Tomato - 40-50g', 'Bell pepper - 30-40g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'tomato'],
  },
  {
    titleKa: 'ისპანახისა და ყველის პანკეიქები',
    titleEn: 'Spinach and Cheese Pancakes',
    descriptionKa: 'ისპანახი ბლენდერით ან წვრილად დაჭერით. კვერცხი, ყველი და ისპანახი შეურიეთ. ბლინები გამოაცხვეთ. მიეცით ახალმომზადებული.',
    descriptionEn: 'Blend or finely chop spinach. Mix egg, cheese and spinach. Cook pancakes. Serve freshly made.',
    ingredientsKa: ['ისპანახი - 30-40 გ', 'ყველი - 20-30 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Spinach - 30-40g', 'Cheese - 20-30g', 'Egg - 1'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['dairy', 'egg'],
  },
  {
    titleKa: 'ენერგეტიკული საუზმის თეფში',
    titleEn: 'Energy Breakfast Plate',
    descriptionKa: 'კვერცხი მოჩლუნგებულ სახით მოხარშეთ. ავოკადო ნაჭრებად დაჭერით. სეზონური ხილი დაამატეთ. ტოსტი ნაჭრებად დაჭერით. ყველა ერთ თეფშზე მოაწყვეთ.',
    descriptionEn: 'Cook egg scrambled. Cut avocado into pieces. Add seasonal fruit. Cut toast into pieces. Arrange everything on one plate.',
    ingredientsKa: ['კვერცხი - 1-2 ცალი', 'ავოკადო - ნახევარი', 'სეზონური ხილი - 40-50 გ', 'ტოსტი - 1 ნაჭერი'],
    ingredientsEn: ['Egg - 1-2', 'Avocado - half', 'Seasonal fruit - 40-50g', 'Toast - 1 slice'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    allergens: ['egg', 'gluten'],
  },
];

async function main() {
  console.log('🌱 Seeding 40 breakfast recipes...');

  let created = 0;
  let skipped = 0;

  for (const r of recipes) {
    const existing = await prisma.dish.findFirst({
      where: { titleKa: r.titleKa, mealType: 'BREAKFAST' },
    });

    if (existing) {
      skipped++;
      console.log(`  ⏭  Already exists: ${r.titleKa}`);
      continue;
    }

    await prisma.dish.create({
      data: {
        titleKa: r.titleKa,
        titleEn: r.titleEn,
        descriptionKa: r.descriptionKa,
        descriptionEn: r.descriptionEn,
        ingredientsKa: r.ingredientsKa,
        ingredientsEn: r.ingredientsEn,
        ageGroups: r.ageGroups as any,
        mealType: r.mealType as any,
        allergens: r.allergens || [],
        calories: (r as any).calories ?? null,
        proteinGrams: (r as any).proteinGrams ?? null,
        fatGrams: (r as any).fatGrams ?? null,
        carbsGrams: (r as any).carbsGrams ?? null,
        fiberGrams: (r as any).fiberGrams ?? null,
        ironMg: (r as any).ironMg ?? null,
        calciumMg: (r as any).calciumMg ?? null,
        vitaminCmg: (r as any).vitaminCmg ?? null,
        vitaminAmcg: (r as any).vitaminAmcg ?? null,
        vitaminEmg: (r as any).vitaminEmg ?? null,
        vitaminB6mg: (r as any).vitaminB6mg ?? null,
        folateMcg: (r as any).folateMcg ?? null,
        potassiumMg: (r as any).potassiumMg ?? null,
        magnesiumMg: (r as any).magnesiumMg ?? null,
        blwNoteKa: (r as any).blwNoteKa ?? null,
        blwNoteEn: (r as any).blwNoteEn ?? null,
        pureeNoteKa: (r as any).pureeNoteKa ?? null,
        pureeNoteEn: (r as any).pureeNoteEn ?? null,
      },
    });
    created++;
    console.log(`  ✓  ${r.titleKa}`);
  }

  console.log(`\n✅ Done: ${created} created, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
