import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Recipes below are original Georgian writing, built around common, widely-known
// infant/toddler feeding combinations (single-vegetable purees, simple protein-and-
// vegetable combinations for FROM_6/FROM_9; family dinners like salmon, pilaf, lasagna,
// and bean stews for FROM_12/FROM_24). Nutrient values are computed from a reusable
// per-100g reference table built from USDA FoodData Central figures (public domain / CC0).
const recipes = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 6-8 MONTHS (FROM_6) — DINNER
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბროკოლის პიურე',
    titleEn: 'Broccoli Puree',
    descriptionKa: 'ბროკოლი ყვავილებად გაყავით. ორთქლზე ან წყალში 8-10 წუთი მოხარშეთ სრულ დარბილებამდე. ბლენდერით გახეხეთ. საჭიროების შემთხვევაში ოდნავ მოხარშული წყალი დაუმატეთ სასურველი კონსისტენციისთვის.',
    descriptionEn: 'Divide broccoli into florets. Steam or boil for 8-10 minutes until fully soft. Blend until smooth. Add a little cooking water if needed for desired consistency.',
    ingredientsKa: ['ბროკოლი - 90 გ', 'წყალი - საჭიროებისამებრ'],
    ingredientsEn: ['Broccoli - 90g', 'Water - as needed'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 32, proteinGrams: 2, fatGrams: 0.4, carbsGrams: 6.5, fiberGrams: 3,
    ironMg: 0.66, calciumMg: 36, vitaminCmg: 58.4, vitaminAmcg: 28, vitaminKmcg: 127, folateMcg: 97, potassiumMg: 264,
    blwNoteKa: 'რბილი ყვავილები ღეროთი შესთავაზეთ, რომ ბავშვმა ხელით მარტივად აიღოს.',
    blwNoteEn: 'Offer soft florets with a bit of stalk so baby can grip them easily.',
    pureeNoteKa: 'ბლენდერით სრულად გლუვ მასად გახეხეთ.',
    pureeNoteEn: 'Blend into a completely smooth mass.',
  },
  {
    titleKa: 'ყვავილოვანი კომბოსტოს პიურე',
    titleEn: 'Cauliflower Puree',
    descriptionKa: 'ყვავილოვანი კომბოსტო ყვავილებად გაყავით. ორთქლზე 10-12 წუთი მოხარშეთ სრულ დარბილებამდე. ბლენდერით ძალიან გლუვ პიურედ გახეხეთ. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Divide cauliflower into florets. Steam for 10-12 minutes until fully soft. Blend into a very smooth puree. Serve slightly cooled.',
    ingredientsKa: ['ყვავილოვანი კომბოსტო - 90 გ'],
    ingredientsEn: ['Cauliflower - 90g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 21, proteinGrams: 2, fatGrams: 0.4, carbsGrams: 3.7, fiberGrams: 2.1,
    vitaminCmg: 39.9, vitaminKmcg: 14, folateMcg: 40, potassiumMg: 128,
    blwNoteKa: 'რბილი ყვავილები ცალ-ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer soft florets separately.',
    pureeNoteKa: 'ბლენდერით ძალიან გლუვ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a very smooth puree.',
  },
  {
    titleKa: 'ავოკადოს პიურე',
    titleEn: 'Avocado Puree',
    descriptionKa: 'მწიფე ავოკადო გაფცქვენით, კურკა ამოიღეთ. ჩანგლით ძალიან გლუვად დაჭყლიტეთ. ახლადმომზადებული მიეცით — ავოკადო სწრაფად ჟანგდება. გათბობა საჭირო არ არის.',
    descriptionEn: 'Peel ripe avocado, remove pit. Mash very smoothly with fork. Serve freshly made — avocado darkens quickly. No heating needed.',
    ingredientsKa: ['ავოკადო - 40 გ'],
    ingredientsEn: ['Avocado - 40g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 64, proteinGrams: 1, fatGrams: 5.9, carbsGrams: 3.4, fiberGrams: 2.7,
    vitaminCmg: 4, vitaminEmg: 0.83, vitaminKmcg: 8.4, vitaminB6mg: 0.1, folateMcg: 32, potassiumMg: 194, magnesiumMg: 12,
    blwNoteKa: 'ავოკადოს გრძელი, რბილი ნაჭერი (კანთან ერთად სამარჯვედ) ბავშვისთვის ხელით საკვებად კარგია.',
    blwNoteEn: 'A long, soft avocado piece (with skin left as a handle) is great for baby to self-feed.',
    pureeNoteKa: 'ჩანგლით ძალიან გლუვად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash very smoothly with a fork.',
  },
  {
    titleKa: 'კარტოფილი და ყაბაყი',
    titleEn: 'Potato and Zucchini',
    descriptionKa: 'კარტოფილი და ყაბაყი გაფცქვენით, კუბიკებად დაჭერით. ორთქლზე ან წყალში 12-15 წუთი მოხარშეთ. ბლენდერით გლუვ პიურედ გახეხეთ. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel potato and zucchini, cut into cubes. Steam or boil for 12-15 minutes. Blend into a smooth puree. Serve slightly cooled.',
    ingredientsKa: ['კარტოფილი - 50 გ', 'ყაბაყი - 50 გ'],
    ingredientsEn: ['Potato - 50g', 'Zucchini - 50g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 52, proteinGrams: 2, fatGrams: 0.2, carbsGrams: 11.6, fiberGrams: 1.4,
    vitaminCmg: 8.8, vitaminAmcg: 5, vitaminB6mg: 0.14, folateMcg: 11, potassiumMg: 320, magnesiumMg: 11,
    blwNoteKa: 'ორივე ბოსტნეული რბილ ჩხირებად დაჭერით და ცალ-ცალკე შესთავაზეთ.',
    blwNoteEn: 'Cut both vegetables into soft sticks and offer separately.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'სტაფილო და გოგრა',
    titleEn: 'Carrot and Pumpkin',
    descriptionKa: 'სტაფილო და გოგრა გაფცქვენით, კუბიკებად დაჭერით. ორთქლზე 15 წუთი მოხარშეთ სრულ დარბილებამდე. ბლენდერით გლუვ ნარინჯისფერ პიურედ გახეხეთ. ბეტა-კაროტინით მდიდარია.',
    descriptionEn: 'Peel carrot and pumpkin, cut into cubes. Steam for 15 minutes until fully soft. Blend into a smooth orange puree. Rich in beta-carotene.',
    ingredientsKa: ['სტაფილო - 50 გ', 'გოგრა - 50 გ'],
    ingredientsEn: ['Carrot - 50g', 'Pumpkin - 50g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 28, proteinGrams: 1, fatGrams: 0.1, carbsGrams: 6.6, fiberGrams: 2.1,
    vitaminCmg: 3.9, vitaminAmcg: 705, vitaminKmcg: 4.3, potassiumMg: 233,
    blwNoteKa: 'ორთქლზე დარბილებული ჩხირები ორ თითს შორის ადვილად უნდა იჭყლიტებოდეს.',
    blwNoteEn: 'Steam-softened sticks should squash easily between two fingers.',
    pureeNoteKa: 'ბლენდერით გლუვ ნარინჯისფერ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a smooth orange puree.',
  },
  {
    titleKa: 'მსხლის პიურე',
    titleEn: 'Pear Puree',
    descriptionKa: 'მსხალი გაფცქვენით, გული ამოიღეთ, კუბიკებად დაჭერით. ორთქლზე 5-7 წუთი მოხარშეთ. ბლენდერით გლუვ ფაფად გახეხეთ. ახლადმომზადებული ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel pear, remove core, cut into cubes. Steam for 5-7 minutes. Blend into a smooth puree. Serve freshly made, slightly cooled.',
    ingredientsKa: ['მსხალი - 1 საშუალო (120 გ)'],
    ingredientsEn: ['Pear - 1 medium (120g)'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 68, proteinGrams: 0, fatGrams: 0.2, carbsGrams: 18.2, fiberGrams: 3.7,
    vitaminCmg: 5.2, folateMcg: 8, potassiumMg: 139,
    blwNoteKa: 'ორთქლზე დარბილებული ჩხირები საკმარისად რბილი უნდა იყოს ორ თითს შორის დასაჭყლეტად.',
    blwNoteEn: 'Steam-softened sticks should be soft enough to squash between two fingers.',
    pureeNoteKa: 'ბლენდერით გლუვ ფაფად გახეხეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'ვაშლის პიურე',
    titleEn: 'Apple Puree',
    descriptionKa: 'ვაშლი გაფცქვენით, გული ამოიღეთ, კუბიკებად დაჭერით. ორთქლზე 8-10 წუთი მოხარშეთ. ბლენდერით გლუვ ფაფად გახეხეთ. ახლადმომზადებული ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel apple, remove core, cut into cubes. Steam for 8-10 minutes. Blend into a smooth puree. Serve freshly made, slightly cooled.',
    ingredientsKa: ['ვაშლი - 1 საშუალო (120 გ)'],
    ingredientsEn: ['Apple - 1 medium (120g)'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 62, proteinGrams: 0, fatGrams: 0.2, carbsGrams: 16.6, fiberGrams: 2.9,
    vitaminCmg: 5.5, folateMcg: 4, potassiumMg: 128,
    blwNoteKa: 'ნედლი ვაშლი მაგარია და საშიშია — ყოველთვის ორთქლზე კარგად დაარბილეთ.',
    blwNoteEn: 'Raw apple is hard and unsafe — always steam it soft first.',
    pureeNoteKa: 'ბლენდერით გლუვ ფაფად გახეხეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'ტკბილი კარტოფილის პიურე',
    titleEn: 'Sweet Potato Puree',
    descriptionKa: 'ტკბილი კარტოფილი გაფცქვენით, კუბიკებად დაჭერით. ორთქლზე 12-15 წუთი მოხარშეთ სრულ დარბილებამდე. ბლენდერით ძალიან გლუვ ნარინჯისფერ პიურედ გახეხეთ.',
    descriptionEn: 'Peel sweet potato, cut into cubes. Steam for 12-15 minutes until fully soft. Blend into a very smooth orange puree.',
    ingredientsKa: ['ტკბილი კარტოფილი - 100 გ'],
    ingredientsEn: ['Sweet potato - 100g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 90, proteinGrams: 2, fatGrams: 0.2, carbsGrams: 20.7, fiberGrams: 3.3,
    ironMg: 0.69, calciumMg: 38, vitaminCmg: 19.6, vitaminAmcg: 961, vitaminB6mg: 0.29,
    potassiumMg: 475, magnesiumMg: 27,
    blwNoteKa: 'შესთავაზეთ სქელი ჩხირის სახით, საჩვენებელი თითივით — ბავშვს ხელით მოსახელთებელი.',
    blwNoteEn: 'Offer as a thick stick, about the width of an adult finger — easy for baby to grip.',
    pureeNoteKa: 'ბლენდერით ძალიან გლუვ ნარინჯისფერ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a very smooth orange puree.',
  },
  {
    titleKa: 'ბანანი და ავოკადო',
    titleEn: 'Banana and Avocado',
    descriptionKa: 'ბანანი და ავოკადო ჩანგლით ძალიან გლუვად ერთად დაჭყლიტეთ. ახლადმომზადებული მიეცით. კალიუმისა და ჯანსაღი ცხიმების შესანიშნავი კომბინაციაა.',
    descriptionEn: 'Mash banana and avocado together very smoothly with fork. Serve freshly made. An excellent combination of potassium and healthy fats.',
    ingredientsKa: ['ბანანი - 55 გ', 'ავოკადო - 30 გ'],
    ingredientsEn: ['Banana - 55g', 'Avocado - 30g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 97, proteinGrams: 1, fatGrams: 4.6, carbsGrams: 15.1, fiberGrams: 3.4,
    ironMg: 0.14, vitaminCmg: 7.8, vitaminEmg: 0.62, vitaminKmcg: 6.3, vitaminB6mg: 0.3,
    folateMcg: 35, potassiumMg: 342, magnesiumMg: 24,
    blwNoteKa: 'ორივე ცალ-ცალკე გრძელ ნაჭრებადაც შეიძლება შესთავაზოთ.',
    blwNoteEn: 'Both can also be offered separately as long soft pieces.',
    pureeNoteKa: 'ჩანგლით ძალიან გლუვად ერთად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash together very smoothly with a fork.',
  },
  {
    titleKa: 'ბოსტნეულის პიურე',
    titleEn: 'Vegetable Puree',
    descriptionKa: 'სტაფილო, ყაბაყი და კარტოფილი გაფცქვენით, კუბიკებად დაჭერით. ერთად ორთქლზე 15 წუთი მოხარშეთ. ბლენდერით გლუვ პიურედ გახეხეთ. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel carrot, zucchini and potato, cut into cubes. Steam together for 15 minutes. Blend into a smooth puree. Serve slightly cooled.',
    ingredientsKa: ['სტაფილო - 40 გ', 'ყაბაყი - 40 გ', 'კარტოფილი - 40 გ'],
    ingredientsEn: ['Carrot - 40g', 'Zucchini - 40g', 'Potato - 40g'],
    ageGroups: ['FROM_6'], mealType: 'DINNER', allergens: [],
    calories: 56, proteinGrams: 2, fatGrams: 0.2, carbsGrams: 12.6, fiberGrams: 2.3,
    vitaminCmg: 8.2, vitaminAmcg: 345, vitaminKmcg: 3.4, vitaminB6mg: 0.11, folateMcg: 8,
    potassiumMg: 350, magnesiumMg: 9,
    blwNoteKa: 'სამივე ბოსტნეული რბილ ჩხირებად ცალ-ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer all three vegetables as soft sticks separately.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 9-11 MONTHS (FROM_9) — DINNER
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბოსტნეულის ომლეტი',
    titleEn: 'Vegetable Omelette',
    descriptionKa: 'ბროკოლი და სტაფილო ორთქლზე ოდნავ მოხარშეთ. კვერცხი ავურიეთ, ბოსტნეული შეუმატეთ. ზეთის მინიმალური რაოდენობით გამოაცხვეთ. ასაკისთვის უსაფრთხო ზომის ნაჭრებად მიეცით.',
    descriptionEn: 'Lightly steam broccoli and carrot. Beat egg and add vegetables. Cook with minimal oil. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ბროკოლი - 30 გ', 'სტაფილო - 30 გ'],
    ingredientsEn: ['Egg - 1', 'Broccoli - 30g', 'Carrot - 30g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: ['egg'],
    calories: 99, proteinGrams: 7, fatGrams: 5.7, carbsGrams: 5.2, fiberGrams: 1.9,
    ironMg: 1.09, calciumMg: 40, vitaminCmg: 20.4, vitaminAmcg: 345, vitaminDmcg: 1,
    vitaminKmcg: 44.9, vitaminB12mcg: 0.65, folateMcg: 56, zincMg: 0.65, potassiumMg: 158, phosphorusMg: 99,
    blwNoteKa: 'ომლეტი პატარა ნაჭრებად დაჭერით ხელით კვებისთვის.',
    blwNoteEn: 'Cut omelette into small pieces for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or process in a blender.',
  },
  {
    titleKa: 'ავოკადო და კვერცხი',
    titleEn: 'Avocado and Egg',
    descriptionKa: 'კვერცხი მოჩლუნგებულ ან რბილი ყვითლით მოხარშეთ. ავოკადო ჩანგლით ოდნავ დაჭყლიტეთ. ორივე ცალ-ცალკე მიეცით. ასაკისთვის უსაფრთხო ზომის ნაჭრებად.',
    descriptionEn: 'Cook egg scrambled or with soft yolk. Lightly mash avocado with fork. Serve both separately in age-appropriate sized pieces.',
    ingredientsKa: ['ავოკადო - 30 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Avocado - 30g', 'Egg - 1'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: ['egg'],
    calories: 126, proteinGrams: 7, fatGrams: 9.9, carbsGrams: 3.1, fiberGrams: 2,
    ironMg: 0.88, calciumMg: 28, vitaminCmg: 3, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminEmg: 0.62, vitaminKmcg: 6.3, vitaminB6mg: 0.08, vitaminB12mcg: 0.65,
    folateMcg: 48, zincMg: 0.65, potassiumMg: 146, magnesiumMg: 9, phosphorusMg: 99,
    blwNoteKa: 'ავოკადოს გრძელი ნაჭერი და კვერცხის ნაჭრები ცალ-ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer a long avocado piece and egg pieces separately.',
    pureeNoteKa: 'ორივე ერთად ჩანგლით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash both together with a fork.',
  },
  {
    titleKa: 'ქათამი და ყაბაყი',
    titleEn: 'Chicken and Zucchini',
    descriptionKa: 'ქათმის ფილე ორთქლზე ან ბულიონში მოხარშეთ. ყაბაყი ასევე ორთქლზე დაარბილეთ. ქათამი ბოჭკოებად დაჭყლიტეთ, ყაბაყი კუბიკებად დაჭერით. ასაკისთვის უსაფრთხო ზომის ნაჭრებად მიეცით.',
    descriptionEn: 'Steam or boil chicken fillet in broth. Also soften zucchini by steaming. Shred chicken into fibers, cut zucchini into cubes. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ქათამი - 70 გ', 'ყაბაყი - 60 გ'],
    ingredientsEn: ['Chicken - 70g', 'Zucchini - 60g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 126, proteinGrams: 22, fatGrams: 2.7, carbsGrams: 1.9, fiberGrams: 0.6,
    ironMg: 0.63, vitaminCmg: 2.8, vitaminAmcg: 6, vitaminB6mg: 0.42, vitaminB12mcg: 0.21,
    folateMcg: 13, zincMg: 0.7, potassiumMg: 336, phosphorusMg: 154,
    blwNoteKa: 'ქათამი ბოჭკოებად, ყაბაყი რბილ კუბიკებად — ორივე ცალკე ხელით.',
    blwNoteEn: 'Chicken in fibers, zucchini in soft cubes — both by hand separately.',
    pureeNoteKa: 'ერთად ჩანგლით ან ბლენდერით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash or blend together.',
  },
  {
    titleKa: 'ოსპის პიურე',
    titleEn: 'Lentil Puree',
    descriptionKa: 'წითელი ოსპი კარგად გარეცხეთ. სტაფილოსთან ერთად ორჯერ ადუღეთ. 20-25 წუთი მოხარშეთ სრულ დარბილებამდე. ბლენდერით გლუვ პიურედ გახეხეთ.',
    descriptionEn: 'Rinse red lentils well. Bring to boil twice with carrot. Cook for 20-25 minutes until fully soft. Blend into a smooth puree.',
    ingredientsKa: ['წითელი ოსპი, მოხარშული - 130 გ', 'სტაფილო - 40 გ'],
    ingredientsEn: ['Red lentils, cooked - 130g', 'Carrot - 40g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 165, proteinGrams: 12, fatGrams: 0.6, carbsGrams: 29.4, fiberGrams: 11.5,
    ironMg: 4.29, vitaminCmg: 1.2, vitaminAmcg: 341, vitaminKmcg: 3.4, folateMcg: 235,
    zincMg: 1.69, potassiumMg: 574, magnesiumMg: 47, phosphorusMg: 234,
    blwNoteKa: 'შესთავაზეთ სქელი მასა კოვზზე — ცალკეული ოსპის მარცვლები ხელისთვის რთულია.',
    blwNoteEn: 'Offer the thick mixture on a spoon — loose lentils are tricky for little hands.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'კარტოფილი და ბროკოლი',
    titleEn: 'Potato and Broccoli',
    descriptionKa: 'კარტოფილი გაფცქვენით, კუბიკებად დაჭერით. ბროკოლი ყვავილებად გაყავით. ერთად ორთქლზე 12-15 წუთი მოხარშეთ. ბლენდერით ან ჩანგლით ოდნავ გახეხეთ. ასაკისთვის უსაფრთხო ტექსტურით მიეცით.',
    descriptionEn: 'Peel potato, cut into cubes. Divide broccoli into florets. Steam together for 12-15 minutes. Blend or mash slightly with fork. Serve with age-appropriate texture.',
    ingredientsKa: ['კარტოფილი - 60 გ', 'ბროკოლი - 60 გ'],
    ingredientsEn: ['Potato - 60g', 'Broccoli - 60g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 73, proteinGrams: 3, fatGrams: 0.3, carbsGrams: 16.4, fiberGrams: 3.1,
    ironMg: 0.44, calciumMg: 24, vitaminCmg: 46.7, vitaminAmcg: 19, vitaminKmcg: 84.7,
    vitaminB6mg: 0.16, folateMcg: 65, potassiumMg: 403, magnesiumMg: 13,
    blwNoteKa: 'ბროკოლის რბილი ყვავილები და კარტოფილის ჩხირები ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer soft broccoli florets and potato sticks separately.',
    pureeNoteKa: 'ბლენდერით ან ჩანგლით გლუვად გახეხეთ.',
    pureeNoteEn: 'Blend or mash smoothly with a fork.',
  },
  {
    titleKa: 'ინდაური და გოგრა',
    titleEn: 'Turkey and Pumpkin',
    descriptionKa: 'ინდაურის ფილე ორთქლზე ან ბულიონში მოხარშეთ. გოგრა კუბიკებად დაჭერით, ორთქლზე 15 წუთი დაარბილეთ. ინდაური ბოჭკოებად დაჭყლიტეთ. ასაკისთვის უსაფრთხო ზომის ნაჭრებად მიეცით.',
    descriptionEn: 'Steam or boil turkey fillet in broth. Cut pumpkin into cubes and soften by steaming for 15 minutes. Shred turkey into fibers. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ინდაური - 70 გ', 'გოგრა - 60 გ'],
    ingredientsEn: ['Turkey - 70g', 'Pumpkin - 60g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 107, proteinGrams: 21, fatGrams: 0.6, carbsGrams: 2.9, fiberGrams: 0.7,
    ironMg: 0.98, vitaminCmg: 2.8, vitaminAmcg: 335, vitaminB6mg: 0.35, vitaminB12mcg: 0.21,
    zincMg: 1.05, potassiumMg: 305, phosphorusMg: 150,
    blwNoteKa: 'ინდაური ბოჭკოებად, გოგრა რბილ კუბიკებად — ცალკე შესთავაზეთ.',
    blwNoteEn: 'Turkey in fibers, pumpkin in soft cubes — offer separately.',
    pureeNoteKa: 'ერთად ჩანგლით ან ბლენდერით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash or blend together.',
  },
  {
    titleKa: 'ბრინჯი ბოსტნეულით',
    titleEn: 'Rice with Vegetables',
    descriptionKa: 'ბრინჯი კარგად მოხარშეთ, სანამ ძალიან რბილი გახდება. სტაფილო და ყაბაყი ბრინჯთან ერთად ან ცალ-ცალკე ორთქლზე მოხარშეთ. ერთად ოდნავ გახეხეთ. ასაკისთვის უსაფრთხო ტექსტურით მიეცით.',
    descriptionEn: 'Cook rice until very soft. Steam carrot and zucchini with rice or separately. Mash together slightly. Serve with age-appropriate texture.',
    ingredientsKa: ['ბრინჯი, მოხარშული - 120 გ', 'სტაფილო - 30 გ', 'ყაბაყი - 30 გ'],
    ingredientsEn: ['Rice, cooked - 120g', 'Carrot - 30g', 'Zucchini - 30g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 172, proteinGrams: 3, fatGrams: 0.5, carbsGrams: 37.2, fiberGrams: 1.7,
    ironMg: 0.24, vitaminCmg: 2.3, vitaminAmcg: 259, vitaminKmcg: 2.6, folateMcg: 6,
    potassiumMg: 149, magnesiumMg: 14, phosphorusMg: 52,
    blwNoteKa: 'შესთავაზეთ სქელი, წებოვანი კონსისტენციით, რომ ხელისთვისაც მოსახერხებელი იყოს.',
    blwNoteEn: 'Serve with a thick, sticky consistency so it is easy to grip too.',
    pureeNoteKa: 'ბლენდერით საჭირო ტექსტურამდე დაამუშავეთ.',
    pureeNoteEn: 'Blend to desired texture.',
  },
  {
    titleKa: 'ყვავილოვანი კომბოსტო და ქათამი',
    titleEn: 'Cauliflower and Chicken',
    descriptionKa: 'ქათმის ფილე ბულიონში ან ორთქლზე მოხარშეთ. ყვავილოვანი კომბოსტო ყვავილებად გაყავით, ორთქლზე 10 წუთი დაარბილეთ. ქათამი ბოჭკოებად დაჭყლიტეთ, ბოსტნეული კუბიკებად. ერთად მიეცით.',
    descriptionEn: 'Cook chicken fillet in broth or steam. Divide cauliflower into florets, soften by steaming for 10 minutes. Shred chicken into fibers, cut vegetables into cubes. Serve together.',
    ingredientsKa: ['ყვავილოვანი კომბოსტო - 70 გ', 'ქათამი - 65 გ'],
    ingredientsEn: ['Cauliflower - 70g', 'Chicken - 65g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 123, proteinGrams: 21, fatGrams: 2.7, carbsGrams: 2.9, fiberGrams: 1.6,
    ironMg: 0.59, vitaminCmg: 31, vitaminKmcg: 10.9, vitaminB6mg: 0.39, vitaminB12mcg: 0.2,
    folateMcg: 31, zincMg: 0.65, potassiumMg: 266, phosphorusMg: 143,
    blwNoteKa: 'ქათამი ბოჭკოებად, ყვავილოვანი კომბოსტოს რბილი ყვავილები ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer chicken in fibers and soft cauliflower florets separately.',
    pureeNoteKa: 'ერთად ჩანგლით ან ბლენდერით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash or blend together.',
  },
  {
    titleKa: 'ტკბილი კარტოფილი და ოსპი',
    titleEn: 'Sweet Potato and Lentils',
    descriptionKa: 'ოსპი გარეცხეთ, 20 წუთი მოხარშეთ. ტკბილი კარტოფილი გაფცქვენით, კუბიკებად დაჭერით, ორთქლზე 12 წუთი მოხარშეთ. ერთად ოდნავ გახეხეთ. ასაკისთვის უსაფრთხო ტექსტურით მიეცით.',
    descriptionEn: 'Rinse lentils and cook for 20 minutes. Peel sweet potato, cut into cubes, steam for 12 minutes. Mash together slightly. Serve with age-appropriate texture.',
    ingredientsKa: ['ტკბილი კარტოფილი - 70 გ', 'ოსპი, მოხარშული - 100 გ'],
    ingredientsEn: ['Sweet potato - 70g', 'Lentils, cooked - 100g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: [],
    calories: 179, proteinGrams: 10, fatGrams: 0.5, carbsGrams: 34.6, fiberGrams: 10.2,
    ironMg: 3.78, calciumMg: 27, vitaminCmg: 13.7, vitaminAmcg: 673, vitaminB6mg: 0.2,
    folateMcg: 181, zincMg: 1.3, potassiumMg: 702, magnesiumMg: 55, phosphorusMg: 180,
    blwNoteKa: 'ტკბილი კარტოფილის ჩხირები ცალკე, ოსპი სქელ მასად კოვზზე.',
    blwNoteEn: 'Sweet potato sticks separately, lentils as a thick mixture on a spoon.',
    pureeNoteKa: 'ერთად ბლენდერით გლუვ პიურედ გახეხეთ.',
    pureeNoteEn: 'Blend together into a smooth puree.',
  },
  {
    titleKa: 'ბოსტნეულის გუფთა',
    titleEn: 'Vegetable Meatballs',
    descriptionKa: 'ბოსტნეული (სტაფილო, ყაბაყი) წვრილად დაჭერით. კვერცხი ავურიეთ, ბოსტნეული შეუმატეთ. პატარა გუფთები ჩამოაყალიბეთ. ღუმელში 180°C-ზე 18-20 წუთი გამოაცხვეთ.',
    descriptionEn: 'Finely chop vegetables (carrot, zucchini). Beat egg and add vegetables. Shape small balls. Bake in oven at 180°C for 18-20 minutes.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'სტაფილო - 50 გ', 'ყაბაყი - 50 გ'],
    ingredientsEn: ['Egg - 1', 'Carrot - 50g', 'Zucchini - 50g'],
    ageGroups: ['FROM_9'], mealType: 'DINNER', allergens: ['egg'],
    calories: 104, proteinGrams: 7, fatGrams: 5.7, carbsGrams: 6.2, fiberGrams: 2,
    ironMg: 0.88, calciumMg: 28, vitaminCmg: 3.8, vitaminAmcg: 511, vitaminDmcg: 1,
    vitaminKmcg: 4.3, vitaminB12mcg: 0.65, folateMcg: 34, zincMg: 0.65, potassiumMg: 248, phosphorusMg: 99,
    blwNoteKa: 'გუფთები ცოტა გაბრტყელებული ფორმით გააკეთეთ, რომ ბავშვმა ხელით მარტივად აიღოს.',
    blwNoteEn: 'Shape balls slightly flattened so baby can grip them easily.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash with a fork.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 12-18 MONTHS (FROM_12) — DINNER — standard toddler dinners (salmon, pilaf,
  // gratin, cutlet dishes)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ქათმის გუფთა ბოსტნეულით',
    titleEn: 'Chicken Meatballs with Vegetables',
    descriptionKa: 'ქათმის ხორცი ბლენდერში ან ხორცსაკეპ მანქანაში გახეხეთ. სტაფილო და ყაბაყი წვრილად გახეხეთ, ხორცს შეუმატეთ. პატარა გუფთები ჩამოაყალიბეთ. ორთქლზე 15-18 წუთი მოხარშეთ ან ღუმელში გამოაცხვეთ.',
    descriptionEn: 'Mince chicken in blender or meat grinder. Grate carrot and zucchini finely and add to meat. Shape small balls. Steam for 15-18 minutes or bake in oven.',
    ingredientsKa: ['ქათმის ხორცი - 100 გ', 'სტაფილო - 40 გ', 'ყაბაყი - 40 გ'],
    ingredientsEn: ['Chicken meat - 100g', 'Carrot - 40g', 'Zucchini - 40g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: [],
    calories: 186, proteinGrams: 32, fatGrams: 3.8, carbsGrams: 4.5, fiberGrams: 1.6,
    ironMg: 0.9, vitaminCmg: 3, vitaminAmcg: 345, vitaminKmcg: 3.4, vitaminB6mg: 0.6,
    vitaminB12mcg: 0.3, folateMcg: 8, zincMg: 1, potassiumMg: 454, phosphorusMg: 220,
  },
  {
    titleKa: 'ორაგული და ბროკოლი',
    titleEn: 'Salmon and Broccoli',
    descriptionKa: 'ორაგული ორთქლზე ან ბულიონში 10-12 წუთი მოხარშეთ. ბროკოლი ყვავილებად გაყავით, ორთქლზე 6-8 წუთი დაარბილეთ. ცილებით, ომეგა-3-ითა და ვიტამინ C-ით მდიდარი ვახშამია.',
    descriptionEn: 'Steam or cook salmon in broth for 10-12 minutes. Divide broccoli into florets, soften by steaming for 6-8 minutes. A dinner rich in protein, omega-3 and vitamin C.',
    ingredientsKa: ['ორაგული - 90 გ', 'ბროკოლი - 80 გ'],
    ingredientsEn: ['Salmon - 90g', 'Broccoli - 80g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: ['fish'],
    calories: 213, proteinGrams: 22, fatGrams: 11.5, carbsGrams: 5.8, fiberGrams: 2.6,
    ironMg: 0.58, calciumMg: 32, vitaminCmg: 51.9, vitaminAmcg: 25, vitaminDmcg: 11.7,
    vitaminKmcg: 112.9, vitaminB12mcg: 2.52, folateMcg: 86, potassiumMg: 580, phosphorusMg: 216, omega3Mg: 1935,
  },
  {
    titleKa: 'ბოსტნეულის პილაფი',
    titleEn: 'Vegetable Pilaf',
    descriptionKa: 'ბრინჯი გარეცხეთ. სტაფილო წვრილად გახეხეთ, ბარდა დაუმატეთ. ბრინჯი და ბოსტნეული ბულიონში ან წყალში 20 წუთი ოდნავ ადუღეთ. ოდნავ გაგრილებული ასაკისთვის უსაფრთხო ზომებად მიეცით.',
    descriptionEn: 'Wash rice. Grate carrot finely and add peas. Simmer rice and vegetables in broth or water for 20 minutes. Serve slightly cooled in age-appropriate portions.',
    ingredientsKa: ['ბრინჯი, მოხარშული - 140 გ', 'სტაფილო - 40 გ', 'ბარდა - 30 გ'],
    ingredientsEn: ['Rice, cooked - 140g', 'Carrot - 40g', 'Peas - 30g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: [],
    calories: 221, proteinGrams: 5, fatGrams: 0.6, carbsGrams: 47.4, fiberGrams: 3.4,
    ironMg: 0.73, vitaminCmg: 5.5, vitaminAmcg: 341, vitaminKmcg: 10.9, folateMcg: 20,
    potassiumMg: 167, magnesiumMg: 17, phosphorusMg: 60,
  },
  {
    titleKa: 'ინდაური და გოგრა',
    titleEn: 'Turkey and Pumpkin',
    descriptionKa: 'ინდაურის ფილე ბულიონში ან ორთქლზე მოხარშეთ. გოგრა კუბიკებად დაჭერით, ორთქლზე 15 წუთი დაარბილეთ. ინდაური ბოჭკოებად ან კუბიკებად. ასაკისთვის უსაფრთხო ზომის ნაჭრებად მიეცით.',
    descriptionEn: 'Cook turkey fillet in broth or steam. Cut pumpkin into cubes and soften by steaming for 15 minutes. Serve turkey in fibers or cubes in age-appropriate sized pieces.',
    ingredientsKa: ['ინდაური - 90 გ', 'გოგრა - 80 გ'],
    ingredientsEn: ['Turkey - 90g', 'Pumpkin - 80g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: [],
    calories: 138, proteinGrams: 28, fatGrams: 0.7, carbsGrams: 3.9, fiberGrams: 0.9,
    ironMg: 1.26, vitaminCmg: 3.8, vitaminAmcg: 446, vitaminB6mg: 0.45, vitaminB12mcg: 0.27,
    zincMg: 1.35, potassiumMg: 399, phosphorusMg: 193,
  },
  {
    titleKa: 'ოსპის კატლეტები',
    titleEn: 'Lentil Cutlets',
    descriptionKa: 'ოსპი 25 წუთი მოხარშეთ სრულ დარბილებამდე. ბლენდერით ოდნავ გახეხეთ. კვერცხი დაუმატეთ, ჩამოაყალიბეთ. ღუმელში 180°C-ზე 20 წუთი გამოაცხვეთ. ასაკისთვის უსაფრთხო ზომებად მიეცით.',
    descriptionEn: 'Cook lentils for 25 minutes until fully soft. Blend slightly. Add egg and shape. Bake in oven at 180°C for 20 minutes. Serve in age-appropriate portions.',
    ingredientsKa: ['ოსპი, მოხარშული - 150 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Lentils, cooked - 150g', 'Egg - 1'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: ['egg'],
    calories: 252, proteinGrams: 20, fatGrams: 6.1, carbsGrams: 30.7, fiberGrams: 11.9,
    ironMg: 5.83, calciumMg: 28, vitaminAmcg: 80, vitaminDmcg: 1, vitaminB12mcg: 0.65,
    folateMcg: 295, zincMg: 2.6, potassiumMg: 554, magnesiumMg: 54, phosphorusMg: 369,
  },
  {
    titleKa: 'ყვავილოვანი კომბოსტოს გრატენი',
    titleEn: 'Cauliflower Gratin',
    descriptionKa: 'ყვავილოვანი კომბოსტო ყვავილებად გაყავით, ორთქლზე 8 წუთი ოდნავ დაარბილეთ. საცხობ ფირფიტაში დაალაგეთ. პასტერიზებული ყველი ზემოდან გადაიფხაქეთ. ღუმელში 180°C-ზე 15 წუთი გამოაცხვეთ.',
    descriptionEn: 'Divide cauliflower into florets, soften slightly by steaming for 8 minutes. Arrange in baking dish. Grate pasteurized cheese on top. Bake in oven at 180°C for 15 minutes.',
    ingredientsKa: ['ყვავილოვანი კომბოსტო - 150 გ', 'პასტერიზებული ყველი - 35 გ'],
    ingredientsEn: ['Cauliflower - 150g', 'Pasteurized cheese - 35g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: ['dairy'],
    calories: 175, proteinGrams: 11, fatGrams: 12.2, carbsGrams: 6.6, fiberGrams: 3.5,
    calciumMg: 252, vitaminCmg: 66.5, vitaminAmcg: 93, vitaminKmcg: 23.3, vitaminB12mcg: 0.29,
    folateMcg: 66, zincMg: 1.09, potassiumMg: 213, phosphorusMg: 179, sodiumMg: 217,
  },
  {
    titleKa: 'ქათამი და ტკბილი კარტოფილი',
    titleEn: 'Chicken and Sweet Potato',
    descriptionKa: 'ქათამი ბულიონში ან ორთქლზე მოხარშეთ. ტკბილი კარტოფილი გაფცქვენით, კუბიკებად დაჭერით, ორთქლზე 12 წუთი. ქათამი ბოჭკოებად ან კუბიკებად. ასაკისთვის უსაფრთხო ზომებად მიეცით.',
    descriptionEn: 'Cook chicken in broth or steam. Peel sweet potato, cut into cubes, steam for 12 minutes. Serve chicken in fibers or cubes in age-appropriate portions.',
    ingredientsKa: ['ქათამი - 90 გ', 'ტკბილი კარტოფილი - 100 გ'],
    ingredientsEn: ['Chicken - 90g', 'Sweet potato - 100g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: [],
    calories: 239, proteinGrams: 30, fatGrams: 3.4, carbsGrams: 20.7, fiberGrams: 3.3,
    ironMg: 1.5, calciumMg: 38, vitaminCmg: 19.6, vitaminAmcg: 961, vitaminB6mg: 0.83,
    vitaminB12mcg: 0.27, zincMg: 0.9, potassiumMg: 705, magnesiumMg: 27, phosphorusMg: 198,
  },
  {
    titleKa: 'ბოსტნეულის სუპი',
    titleEn: 'Vegetable Soup',
    descriptionKa: 'კარტოფილი, სტაფილო და ყაბაყი გაფცქვენით, კუბიკებად დაჭერით. ბულიონში ან წყალში 20 წუთი მოხარშეთ. ბლენდერით გლუვ ან ნახევრად გლუვ სუპად გახეხეთ. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel potato, carrot and zucchini, cut into cubes. Cook in broth or water for 20 minutes. Blend into smooth or semi-smooth soup. Serve slightly cooled.',
    ingredientsKa: ['კარტოფილი - 60 გ', 'სტაფილო - 50 გ', 'ყაბაყი - 50 გ'],
    ingredientsEn: ['Potato - 60g', 'Carrot - 50g', 'Zucchini - 50g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: [],
    calories: 78, proteinGrams: 2, fatGrams: 0.3, carbsGrams: 17.7, fiberGrams: 3.1,
    vitaminCmg: 11.6, vitaminAmcg: 431, vitaminKmcg: 4.3, vitaminB6mg: 0.16, folateMcg: 11,
    potassiumMg: 475, magnesiumMg: 13,
  },
  {
    titleKa: 'ბრინჯი და ავოკადო',
    titleEn: 'Rice and Avocado',
    descriptionKa: 'ბრინჯი კარგად მოხარშეთ, სანამ ძალიან რბილი გახდება. ავოკადო გახეხეთ, ჩანგლით ოდნავ დაჭყლიტეთ. ბრინჯი ოდნავ გაგრილებულს ავოკადო ზემოდან დაუმატეთ.',
    descriptionEn: 'Cook rice until very soft. Peel avocado and mash slightly with fork. Add avocado on top of slightly cooled rice.',
    ingredientsKa: ['ბრინჯი, მოხარშული - 110 გ', 'ავოკადო - 30 გ'],
    ingredientsEn: ['Rice, cooked - 110g', 'Avocado - 30g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: [],
    calories: 191, proteinGrams: 3, fatGrams: 4.7, carbsGrams: 33.6, fiberGrams: 2.4,
    ironMg: 0.22, vitaminCmg: 3, vitaminEmg: 0.62, vitaminKmcg: 6.3, vitaminB6mg: 0.08,
    folateMcg: 24, potassiumMg: 146, magnesiumMg: 22, phosphorusMg: 47,
  },
  {
    titleKa: 'კვერცხის მაფინი ბოსტნეულით',
    titleEn: 'Egg Muffin with Vegetables',
    descriptionKa: 'ბროკოლი და სტაფილო წვრილად გახეხეთ ან დაჭერით. კვერცხი ავურიეთ, ბოსტნეული შეუმატეთ. მინი მაფინის ფორმებში ჩაასხით. 180°C-ზე 15-18 წუთი გამოაცხვეთ. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Finely grate or chop broccoli and carrot. Beat egg and add vegetables. Pour into mini muffin forms. Bake at 180°C for 15-18 minutes. Serve slightly cooled.',
    ingredientsKa: ['კვერცხი - 2 ცალი', 'ბროკოლი - 40 გ', 'სტაფილო - 40 გ'],
    ingredientsEn: ['Egg - 2', 'Broccoli - 40g', 'Carrot - 40g'],
    ageGroups: ['FROM_12'], mealType: 'DINNER', allergens: ['egg'],
    calories: 183, proteinGrams: 14, fatGrams: 11.2, carbsGrams: 7.3, fiberGrams: 2.5,
    ironMg: 2.04, calciumMg: 72, vitaminCmg: 27.2, vitaminAmcg: 513, vitaminDmcg: 2,
    vitaminKmcg: 59.9, vitaminB12mcg: 1.29, folateMcg: 90, zincMg: 1.3, potassiumMg: 211, phosphorusMg: 198,
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 18-36 MONTHS (FROM_24) — DINNER — family-style dinners (schnitzel, salmon,
  // lasagna, meatball, and pilaf style dishes)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ქათმის შნიცელი ბოსტნეულით',
    titleEn: 'Chicken Schnitzel with Vegetables',
    descriptionKa: 'ქათმის ფილე გაბრტყელეთ. ორთქლზე მოხარშეთ ან ზეთის მინიმალური რაოდენობით შეწვით. ბროკოლი და სტაფილო ორთქლზე ოდნავ მოხარშეთ. ასაკისთვის უსაფრთხო ზომის ნაჭრებად მიეცით.',
    descriptionEn: 'Flatten chicken fillet. Steam or cook with minimal oil. Lightly steam broccoli and carrot. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ქათმის ფილე - 110 გ', 'ბროკოლი - 60 გ', 'სტაფილო - 50 გ'],
    ingredientsEn: ['Chicken fillet - 110g', 'Broccoli - 60g', 'Carrot - 50g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 220, proteinGrams: 36, fatGrams: 4.3, carbsGrams: 8.4, fiberGrams: 3.5,
    ironMg: 1.43, calciumMg: 24, vitaminCmg: 40.4, vitaminAmcg: 445, vitaminKmcg: 89,
    vitaminB6mg: 0.66, vitaminB12mcg: 0.33, folateMcg: 65, zincMg: 1.1, potassiumMg: 575, phosphorusMg: 242,
  },
  {
    titleKa: 'ორაგული ბრინჯით',
    titleEn: 'Salmon with Rice',
    descriptionKa: 'ორაგული ორთქლზე ან ბულიონში 10-12 წუთი მოხარშეთ. ბრინჯი ცალ-ცალკე კარგად მოხარშეთ. ერთ თეფშზე მოაწყვეთ. ომეგა-3 ცხიმოვანი მჟავების შესანიშნავი წყაროა.',
    descriptionEn: 'Steam or cook salmon in broth for 10-12 minutes. Cook rice separately until done. Arrange on one plate. An excellent source of omega-3 fatty acids.',
    ingredientsKa: ['ორაგული - 110 გ', 'ბრინჯი, მოხარშული - 130 გ'],
    ingredientsEn: ['Salmon - 110g', 'Rice, cooked - 130g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: ['fish'],
    calories: 396, proteinGrams: 27, fatGrams: 14, carbsGrams: 36.7, fiberGrams: 0.5,
    ironMg: 0.26, vitaminDmcg: 14.3, vitaminB12mcg: 3.08, potassiumMg: 422, magnesiumMg: 16,
    phosphorusMg: 320, omega3Mg: 2365,
  },
  {
    titleKa: 'ინდაურის კატლეტი',
    titleEn: 'Turkey Cutlet',
    descriptionKa: 'ინდაური ბლენდერში გახეხეთ. ყაბაყი წვრილად გახეხეთ, წყალი გამოწუროთ, ხორცს შეუმატეთ. კატლეტები ჩამოაყალიბეთ. ორთქლზე 15-18 წუთი ან ღუმელში 180°C-ზე 20 წუთი მოხარშეთ.',
    descriptionEn: 'Blend turkey. Grate zucchini finely, squeeze out water and add to meat. Shape cutlets. Steam for 15-18 minutes or bake at 180°C for 20 minutes.',
    ingredientsKa: ['ინდაური - 135 გ', 'ყაბაყი - 60 გ'],
    ingredientsEn: ['Turkey - 135g', 'Zucchini - 60g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 192, proteinGrams: 41, fatGrams: 1.1, carbsGrams: 1.9, fiberGrams: 0.6,
    ironMg: 1.89, vitaminCmg: 2.8, vitaminAmcg: 6, vitaminB6mg: 0.68, vitaminB12mcg: 0.41,
    folateMcg: 13, zincMg: 2.03, potassiumMg: 479, phosphorusMg: 289,
  },
  {
    titleKa: 'ბოსტნეულის ლაზანია',
    titleEn: 'Vegetable Lasagna',
    descriptionKa: 'ბოსტნეული (ყაბაყი, სტაფილო, ბარდა) წვრილად დაჭერით. ლაზანიის ფენები ბოსტნეულისა და ყველის ფენებს მოარიდეთ. ღუმელში 180°C-ზე 25-30 წუთი გამოაცხვეთ. ოდნავ გაგრილებული ასაკისთვის უსაფრთხო ზომებად მიეცით.',
    descriptionEn: 'Finely chop vegetables (zucchini, carrot, peas). Layer lasagna sheets with vegetable and cheese layers. Bake in oven at 180°C for 25-30 minutes. Serve slightly cooled in age-appropriate portions.',
    ingredientsKa: ['ლაზანიის ფირფიტები, მოხარშული - 100 გ', 'ყველი - 50 გ', 'ბოსტნეული (სტაფილო, ყაბაყი) - 120 გ', 'ბარდა - 30 გ'],
    ingredientsEn: ['Lasagna sheets, cooked - 100g', 'Cheese - 50g', 'Vegetables (carrot, zucchini) - 120g', 'Peas - 30g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: ['dairy', 'gluten'],
    calories: 388, proteinGrams: 20, fatGrams: 18, carbsGrams: 37.1, fiberGrams: 5.9,
    ironMg: 1.35, calciumMg: 361, vitaminCmg: 8.8, vitaminAmcg: 650, vitaminKmcg: 12.6,
    vitaminB12mcg: 0.42, folateMcg: 52, zincMg: 1.55, potassiumMg: 371, magnesiumMg: 18, phosphorusMg: 256, sodiumMg: 311,
  },
  {
    titleKa: 'პასტა ტომატის სოუსით',
    titleEn: 'Pasta with Tomato Sauce',
    descriptionKa: 'მაკარონი ალ დენტეზე ოდნავ მეტ ხანს მოხარშეთ, სანამ ძალიან რბილი გახდება. ტომატი პიურედ გადააქციეთ, ოდნავ ჩააშუშეთ. სოუსი პასტას დაასხით.',
    descriptionEn: 'Cook pasta slightly longer than al dente until very soft. Puree tomato and lightly simmer. Pour sauce over pasta.',
    ingredientsKa: ['მაკარონი, მოხარშული - 140 გ', 'ტომატი - 100 გ'],
    ingredientsEn: ['Pasta, cooked - 140g', 'Tomato - 100g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: ['gluten'],
    calories: 201, proteinGrams: 8, fatGrams: 1.7, carbsGrams: 38.9, fiberGrams: 3.7,
    ironMg: 1.26, vitaminCmg: 13.7, vitaminAmcg: 42, folateMcg: 43, potassiumMg: 237, magnesiumMg: 25,
  },
  {
    titleKa: 'ლობიოს ჩაშუშული',
    titleEn: 'Bean Stew',
    descriptionKa: 'ლობიო წინასწარ გაჟღენთეთ, 40-50 წუთი მოხარშეთ. ბოსტნეული (სტაფილო, პომიდორი) წვრილ კუბიკებად დაჭერით, ჩააშუშეთ. ლობიო ბოსტნეულს შეუმატეთ, 10 წუთი ერთად მოხარშეთ.',
    descriptionEn: 'Soak beans beforehand, cook for 40-50 minutes. Finely dice vegetables (carrot, tomato) and stew. Add beans to vegetables and cook together for 10 minutes.',
    ingredientsKa: ['ლობიო, მოხარშული - 110 გ', 'სტაფილო - 50 გ', 'პომიდორი - 40 გ'],
    ingredientsEn: ['Beans, cooked - 110g', 'Carrot - 50g', 'Tomato - 40g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 178, proteinGrams: 11, fatGrams: 0.6, carbsGrams: 33.3, fiberGrams: 8.9,
    ironMg: 2.97, calciumMg: 99, vitaminCmg: 7, vitaminAmcg: 443, vitaminKmcg: 4.3,
    folateMcg: 116, potassiumMg: 829, magnesiumMg: 69,
  },
  {
    titleKa: 'ბოსტნეულის სუპი',
    titleEn: 'Vegetable Soup',
    descriptionKa: 'კარტოფილი, სტაფილო და ბროკოლი გაფცქვენით, კუბიკებად დაჭერით. ბულიონში 20 წუთი მოხარშეთ. ბლენდერით ნახევრად გახეხეთ ან მთლიანად დატოვეთ. ოდნავ გაგრილებული მიეცით.',
    descriptionEn: 'Peel potato, carrot and broccoli, cut into cubes. Cook in broth for 20 minutes. Blend partially or leave chunky. Serve slightly cooled.',
    ingredientsKa: ['კარტოფილი - 60 გ', 'სტაფილო - 50 გ', 'ბროკოლი - 60 გ'],
    ingredientsEn: ['Potato - 60g', 'Carrot - 50g', 'Broccoli - 60g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 91, proteinGrams: 3, fatGrams: 0.4, carbsGrams: 20.5, fiberGrams: 4.6,
    ironMg: 0.44, calciumMg: 24, vitaminCmg: 48.2, vitaminAmcg: 445, vitaminKmcg: 89,
    vitaminB6mg: 0.16, folateMcg: 65, potassiumMg: 521, magnesiumMg: 13,
  },
  {
    titleKa: 'საქონლის ხორცის გუფთა',
    titleEn: 'Beef Meatballs',
    descriptionKa: 'საქონლის ხორცი ბლენდერში ან ხორცსაკეპ მანქანაში გახეხეთ. ბრინჯი ოდნავ მოხარშეთ, შეუმატეთ. პატარა გუფთები ჩამოაყალიბეთ. ბულიონში ან ორთქლზე 20-25 წუთი მოხარშეთ.',
    descriptionEn: 'Mince beef in blender or meat grinder. Lightly cook rice and add. Shape small balls. Cook in broth or steam for 20-25 minutes.',
    ingredientsKa: ['საქონლის ხორცი, მჭლე - 135 გ', 'ბრინჯი, მოხარშული - 60 გ'],
    ingredientsEn: ['Lean beef - 135g', 'Rice, cooked - 60g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 326, proteinGrams: 42, fatGrams: 9, carbsGrams: 16.9, fiberGrams: 0.2,
    ironMg: 3.63, vitaminB12mcg: 3.51, zincMg: 7.29, potassiumMg: 459, magnesiumMg: 7, phosphorusMg: 350,
  },
  {
    titleKa: 'ქათმის პილაფი',
    titleEn: 'Chicken Pilaf',
    descriptionKa: 'ქათამი კუბიკებად დაჭერით, ოდნავ შეწვით. ბრინჯი და სტაფილო დაუმატეთ. ბულიონი ჩაასხით, დაფარეთ სახურავით. 20-25 წუთი ოდნავ ადუღეთ. ოდნავ გაგრილებული ასაკისთვის უსაფრთხო ზომებად მიეცით.',
    descriptionEn: 'Cut chicken into cubes and lightly fry. Add rice and carrot. Pour in broth and cover. Simmer for 20-25 minutes. Serve slightly cooled in age-appropriate portions.',
    ingredientsKa: ['ქათამი - 110 გ', 'ბრინჯი, მოხარშული - 130 გ', 'სტაფილო - 50 გ'],
    ingredientsEn: ['Chicken - 110g', 'Rice, cooked - 130g', 'Carrot - 50g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 368, proteinGrams: 38, fatGrams: 4.4, carbsGrams: 40.8, fiberGrams: 2,
    ironMg: 1.25, vitaminCmg: 1.5, vitaminAmcg: 426, vitaminKmcg: 4.3, vitaminB6mg: 0.66,
    vitaminB12mcg: 0.33, zincMg: 1.1, potassiumMg: 399, magnesiumMg: 16, phosphorusMg: 298,
  },
  {
    titleKa: 'ოჯახური ვახშმის თეფში',
    titleEn: 'Family Dinner Plate',
    descriptionKa: 'ბალანსირებული ვახშამი: ცილა (ქათამი/ინდაური/ორაგული/კვერცხი), ბოსტნეული (ყაბაყი/ბარდა/ბროკოლი) და მარცვლეული (ბრინჯი/მაკარონი) ასაკისთვის უსაფრთხო ზომებად ერთ თეფშზე. ოჯახთან ერთად მიეცით.',
    descriptionEn: 'A balanced dinner: protein (chicken/turkey/salmon/egg), vegetables (zucchini/peas/broccoli) and grains (rice/pasta) in age-appropriate portions on one plate. Serve together with the family.',
    ingredientsKa: ['ქათმის ფილე - 100 გ', 'ყაბაყი - 45 გ', 'ბარდა - 35 გ', 'ბრინჯი, მოხარშული - 60 გ'],
    ingredientsEn: ['Chicken fillet - 100g', 'Zucchini - 45g', 'Peas - 35g', 'Rice, cooked - 60g'],
    ageGroups: ['FROM_24'], mealType: 'DINNER', allergens: [],
    calories: 280, proteinGrams: 35, fatGrams: 4, carbsGrams: 23.8, fiberGrams: 2.6,
    ironMg: 1.55, vitaminCmg: 7, vitaminAmcg: 5, vitaminKmcg: 8.7, vitaminB6mg: 0.6,
    vitaminB12mcg: 0.3, folateMcg: 32, zincMg: 1, potassiumMg: 459, magnesiumMg: 7, phosphorusMg: 246,
  },
];

async function main() {
  console.log('🌱 Seeding 40 dinner recipes...');

  let created = 0;
  let skipped = 0;

  for (const r of recipes) {
    const existing = await prisma.dish.findFirst({
      where: { titleKa: r.titleKa, mealType: 'DINNER', ageGroups: { equals: r.ageGroups as any } },
    });

    if (existing) {
      skipped++;
      console.log(`  ⏭  Already exists: ${r.titleKa}`);
      continue;
    }

    await prisma.dish.create({
      data: {
        titleKa: r.titleKa,
        titleEn: r.titleEn,
        descriptionKa: r.descriptionKa,
        descriptionEn: r.descriptionEn,
        ingredientsKa: r.ingredientsKa,
        ingredientsEn: r.ingredientsEn,
        ageGroups: r.ageGroups as any,
        mealType: r.mealType as any,
        allergens: r.allergens || [],
        calories: (r as any).calories ?? null,
        proteinGrams: (r as any).proteinGrams ?? null,
        fatGrams: (r as any).fatGrams ?? null,
        carbsGrams: (r as any).carbsGrams ?? null,
        fiberGrams: (r as any).fiberGrams ?? null,
        ironMg: (r as any).ironMg ?? null,
        calciumMg: (r as any).calciumMg ?? null,
        vitaminCmg: (r as any).vitaminCmg ?? null,
        vitaminAmcg: (r as any).vitaminAmcg ?? null,
        vitaminDmcg: (r as any).vitaminDmcg ?? null,
        vitaminEmg: (r as any).vitaminEmg ?? null,
        vitaminKmcg: (r as any).vitaminKmcg ?? null,
        vitaminB6mg: (r as any).vitaminB6mg ?? null,
        vitaminB12mcg: (r as any).vitaminB12mcg ?? null,
        folateMcg: (r as any).folateMcg ?? null,
        zincMg: (r as any).zincMg ?? null,
        potassiumMg: (r as any).potassiumMg ?? null,
        magnesiumMg: (r as any).magnesiumMg ?? null,
        phosphorusMg: (r as any).phosphorusMg ?? null,
        sodiumMg: (r as any).sodiumMg ?? null,
        omega3Mg: (r as any).omega3Mg ?? null,
        blwNoteKa: (r as any).blwNoteKa ?? null,
        blwNoteEn: (r as any).blwNoteEn ?? null,
        pureeNoteKa: (r as any).pureeNoteKa ?? null,
        pureeNoteEn: (r as any).pureeNoteEn ?? null,
      },
    });
    created++;
    console.log(`  ✓  ${r.titleKa}`);
  }

  console.log(`\n✅ Done: ${created} created, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
