import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Recipes below are original Georgian writing, built around common, widely-known
// infant/toddler feeding combinations (age-appropriate purees, finger foods, and family
// dishes) that appear across baby-feeding guidance worldwide and are not the copyrightable
// expression of any single source. Nutrient values are computed from a reusable per-100g
// reference table built from USDA FoodData Central figures (public domain / CC0).
const recipes = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 6-8 MONTHS (FROM_6) — first-weaning purees and soft porridges
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბანანისა და შვრიის ფაფა',
    titleEn: 'Banana Oat Porridge',
    descriptionKa: 'შვრია მოხარშეთ წყალში 5-7 წუთი, სანამ კარგად დარბილდება. ბანანი დაჭყლიტეთ ჩანგლით. შეურიეთ ფაფას და საჭიროების შემთხვევაში დააბლენდერეთ. მიეცით თბილი, არა ცხელი.',
    descriptionEn: 'Cook oats in water for 5-7 minutes until soft. Mash banana with a fork. Mix into porridge and blend if needed. Serve warm, not hot.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'მწიფე ბანანი - 50 გ', 'წყალი ან დედის რძე/ფორმულა - 120 მლ'],
    ingredientsEn: ['Oat flakes - 20g', 'Ripe banana - 50g', 'Water or breast milk/formula - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 122, proteinGrams: 4, fatGrams: 1.5, carbsGrams: 24.7, fiberGrams: 3.4,
    ironMg: 1.07, calciumMg: 11, vitaminCmg: 4.4, vitaminEmg: 0.14, vitaminB6mg: 0.22,
    folateMcg: 21, zincMg: 0.8, potassiumMg: 265, magnesiumMg: 49, phosphorusMg: 105,
    allergens: ['gluten'],
    blwNoteKa: 'მოამზადეთ უფრო სქელი და შესთავაზეთ წინასწარ დატვირთულ კოვზზე.',
    blwNoteEn: 'Make thicker and serve on a pre-loaded spoon.',
    pureeNoteKa: 'დააბლენდერეთ სრულიად გლუვ მასად, განსაკუთრებით 6 თვის დასაწყისში.',
    pureeNoteEn: 'Blend completely smooth, especially at the start of 6 months.',
  },
  {
    titleKa: 'ვაშლის შვრიის ფაფა',
    titleEn: 'Apple Oat Porridge',
    descriptionKa: 'ვაშლი დაჭერით და ორთქლზე მოამზადეთ 7-10 წუთი. შვრია მოხარშეთ წყალში. ვაშლი დაჭყლიტეთ და შეურიეთ ფაფას.',
    descriptionEn: 'Slice apple and steam for 7-10 minutes. Cook oats in water. Mash apple and mix into porridge.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'ვაშლი, გაფცქვნილი - 60 გ', 'წყალი - 120 მლ'],
    ingredientsEn: ['Oat flakes - 20g', 'Apple, peeled - 60g', 'Water - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 109, proteinGrams: 4, fatGrams: 1.5, carbsGrams: 21.5, fiberGrams: 3.6,
    ironMg: 0.94, calciumMg: 11, vitaminCmg: 2.8, vitaminEmg: 0.14, vitaminB6mg: 0.02,
    folateMcg: 13, zincMg: 0.8, potassiumMg: 150, magnesiumMg: 35, phosphorusMg: 105,
    allergens: ['gluten'],
    blwNoteKa: 'დატოვეთ ოდნავ მარცვლოვანი ტექსტურა, თუ ბავშვი უკვე კარგად იღებს სქელ ფაფას.',
    blwNoteEn: 'Leave slightly grainy texture if baby already handles thick porridge well.',
    pureeNoteKa: 'ვაშლი და შვრია ერთად დააბლენდერეთ, რომ კანი/ნაჭრები არ დარჩეს.',
    pureeNoteEn: 'Blend apple and oats together so no skin or pieces remain.',
  },
  {
    titleKa: 'გოგრის შვრიის ფაფა',
    titleEn: 'Pumpkin Oat Porridge',
    descriptionKa: 'გოგრა ორთქლზე ან წყალში მოხარშეთ სრულ დარბილებამდე. შვრია მოხარშეთ ცალკე. შეურიეთ გოგრა და შვრია. დააბლენდერეთ სასურველ ტექსტურამდე.',
    descriptionEn: 'Steam or boil pumpkin until fully soft. Cook oats separately. Mix pumpkin and oats. Blend to desired texture.',
    ingredientsKa: ['გოგრა - 70 გ', 'შვრიის ფანტელი - 20 გ', 'წყალი - 120 მლ'],
    ingredientsEn: ['Pumpkin - 70g', 'Oat flakes - 20g', 'Water - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 92, proteinGrams: 4, fatGrams: 1.5, carbsGrams: 16.7, fiberGrams: 2.9,
    ironMg: 0.94, calciumMg: 11, vitaminCmg: 3.3, vitaminAmcg: 391, vitaminEmg: 0.14,
    vitaminB6mg: 0.02, folateMcg: 11, zincMg: 0.8, potassiumMg: 247, magnesiumMg: 35, phosphorusMg: 105,
    allergens: ['gluten'],
    blwNoteKa: 'გააკეთეთ სქელი ფაფა და მიეცით კოვზით; ცალკე გოგრის ძალიან რბილი ზოლებიც შეიძლება.',
    blwNoteEn: 'Make thick porridge and serve by spoon; very soft pumpkin strips can be offered separately.',
    pureeNoteKa: 'გაათხელეთ წყლით ან რძით, თუ ფაფა ძალიან სქელია.',
    pureeNoteEn: 'Thin with water or milk if porridge is too thick.',
  },
  {
    titleKa: 'ავოკადოს შვრიის ფაფა',
    titleEn: 'Avocado Oat Porridge',
    descriptionKa: 'შვრია მოხარშეთ კარგად დარბილებამდე. ავოკადო დაჭყლიტეთ გლუვად. შეურიეთ თბილ, ოდნავ გაგრილებულ ფაფას. ავოკადოს არ ადუღებთ, რომ გემო არ გამწარდეს.',
    descriptionEn: 'Cook oats until well softened. Mash avocado smoothly. Mix into warm, slightly cooled porridge. Do not boil avocado, to keep it from turning bitter.',
    ingredientsKa: ['შვრიის ფანტელი - 18 გ', 'მწიფე ავოკადო - 35 გ', 'წყალი - 100 მლ'],
    ingredientsEn: ['Oat flakes - 18g', 'Ripe avocado - 35g', 'Water - 100ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 126, proteinGrams: 4, fatGrams: 6.4, carbsGrams: 14.9, fiberGrams: 4.3,
    ironMg: 0.85, calciumMg: 10, vitaminCmg: 3.5, vitaminEmg: 0.85, vitaminKmcg: 7.4,
    vitaminB6mg: 0.11, folateMcg: 38, zincMg: 0.72, potassiumMg: 247, magnesiumMg: 42, phosphorusMg: 94,
    allergens: ['gluten'],
    blwNoteKa: 'სქელი ფაფა შესთავაზეთ კოვზზე; ავოკადოს რბილი გრძელი ნაჭერი შეიძლება ცალკეც.',
    blwNoteEn: 'Offer thick porridge on spoon; a soft long piece of avocado can be offered separately.',
    pureeNoteKa: 'შვრია და ავოკადო ერთად დააბლენდერეთ კრემისებრ მასად.',
    pureeNoteEn: 'Blend oats and avocado together into a creamy mass.',
  },
  {
    titleKa: 'მსხლისა და ფეტვის ფაფა',
    titleEn: 'Pear Millet Porridge',
    descriptionKa: 'ფეტვი კარგად გარეცხეთ და მოხარშეთ წყალში 15-18 წუთი, სანამ დარბილდება. მსხალი ორთქლზე მოამზადეთ ან ფაფაში ჩახარშეთ. დააბლენდერეთ საჭირო ტექსტურამდე. ალტერნატიული მარცვლის დამატება ინარჩუნებს რაციონის მრავალფეროვნებას.',
    descriptionEn: 'Rinse millet well and cook in water for 15-18 minutes until soft. Steam pear or cook it into the porridge. Blend to desired texture. Rotating grains keeps the diet varied.',
    ingredientsKa: ['ფეტვი, მოხარშული - 60 გ', 'მსხალი, გაფცქვნილი - 60 გ', 'წყალი - 60 მლ'],
    ingredientsEn: ['Millet, cooked - 60g', 'Pear, peeled - 60g', 'Water - 60ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 106, proteinGrams: 2, fatGrams: 0.7, carbsGrams: 23.3, fiberGrams: 2.6,
    ironMg: 0.63, vitaminCmg: 2.6, folateMcg: 4, zincMg: 0.54, potassiumMg: 107, magnesiumMg: 26, phosphorusMg: 60,
    allergens: [],
    blwNoteKa: 'უფრო სქელი მასა დადეთ კოვზზე ან პატარა რბილ გუნდებად.',
    blwNoteEn: 'Put thicker mass on spoon or shape into small soft balls.',
    pureeNoteKa: 'მოხარშვის შემდეგ კარგად დააბლენდერეთ, რადგან ფეტვი მარცვლოვანი რჩება.',
    pureeNoteEn: 'Blend well after cooking as millet tends to remain grainy.',
  },
  {
    titleKa: 'ატმის შვრიის ფაფა',
    titleEn: 'Peach Oat Porridge',
    descriptionKa: 'ატამს მოაშორეთ კანი და კურკა. ორთქლზე ოდნავ დაარბილეთ, თუ ძალიან რბილი არ არის. შვრია მოხარშეთ 5-7 წუთი. შეურიეთ და დააბლენდერეთ.',
    descriptionEn: 'Remove peach skin and pit. Slightly soften by steaming if not very soft. Cook oats for 5-7 minutes. Mix and blend.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'მწიფე ატამი - 60 გ', 'წყალი - 120 მლ'],
    ingredientsEn: ['Oat flakes - 20g', 'Ripe peach - 60g', 'Water - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 101, proteinGrams: 4, fatGrams: 1.5, carbsGrams: 19, fiberGrams: 3,
    ironMg: 0.94, calciumMg: 11, vitaminCmg: 4, vitaminAmcg: 10, vitaminEmg: 0.14,
    vitaminB6mg: 0.02, folateMcg: 11, zincMg: 0.8, potassiumMg: 200, magnesiumMg: 35, phosphorusMg: 105,
    allergens: ['gluten'],
    blwNoteKa: 'სქელი ფაფა კოვზზე; ძალიან რბილი ატმის გრძელი ნაჭერი მხოლოდ მაშინ, თუ ბავშვი მზად არის.',
    blwNoteEn: 'Thick porridge on spoon; a long piece of very soft peach only when baby is ready.',
    pureeNoteKa: 'ატამი და შვრია დააბლენდერეთ ერთგვაროვნად.',
    pureeNoteEn: 'Blend peach and oats uniformly.',
  },
  {
    titleKa: 'მანგოს შვრიის ფაფა',
    titleEn: 'Mango Oat Porridge',
    descriptionKa: 'შვრია მოხარშეთ წყალში დარბილებამდე. მანგო გაფცქვენით და დაჭყლიტეთ. შეურიეთ ფაფას და საჭიროების შემთხვევაში დააბლენდერეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Cook oats in water until soft. Peel and mash mango. Mix into porridge and blend if needed. Serve freshly made.',
    ingredientsKa: ['შვრიის ფანტელი - 20 გ', 'მწიფე მანგო - 55 გ', 'წყალი - 120 მლ'],
    ingredientsEn: ['Oat flakes - 20g', 'Ripe mango - 55g', 'Water - 120ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 111, proteinGrams: 4, fatGrams: 1.6, carbsGrams: 21.5, fiberGrams: 3,
    ironMg: 0.94, calciumMg: 11, vitaminCmg: 20, vitaminAmcg: 30, vitaminEmg: 0.14,
    vitaminB6mg: 0.02, folateMcg: 35, zincMg: 0.8, potassiumMg: 178, magnesiumMg: 35, phosphorusMg: 105,
    allergens: ['gluten'],
    blwNoteKa: 'სქელი ფაფა კოვზზე; ძალიან სრიალა მანგოს ნაჭერი ფრთხილად შესთავაზეთ.',
    blwNoteEn: 'Thick porridge on spoon; offer slippery mango piece carefully.',
    pureeNoteKa: 'მანგო და ფაფა ერთად დააბლენდერეთ კრემისებრ მასად.',
    pureeNoteEn: 'Blend mango and porridge together into a creamy mass.',
  },
  {
    titleKa: 'ტკბილი კარტოფილისა და შვრიის ფაფა',
    titleEn: 'Sweet Potato Oat Porridge',
    descriptionKa: 'ტკბილი კარტოფილი გაფცქვენით და ორთქლზე მოხარშეთ. შვრია მოხარშეთ წყალში. შეურიეთ და დააბლენდერეთ. საჭიროების შემთხვევაში გაათხელეთ წყლით.',
    descriptionEn: 'Peel sweet potato and steam. Cook oats in water. Mix and blend. Thin with water if needed.',
    ingredientsKa: ['ტკბილი კარტოფილი - 70 გ', 'შვრიის ფანტელი - 20 გ', 'წყალი - 130 მლ'],
    ingredientsEn: ['Sweet potato - 70g', 'Oat flakes - 20g', 'Water - 130ml'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 141, proteinGrams: 5, fatGrams: 1.5, carbsGrams: 27.8, fiberGrams: 4.4,
    ironMg: 1.42, calciumMg: 37, vitaminCmg: 13.7, vitaminAmcg: 673, vitaminEmg: 0.14,
    vitaminB6mg: 0.22, folateMcg: 11, zincMg: 0.8, potassiumMg: 418, magnesiumMg: 54, phosphorusMg: 105,
    allergens: ['gluten'],
    blwNoteKa: 'ტკბილი კარტოფილის ძალიან რბილი ზოლი შეიძლება ცალკე; ფაფა კოვზით.',
    blwNoteEn: 'Very soft sweet potato strip can be offered separately; porridge by spoon.',
    pureeNoteKa: 'გააკეთეთ გლუვი, სქელი პიურე.',
    pureeNoteEn: 'Make a smooth, thick puree.',
  },
  {
    titleKa: 'წიწიბურას ფაფა ბანანით',
    titleEn: 'Buckwheat Banana Porridge',
    descriptionKa: 'წიწიბურა კარგად გარეცხეთ და მოხარშეთ სრულ დარბილებამდე. დაუმატეთ დაჭყლეტილი ბანანი. დააბლენდერეთ, თუ ბავშვი ჯერ მარცვლოვან ტექსტურას ვერ იღებს.',
    descriptionEn: 'Rinse buckwheat well and cook until fully soft. Add mashed banana. Blend if baby cannot yet handle grainy texture.',
    ingredientsKa: ['წიწიბურა, მოხარშული - 70 გ', 'ბანანი - 50 გ'],
    ingredientsEn: ['Buckwheat, cooked - 70g', 'Banana - 50g'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 109, proteinGrams: 3, fatGrams: 0.6, carbsGrams: 25.3, fiberGrams: 3.2,
    ironMg: 0.9, vitaminCmg: 4.4, vitaminB6mg: 0.2, folateMcg: 20, zincMg: 0.49,
    potassiumMg: 241, magnesiumMg: 49, phosphorusMg: 49,
    allergens: [],
    blwNoteKa: 'გაასქელეთ და შესთავაზეთ კოვზზე ან რბილ პატარა გუნდებად.',
    blwNoteEn: 'Thicken and offer on spoon or as small soft balls.',
    pureeNoteKa: 'დააბლენდერეთ კარგად, რადგან წიწიბურას მარცვლოვანი სტრუქტურა აქვს.',
    pureeNoteEn: 'Blend well as buckwheat has a grainy structure.',
  },
  {
    titleKa: 'მსხლისა და ავოკადოს კრემი',
    titleEn: 'Pear Avocado Cream',
    descriptionKa: 'მსხალი გაფცქვენით და მოაშორეთ გული. ავოკადო და მსხალი დაჭყლიტეთ. დააბლენდერეთ კრემისებრ მასად. მიეცით მომზადებისთანავე — ავოკადო სწრაფად ჟანგდება.',
    descriptionEn: 'Peel pear and remove core. Mash avocado and pear. Blend into a creamy mass. Serve immediately after preparation — avocado oxidises quickly.',
    ingredientsKa: ['მწიფე ავოკადო - 35 გ', 'მწიფე მსხალი, გაფცქვნილი - 60 გ'],
    ingredientsEn: ['Ripe avocado - 35g', 'Ripe pear, peeled - 60g'],
    ageGroups: ['FROM_6'],
    mealType: 'BREAKFAST',
    calories: 90, proteinGrams: 1, fatGrams: 5.2, carbsGrams: 12.1, fiberGrams: 4.2,
    vitaminCmg: 6.1, vitaminEmg: 0.72, vitaminKmcg: 7.4, vitaminB6mg: 0.09, folateMcg: 33,
    potassiumMg: 239, magnesiumMg: 10,
    allergens: [],
    blwNoteKa: 'ავოკადოს გრძელი რბილი ნაჭერი და ძალიან რბილი მსხლის ნაჭერი შეიძლება ცალკე, მუდმივი მეთვალყურეობით.',
    blwNoteEn: 'Long soft avocado piece and very soft pear piece can be offered separately with constant supervision.',
    pureeNoteKa: 'დააბლენდერეთ სრულად, რომ სრიალა და ერთგვაროვანი იყოს.',
    pureeNoteEn: 'Blend completely to make smooth and uniform.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 9-11 MONTHS (FROM_9) — soft finger foods for self-feeding practice
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბროკოლის ომლეტის ჩხირები',
    titleEn: 'Broccoli Omelette Fingers',
    descriptionKa: 'ბროკოლი ორთქლზე მოხარშეთ და წვრილად დაჭერით. კვერცხი ავურიეთ. ზეითუნის ზეთზე გამოაცხვეთ ომლეტი ბროკოლით და ცოტა ხანს მოიცადეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Steam broccoli and finely chop. Beat egg. Cook omelette with broccoli in olive oil. Prepare with age-appropriate texture.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ბროკოლი - 35 გ', 'ზეითუნის ზეთი - 1 ჩ/კ'],
    ingredientsEn: ['Egg - 1', 'Broccoli - 35g', 'Olive oil - 1 tsp'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 90, proteinGrams: 7, fatGrams: 5.6, carbsGrams: 3.1, fiberGrams: 1.2,
    ironMg: 1.13, calciumMg: 42, vitaminCmg: 22.7, vitaminAmcg: 91, vitaminDmcg: 1,
    vitaminKmcg: 49.4, vitaminB12mcg: 0.65, folateMcg: 61, zincMg: 0.65, potassiumMg: 103, phosphorusMg: 99,
    allergens: ['egg'],
    blwNoteKa: 'ომლეტი დაჭერით პატარა, თითის ტოლი ნაჭრებად, რომ ბავშვმა ხელით აიღოს.',
    blwNoteEn: 'Cut omelette into small finger-sized pieces for self-feeding.',
    pureeNoteKa: 'ომლეტი ბლენდერით დაამსხვილეთ ან ჩანგლით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash omelette with a fork or blend until fine.',
  },
  {
    titleKa: 'ბანანის შვრიის ბლინები',
    titleEn: 'Banana Oat Pancakes',
    descriptionKa: 'ბანანი კარგად დაჭყლიტეთ. კვერცხი და შვრიის ფქვილი შეურიეთ ბანანს. პატარა ბლინები გამოაცხვეთ ზეთის გარეშე ან მინიმალური ზეთით. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Mash banana well. Mix egg and oat flour into banana. Cook small pancakes with no or minimal oil. Prepare with age-appropriate texture.',
    ingredientsKa: ['ბანანი - 1 მწიფე (60 გ)', 'კვერცხი - 1 ცალი', 'შვრიის ფქვილი - 25 გ'],
    ingredientsEn: ['Banana - 1 ripe (60g)', 'Egg - 1', 'Oat flour - 25g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 232, proteinGrams: 11, fatGrams: 8, carbsGrams: 30.7, fiberGrams: 3.2,
    ironMg: 2.16, calciumMg: 28, vitaminCmg: 5.2, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminB6mg: 0.24, vitaminB12mcg: 0.65, folateMcg: 44, zincMg: 1.45, potassiumMg: 215, magnesiumMg: 52, phosphorusMg: 207,
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'პატარა, მრგვალი ბლინები ბავშვისთვის ხელით მისაღებად მოხერხებულია.',
    blwNoteEn: 'Small round pancakes are convenient for self-feeding.',
    pureeNoteKa: 'ბლინი ჩანგლით დაჭყლიტეთ ან ოდნავ გაათბეთ.',
    pureeNoteEn: 'Mash pancake with a fork or warm slightly.',
  },
  {
    titleKa: 'ისპანახის ომლეტი',
    titleEn: 'Spinach Omelette',
    descriptionKa: 'ისპანახი ოდნავ შეაცხვეთ ზეთში, სანამ დარბილდება. კვერცხი ავურიეთ და ისპანახს შეუმატეთ. ომლეტი გამოაცხვეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Lightly sauté spinach in oil until soft. Beat egg and add to spinach. Cook omelette. Prepare with age-appropriate texture.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ისპანახი - 35 გ'],
    ingredientsEn: ['Egg - 1', 'Spinach - 35g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 86, proteinGrams: 8, fatGrams: 5.6, carbsGrams: 1.9, fiberGrams: 0.8,
    ironMg: 2.12, calciumMg: 76, vitaminCmg: 3.4, vitaminAmcg: 263, vitaminDmcg: 1,
    vitaminKmcg: 172.6, vitaminB12mcg: 0.65, folateMcg: 75, zincMg: 0.65, potassiumMg: 163, magnesiumMg: 30, phosphorusMg: 99,
    allergens: ['egg'],
    blwNoteKa: 'ომლეტი პატარა ნაჭრებად დაჭერით ხელით კვებისთვის.',
    blwNoteEn: 'Cut omelette into small pieces for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or process in a blender.',
  },
  {
    titleKa: 'მოცვის შვრიის ბლინები',
    titleEn: 'Blueberry Oat Pancakes',
    descriptionKa: 'კვერცხი, შვრიის ფქვილი და მოცვი შეურიეთ. პატარა ბლინები გამოაცხვეთ. მიეცით ახლადმომზადებული. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Mix egg, oat flour and blueberries. Cook small pancakes. Serve freshly made. Prepare with age-appropriate texture.',
    ingredientsKa: ['მოცვი - 35 გ', 'კვერცხი - 1 ცალი', 'შვრიის ფქვილი - 25 გ'],
    ingredientsEn: ['Blueberry - 35g', 'Egg - 1', 'Oat flour - 25g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 198, proteinGrams: 10, fatGrams: 7.9, carbsGrams: 22.1, fiberGrams: 2.5,
    ironMg: 2, calciumMg: 28, vitaminCmg: 3.4, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminKmcg: 6.8, vitaminB12mcg: 0.65, folateMcg: 32, zincMg: 1.45, potassiumMg: 27, magnesiumMg: 36, phosphorusMg: 207,
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'პანკეიქი პატარა ნაჭრებად — ბავშვი ხელით ადვილად მოიჭერს.',
    blwNoteEn: 'Cut pancake into small pieces — easy for baby to self-feed.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ოდნავ გამდელეთ.',
    pureeNoteEn: 'Mash with fork or soften slightly.',
  },
  {
    titleKa: 'კვერცხი ავოკადოთი',
    titleEn: 'Egg with Avocado',
    descriptionKa: 'კვერცხი მოამზადეთ მოჩლუნგებულ სახით ან რბილი ყვითლით. ავოკადო დაჭყლიტეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით და მიირთვით ახლადმომზადებული.',
    descriptionEn: 'Cook egg scrambled or with soft yolk. Mash avocado. Prepare with age-appropriate texture and serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ავოკადო - 35 გ'],
    ingredientsEn: ['Egg - 1', 'Avocado - 35g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 134, proteinGrams: 7, fatGrams: 10.6, carbsGrams: 3.5, fiberGrams: 2.3,
    ironMg: 0.88, calciumMg: 28, vitaminCmg: 3.5, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminEmg: 0.72, vitaminKmcg: 7.4, vitaminB6mg: 0.09, vitaminB12mcg: 0.65,
    folateMcg: 52, zincMg: 0.65, potassiumMg: 170, magnesiumMg: 10, phosphorusMg: 99,
    allergens: ['egg'],
    blwNoteKa: 'ავოკადოს ნაჭრები და კვერცხის ნაჭრები ცალ-ცალკე შესთავაზეთ ხელით კვებისთვის.',
    blwNoteEn: 'Offer avocado pieces and egg pieces separately for self-feeding.',
    pureeNoteKa: 'კვერცხი და ავოკადო ჩანგლით ერთად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash egg and avocado together with a fork.',
  },
  {
    titleKa: 'ხაჭო ბანანით',
    titleEn: 'Cottage Cheese with Banana',
    descriptionKa: 'ბანანი დაჭყლიტეთ ჩანგლით. ხაჭო ბანანს შეურიეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით და მიირთვით ახლადმომზადებული.',
    descriptionEn: 'Mash banana with fork. Mix cottage cheese with banana. Prepare with age-appropriate texture and serve freshly made.',
    ingredientsKa: ['ხაჭო - 70 გ', 'ბანანი - 45 გ'],
    ingredientsEn: ['Cottage cheese - 70g', 'Banana - 45g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 99, proteinGrams: 8, fatGrams: 1.7, carbsGrams: 12.6, fiberGrams: 1.2,
    ironMg: 0.12, calciumMg: 58, vitaminCmg: 3.9, vitaminB6mg: 0.18, vitaminB12mcg: 0.3,
    folateMcg: 9, potassiumMg: 234, magnesiumMg: 12, phosphorusMg: 106, sodiumMg: 255,
    allergens: ['dairy'],
    blwNoteKa: 'ხაჭო-ბანანის ნარევი სქელი კოვზზე შესთავაზეთ.',
    blwNoteEn: 'Offer the thick cottage cheese and banana mix on a spoon.',
    pureeNoteKa: 'ბლენდერით დამუშავეთ სრულ გლუვობამდე.',
    pureeNoteEn: 'Process in blender until completely smooth.',
  },
  {
    titleKa: 'ბანანის შვრიის მაფინები',
    titleEn: 'Banana Oat Muffins',
    descriptionKa: 'შვრიის ფქვილი, კვერცხი და ბანანი შეურიეთ. ფორმებში ჩაასხით. 180°C-ზე გამოაცხვეთ 15-18 წუთი. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Mix oat flour, egg and banana. Pour into muffin forms. Bake at 180°C for 15-18 minutes. Prepare with age-appropriate texture.',
    ingredientsKa: ['შვრიის ფქვილი - 55 გ', 'კვერცხი - 1 ცალი', 'ბანანი - 1 მწიფე (60 გ)'],
    ingredientsEn: ['Oat flour - 55g', 'Egg - 1', 'Banana - 1 ripe (60g)'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 353, proteinGrams: 15, fatGrams: 10.7, carbsGrams: 50.5, fiberGrams: 5.1,
    ironMg: 3.51, calciumMg: 28, vitaminCmg: 5.2, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminB6mg: 0.24, vitaminB12mcg: 0.65, folateMcg: 53, zincMg: 2.41, potassiumMg: 215, magnesiumMg: 95, phosphorusMg: 336,
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'მაფინი ბავშვის ხელში ხვდება — მარტივია ხელით კვებისთვის.',
    blwNoteEn: 'Muffin fits in baby\'s hand — easy for self-feeding.',
    pureeNoteKa: 'მაფინი ჩანგლით დაჭყლიტეთ ან ოდნავ გამდელეთ.',
    pureeNoteEn: 'Mash muffin with fork or soften slightly.',
  },
  {
    titleKa: 'გოგრის შვრიის ბლინები',
    titleEn: 'Pumpkin Oat Pancakes',
    descriptionKa: 'გოგრა ორთქლზე მოხარშეთ და დაჭყლიტეთ. კვერცხი და შვრიის ფქვილი შეურიეთ. პატარა ბლინები გამოაცხვეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Steam pumpkin and mash. Mix in egg and oat flour. Cook small pancakes. Prepare with age-appropriate texture.',
    ingredientsKa: ['გოგრა - 65 გ', 'კვერცხი - 1 ცალი', 'შვრიის ფქვილი - 25 გ'],
    ingredientsEn: ['Pumpkin - 65g', 'Egg - 1', 'Oat flour - 25g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 192, proteinGrams: 11, fatGrams: 7.8, carbsGrams: 20.2, fiberGrams: 2.3,
    ironMg: 2, calciumMg: 28, vitaminCmg: 3.1, vitaminAmcg: 443, vitaminDmcg: 1,
    vitaminB12mcg: 0.65, folateMcg: 32, zincMg: 1.45, potassiumMg: 150, magnesiumMg: 36, phosphorusMg: 207,
    allergens: ['egg', 'gluten'],
    blwNoteKa: 'პატარა, ნარინჯისფერი ბლინები ბავშვისთვის ვიზუალურადაც საინტერესოა.',
    blwNoteEn: 'Small orange pancakes are visually interesting for baby too.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დამუშავეთ.',
    pureeNoteEn: 'Mash with fork or process in blender.',
  },
  {
    titleKa: 'იოგურტი მარწყვით',
    titleEn: 'Yogurt with Strawberry',
    descriptionKa: 'მარწყვი ჩანგლით დაჭყლიტეთ ან ბლენდერით დამუშავეთ. ბუნებრივ იოგურტს შეურიეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით და მიირთვით ახლადმომზადებული.',
    descriptionEn: 'Mash strawberries with fork or blend. Mix into natural yogurt. Prepare with age-appropriate texture and serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 70 გ', 'მარწყვი - 35 გ'],
    ingredientsEn: ['Natural yogurt - 70g', 'Strawberry - 35g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 54, proteinGrams: 3, fatGrams: 2.4, carbsGrams: 6, fiberGrams: 0.7,
    calciumMg: 85, vitaminCmg: 20.6, vitaminB12mcg: 0.35, folateMcg: 8, potassiumMg: 162, phosphorusMg: 67,
    allergens: ['dairy', 'strawberry'],
    blwNoteKa: 'იოგურტი კოვზზე შესთავაზეთ; მარწყვის პატარა ნაჭრებიც შეიძლება ცალკე.',
    blwNoteEn: 'Offer yogurt on spoon; small strawberry pieces can be offered separately.',
    pureeNoteKa: 'ბლენდერით გლუვ მასად დამუშავეთ.',
    pureeNoteEn: 'Process in blender until smooth.',
  },
  {
    titleKa: 'ბოსტნეულის კვერცხის მაფინი',
    titleEn: 'Vegetable Egg Muffin',
    descriptionKa: 'სტაფილო და ყაბაყი გაატარეთ სახეხელაზე. კვერცხი ავურიეთ ბოსტნეულთან. ფორმებში ჩაასხით და 180°C-ზე 15 წუთი გამოაცხვეთ. მოამზადეთ ასაკის შესაბამისი ტექსტურით.',
    descriptionEn: 'Grate carrot and zucchini. Beat egg with vegetables. Pour into forms and bake at 180°C for 15 minutes. Prepare with age-appropriate texture.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'სტაფილო - 25 გ', 'ყაბაყი - 25 გ'],
    ingredientsEn: ['Egg - 1', 'Carrot - 25g', 'Zucchini - 25g'],
    ageGroups: ['FROM_9'],
    mealType: 'BREAKFAST',
    calories: 91, proteinGrams: 7, fatGrams: 5.6, carbsGrams: 3.4, fiberGrams: 1,
    ironMg: 0.88, calciumMg: 28, vitaminCmg: 1.9, vitaminAmcg: 296, vitaminDmcg: 1,
    vitaminKmcg: 2.2, vitaminB12mcg: 0.65, folateMcg: 29, zincMg: 0.65, potassiumMg: 124, phosphorusMg: 99,
    allergens: ['egg'],
    blwNoteKa: 'პატარა მაფინი ბავშვი ხელით იჭერს — ხელით კვებისთვის იდეალურია.',
    blwNoteEn: 'Small muffin baby can grip — ideal for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დამუშავეთ.',
    pureeNoteEn: 'Mash with fork or process in blender.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 12-18 MONTHS (FROM_12) — standard toddler breakfasts (egg dishes, oatmeal,
  // pancakes, yogurt parfaits)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ფრანგული ტოსტი',
    titleEn: 'French Toast',
    descriptionKa: 'კვერცხი ავურიეთ. მთლიანი მარცვლის პური ჩაასველეთ კვერცხში. ტეფლონის ტაფაზე ორივე მხრიდან გამოაცხვეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Beat egg. Soak whole grain bread in egg. Cook on non-stick pan on both sides. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'მთლიანი მარცვლის პური - 1-2 ნაჭერი (60 გ)'],
    ingredientsEn: ['Egg - 1', 'Whole grain bread - 1-2 slices (60g)'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 226, proteinGrams: 14, fatGrams: 7.5, carbsGrams: 25.2, fiberGrams: 4.1,
    ironMg: 2.38, calciumMg: 28, vitaminAmcg: 80, vitaminDmcg: 1, vitaminB6mg: 0.11,
    vitaminB12mcg: 0.65, folateMcg: 48, zincMg: 0.65, magnesiumMg: 49, phosphorusMg: 99,
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'ჩიას პუდინგი ბანანით',
    titleEn: 'Chia Pudding with Banana',
    descriptionKa: 'ჩიას თესლი რძეში ჩაყარეთ, ავურიეთ და 15-20 წუთი ან ღამე დაისვენეთ. ბანანის ნაჭრები დაუმატეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Add chia seeds to milk, stir and rest for 15-20 minutes or overnight. Add banana pieces. Serve freshly made.',
    ingredientsKa: ['ჩიას თესლი - 10 გ', 'რძე - 100 მლ', 'ბანანი - 30 გ'],
    ingredientsEn: ['Chia seeds - 10g', 'Milk - 100ml', 'Banana - 30g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 136, proteinGrams: 5, fatGrams: 6.5, carbsGrams: 15.9, fiberGrams: 4.2,
    ironMg: 0.85, calciumMg: 176, vitaminCmg: 2.6, vitaminDmcg: 1.3, vitaminB6mg: 0.12,
    vitaminB12mcg: 0.45, folateMcg: 6, zincMg: 0.46, potassiumMg: 280, magnesiumMg: 42, phosphorusMg: 170, omega3Mg: 1780,
    allergens: ['dairy'],
  },
  {
    titleKa: 'ავოკადოს ტოსტი კვერცხით',
    titleEn: 'Avocado Toast with Egg',
    descriptionKa: 'პური შეწვით. ავოკადო დაჭყლიტეთ და პურს წაუსვით. კვერცხი მოჩლუნგებულ ან რბილი ყვითლით მოხარშეთ. ტოსტზე დადეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Toast bread. Mash avocado and spread on toast. Cook egg scrambled or with soft yolk. Place on toast. Serve freshly made.',
    ingredientsKa: ['ავოკადო - 40 გ', 'კვერცხი - 1 ცალი', 'მთლიანი მარცვლის პური - 1 ნაჭერი (30 გ)'],
    ingredientsEn: ['Avocado - 40g', 'Egg - 1', 'Whole grain bread - 1 slice (30g)'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 216, proteinGrams: 11, fatGrams: 12.4, carbsGrams: 16.3, fiberGrams: 4.7,
    ironMg: 1.63, calciumMg: 28, vitaminCmg: 4, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminEmg: 0.83, vitaminKmcg: 8.4, vitaminB6mg: 0.16, vitaminB12mcg: 0.65,
    folateMcg: 68, zincMg: 0.65, potassiumMg: 194, magnesiumMg: 36, phosphorusMg: 99,
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'შვრიის ვაფლები',
    titleEn: 'Oat Waffles',
    descriptionKa: 'შვრიის ფქვილი, კვერცხი და რძე შეურიეთ. ვაფლის ფორმაში გამოაცხვეთ. მიეცით ახლადმომზადებული ხილის კომპოტთან ან ბუნებრივ იოგურტთან ერთად.',
    descriptionEn: 'Mix oat flour, egg and milk. Bake in waffle maker. Serve freshly made with fruit compote or natural yogurt.',
    ingredientsKa: ['შვრიის ფქვილი - 65 გ', 'კვერცხი - 1 ცალი', 'რძე - 30 მლ'],
    ingredientsEn: ['Oat flour - 65g', 'Egg - 1', 'Milk - 30ml'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 358, proteinGrams: 17, fatGrams: 12.4, carbsGrams: 44.9, fiberGrams: 4.2,
    ironMg: 3.8, calciumMg: 62, vitaminAmcg: 80, vitaminDmcg: 1.4, vitaminB12mcg: 0.78,
    folateMcg: 44, zincMg: 2.73, potassiumMg: 40, magnesiumMg: 94, phosphorusMg: 404,
    allergens: ['egg', 'gluten', 'dairy'],
  },
  {
    titleKa: 'ყველისა და ისპანახის ომლეტი',
    titleEn: 'Cheese and Spinach Omelette',
    descriptionKa: 'ისპანახი ოდნავ შეაცხვეთ. კვერცხი ავურიეთ და გამოაცხვეთ. ომლეტზე ყველი დაყარეთ. გააკეცეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Lightly sauté spinach. Beat egg and cook. Add cheese on omelette. Fold. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 2 ცალი', 'ყველი - 18 გ', 'ისპანახი - 25 გ'],
    ingredientsEn: ['Egg - 2', 'Cheese - 18g', 'Spinach - 25g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 233, proteinGrams: 18, fatGrams: 17, carbsGrams: 2.3, fiberGrams: 0.6,
    ironMg: 2.64, calciumMg: 220, vitaminCmg: 2.5, vitaminAmcg: 339, vitaminDmcg: 2,
    vitaminKmcg: 123.3, vitaminB12mcg: 1.44, folateMcg: 84, zincMg: 1.86,
    potassiumMg: 117, magnesiumMg: 22, phosphorusMg: 290, sodiumMg: 112,
    allergens: ['egg', 'dairy'],
  },
  {
    titleKa: 'მარწყვის იოგურტ ბოული',
    titleEn: 'Strawberry Yogurt Bowl',
    descriptionKa: 'მარწყვი ჩანგლით ან ბლენდერით დამუშავეთ. ბუნებრივ იოგურტს შეურიეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Process strawberries with fork or blender. Mix into natural yogurt. Serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 110 გ', 'მარწყვი - 45 გ'],
    ingredientsEn: ['Natural yogurt - 110g', 'Strawberry - 45g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 82, proteinGrams: 4, fatGrams: 3.8, carbsGrams: 8.6, fiberGrams: 0.9,
    calciumMg: 133, vitaminCmg: 26.5, vitaminB12mcg: 0.55, folateMcg: 11, potassiumMg: 239, phosphorusMg: 105,
    allergens: ['dairy', 'strawberry'],
  },
  {
    titleKa: 'მოცვისა და ბანანის მაფინები',
    titleEn: 'Blueberry Banana Oat Muffins',
    descriptionKa: 'შვრიის ფქვილი, ბანანი, კვერცხი და მოცვი შეურიეთ. ფორმებში ჩაასხით. 180°C-ზე 18-20 წუთი გამოაცხვეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Mix oat flour, banana, egg and blueberries. Pour into forms. Bake at 180°C for 18-20 minutes. Serve freshly made.',
    ingredientsKa: ['მოცვი - 45 გ', 'შვრიის ფქვილი - 65 გ', 'ბანანი - 1 მწიფე (50 გ)'],
    ingredientsEn: ['Blueberry - 45g', 'Oat flour - 65g', 'Banana - 1 ripe (50g)'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 333, proteinGrams: 10, fatGrams: 6.2, carbsGrams: 60.8, fiberGrams: 6.6,
    ironMg: 3.06, vitaminCmg: 8.7, vitaminKmcg: 8.7, vitaminB6mg: 0.2, folateMcg: 31,
    zincMg: 2.08, potassiumMg: 214, magnesiumMg: 107, phosphorusMg: 280,
    allergens: ['gluten'],
  },
  {
    titleKa: 'ბანანის ენერგეტიკული ბოული',
    titleEn: 'Banana Yogurt Oat Bowl',
    descriptionKa: 'შვრია მოხარშეთ. ბანანი დაჭყლიტეთ. ბუნებრივი იოგურტი შეუმატეთ. შეურიეთ და მიეცით ახლადმომზადებული.',
    descriptionEn: 'Cook oats. Mash banana. Add natural yogurt. Mix and serve freshly made.',
    ingredientsKa: ['ბანანი - 1 ცალი (60 გ)', 'ბუნებრივი იოგურტი - 45 გ', 'შვრიის ფანტელი - 35 გ'],
    ingredientsEn: ['Banana - 1 (60g)', 'Natural yogurt - 45g', 'Oats - 35g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 217, proteinGrams: 8, fatGrams: 4.1, carbsGrams: 39, fiberGrams: 5.3,
    ironMg: 1.8, calciumMg: 73, vitaminCmg: 5.2, vitaminEmg: 0.25, vitaminB6mg: 0.28,
    vitaminB12mcg: 0.23, folateMcg: 32, zincMg: 1.4, potassiumMg: 435, magnesiumMg: 78, phosphorusMg: 226,
    allergens: ['dairy', 'gluten'],
  },
  {
    titleKa: 'წიწიბურას პანკეიქები',
    titleEn: 'Buckwheat Pancakes',
    descriptionKa: 'წიწიბურას ფქვილი კვერცხთან შეურიეთ. ოდნავ ზეთთან ერთად გამოაცხვეთ. პატარა, მრგვალი პანკეიქები გაკეთეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Mix buckwheat flour with egg. Cook with minimal oil. Make small round pancakes. Serve freshly made.',
    ingredientsKa: ['წიწიბურას ფქვილი - 65 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Buckwheat flour - 65g', 'Egg - 1'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 295, proteinGrams: 15, fatGrams: 7.5, carbsGrams: 47, fiberGrams: 6.5,
    ironMg: 3.54, calciumMg: 28, vitaminAmcg: 80, vitaminDmcg: 1, vitaminB12mcg: 0.65,
    folateMcg: 43, zincMg: 2.02, potassiumMg: 208, magnesiumMg: 163, phosphorusMg: 325,
    allergens: ['egg'],
  },
  {
    titleKa: 'რკინით მდიდარი საუზმე',
    titleEn: 'Iron-Rich Breakfast Plate',
    descriptionKa: 'კვერცხი მოჩლუნგებულ ან რბილი ყვითლით მოხარშეთ. ისპანახი ოდნავ შეაცხვეთ. ავოკადო დაჭყლიტეთ. ყველა ერთ თეფშზე დაწყვეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Cook egg scrambled or with soft yolk. Lightly sauté spinach. Mash avocado. Plate everything together. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ისპანახი - 25 გ', 'ავოკადო - 40 გ'],
    ingredientsEn: ['Egg - 1', 'Spinach - 25g', 'Avocado - 40g'],
    ageGroups: ['FROM_12'],
    mealType: 'BREAKFAST',
    calories: 147, proteinGrams: 8, fatGrams: 11.4, carbsGrams: 4.9, fiberGrams: 3.3,
    ironMg: 1.77, calciumMg: 62, vitaminCmg: 6.5, vitaminAmcg: 211, vitaminDmcg: 1,
    vitaminEmg: 0.83, vitaminKmcg: 131.7, vitaminB6mg: 0.1, vitaminB12mcg: 0.65,
    folateMcg: 92, zincMg: 0.65, potassiumMg: 311, magnesiumMg: 33, phosphorusMg: 99,
    allergens: ['egg'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 18-36 MONTHS (FROM_24) — family-style breakfasts (egg dishes, waffles,
  // muffins, yogurt parfaits)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ბოსტნეულის ომლეტი',
    titleEn: 'Vegetable Omelette',
    descriptionKa: 'ბროკოლი და სტაფილო მოხარშეთ და წვრილად დაჭერით. კვერცხი ავურიეთ. ომლეტი გამოაცხვეთ ბოსტნეულით. მიეცით უსაფრთხო ზომის ნაჭრებად.',
    descriptionEn: 'Cook and finely chop broccoli and carrot. Beat egg. Cook omelette with vegetables. Serve in safe-sized pieces.',
    ingredientsKa: ['კვერცხი - 2 ცალი', 'ბროკოლი - 35 გ', 'სტაფილო - 25 გ'],
    ingredientsEn: ['Egg - 2', 'Broccoli - 35g', 'Carrot - 25g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 176, proteinGrams: 14, fatGrams: 11.2, carbsGrams: 5.7, fiberGrams: 1.9,
    ironMg: 2.01, calciumMg: 70, vitaminCmg: 23.5, vitaminAmcg: 384, vitaminDmcg: 2,
    vitaminKmcg: 51.5, vitaminB12mcg: 1.29, folateMcg: 85, zincMg: 1.3, potassiumMg: 161, phosphorusMg: 198,
    allergens: ['egg'],
  },
  {
    titleKa: 'შვრიის ვაფლები ხილით',
    titleEn: 'Oat Waffles with Fruit',
    descriptionKa: 'შვრიის ფქვილი და კვერცხი შეურიეთ. ვაფლის ფორმაში გამოაცხვეთ. ბანანის ნაჭრები ზემოდან დაუმატეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Mix oat flour and egg. Bake in waffle maker. Top with banana slices. Serve freshly made.',
    ingredientsKa: ['შვრიის ფქვილი - 75 გ', 'ბანანი - 55 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Oat flour - 75g', 'Banana - 55g', 'Egg - 1'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 429, proteinGrams: 18, fatGrams: 12.5, carbsGrams: 62.6, fiberGrams: 6.3,
    ironMg: 4.39, calciumMg: 28, vitaminCmg: 4.8, vitaminAmcg: 80, vitaminDmcg: 1,
    vitaminB6mg: 0.22, vitaminB12mcg: 0.65, folateMcg: 59, zincMg: 3.05, potassiumMg: 197, magnesiumMg: 123, phosphorusMg: 422,
    allergens: ['egg', 'gluten'],
  },
  {
    titleKa: 'არაქისის კარაქის ტოსტი',
    titleEn: 'Peanut Butter Toast',
    descriptionKa: 'პური შეწვით. არაქისის კარაქი თხელი ფენით წაუსვით. მიეცით უსაფრთხო ზომის ნაჭრებად. არაქისი ერთ-ერთი მთავარი ალერგენია — თუ ბავშვს პირველად აძლევთ, სცადეთ მცირე რაოდენობით.',
    descriptionEn: 'Toast bread. Spread thin layer of peanut butter. Serve in safe-sized pieces. Peanut is a major allergen — if trying for the first time, offer a small amount.',
    ingredientsKa: ['ტოსტის პური - 1 ნაჭერი (30 გ)', 'არაქისის კარაქი - 1 ჩ/კ (8 გ)'],
    ingredientsEn: ['Toast bread - 1 slice (30g)', 'Peanut butter - 1 tsp (8g)'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 127, proteinGrams: 5, fatGrams: 5, carbsGrams: 16.3, fiberGrams: 1.3,
    ironMg: 1.08, vitaminEmg: 0.72, folateMcg: 44, zincMg: 0.23, potassiumMg: 52, magnesiumMg: 13,
    allergens: ['gluten', 'peanut'],
  },
  {
    titleKa: 'ხაჭოს ბლინები',
    titleEn: 'Cottage Cheese Pancakes',
    descriptionKa: 'ხაჭო, კვერცხი და ოდნავ ფქვილი შეურიეთ. პატარა ბლინები გამოაცხვეთ. მიეცით ახლადმომზადებული ხილის კომპოტთან ან ბუნებრივ იოგურტთან ერთად.',
    descriptionEn: 'Mix cottage cheese, egg and a little flour. Cook small pancakes. Serve freshly made with fruit compote or natural yogurt.',
    ingredientsKa: ['ხაჭო - 90 გ', 'კვერცხი - 1 ცალი', 'ფქვილი - 25 გ'],
    ingredientsEn: ['Cottage cheese - 90g', 'Egg - 1', 'Flour - 25g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 244, proteinGrams: 19, fatGrams: 7.8, carbsGrams: 22.7, fiberGrams: 0.7,
    ironMg: 2.03, calciumMg: 103, vitaminAmcg: 80, vitaminDmcg: 1, vitaminB12mcg: 1.03,
    folateMcg: 69, zincMg: 0.65, potassiumMg: 94, magnesiumMg: 6, phosphorusMg: 236, sodiumMg: 328,
    allergens: ['dairy', 'egg', 'gluten'],
  },
  {
    titleKa: 'კვერცხისა და ყველის სენდვიჩი',
    titleEn: 'Egg and Cheese Sandwich',
    descriptionKa: 'კვერცხი მოჩლუნგებულ სახით მოხარშეთ. ყველი პურზე დადეთ. კვერცხი ზემოდან. პური ჩაჭერით სამკუთხა ნაჭრებად. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Cook egg scrambled. Place cheese on bread. Add egg on top. Cut bread into triangle pieces. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ყველი - 25 გ', 'მთლიანი მარცვლის პური - 2 ნაჭერი (60 გ)'],
    ingredientsEn: ['Egg - 1', 'Cheese - 25g', 'Whole grain bread - 2 slices (60g)'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 326, proteinGrams: 21, fatGrams: 15.8, carbsGrams: 25.5, fiberGrams: 4.1,
    ironMg: 2.38, calciumMg: 208, vitaminAmcg: 146, vitaminDmcg: 1, vitaminB6mg: 0.11,
    vitaminB12mcg: 0.85, folateMcg: 48, zincMg: 1.43, magnesiumMg: 49, phosphorusMg: 227, sodiumMg: 155,
    allergens: ['egg', 'dairy', 'gluten'],
  },
  {
    titleKa: 'ბანანისა და მოცვის მაფინები',
    titleEn: 'Banana Blueberry Oat Muffins',
    descriptionKa: 'ბანანი დაჭყლიტეთ. შვრიის ფქვილი, ბანანი და მოცვი შეურიეთ. ფორმებში ჩაასხით. 180°C-ზე 18-20 წუთი გამოაცხვეთ.',
    descriptionEn: 'Mash banana. Mix oat flour, banana and blueberries. Pour into forms. Bake at 180°C for 18-20 minutes.',
    ingredientsKa: ['ბანანი - 1 მწიფე (60 გ)', 'მოცვი - 55 გ', 'შვრიის ფქვილი - 65 გ'],
    ingredientsEn: ['Banana - 1 ripe (60g)', 'Blueberry - 55g', 'Oat flour - 65g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 347, proteinGrams: 11, fatGrams: 6.3, carbsGrams: 64.6, fiberGrams: 7.1,
    ironMg: 3.08, vitaminCmg: 10.6, vitaminKmcg: 10.6, vitaminB6mg: 0.24, folateMcg: 33,
    zincMg: 2.08, potassiumMg: 257, magnesiumMg: 110, phosphorusMg: 280,
    allergens: ['gluten'],
  },
  {
    titleKa: 'იოგურტის გრანოლა ბოული',
    titleEn: 'Yogurt Granola Bowl',
    descriptionKa: 'ბუნებრივი იოგურტი თასში ჩაასხით. გრანოლა ზემოდან დაუმატეთ. მარწყვი ზემოდან. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Pour natural yogurt into bowl. Add granola on top. Top with strawberries. Serve freshly made.',
    ingredientsKa: ['ბუნებრივი იოგურტი - 110 გ', 'გრანოლა - 25 გ', 'მარწყვი - 45 გ'],
    ingredientsEn: ['Natural yogurt - 110g', 'Granola - 25g', 'Strawberry - 45g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 199, proteinGrams: 7, fatGrams: 8.8, carbsGrams: 24.6, fiberGrams: 2.7,
    ironMg: 0.63, calciumMg: 133, vitaminCmg: 26.5, vitaminB12mcg: 0.55, folateMcg: 11,
    potassiumMg: 239, magnesiumMg: 33, phosphorusMg: 105,
    allergens: ['dairy', 'gluten'],
  },
  {
    titleKa: 'საბავშვო შაქშუქა',
    titleEn: 'Baby Shakshuka',
    descriptionKa: 'ბულგარული წიწაკა და პომიდორი წვრილად დაჭერით. ზეთში შეაცხვეთ 5 წუთი. კვერცხი ჩასხით ზემოდან. დააფარეთ სახურავი და 3-4 წუთი მოხარშეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Finely chop bell pepper and tomato. Sauté in oil for 5 minutes. Add egg on top. Cover and cook for 3-4 minutes. Serve freshly made.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'პომიდორი - 45 გ', 'ბულგარული წიწაკა - 35 გ'],
    ingredientsEn: ['Egg - 1', 'Tomato - 45g', 'Bell pepper - 35g'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 96, proteinGrams: 7, fatGrams: 5.7, carbsGrams: 4.4, fiberGrams: 1.3,
    ironMg: 0.88, calciumMg: 28, vitaminCmg: 50.9, vitaminAmcg: 154, vitaminDmcg: 1,
    vitaminB6mg: 0.1, vitaminB12mcg: 0.65, folateMcg: 30, zincMg: 0.65, potassiumMg: 181, phosphorusMg: 99,
    allergens: ['egg', 'tomato'],
  },
  {
    titleKa: 'ისპანახისა და ყველის პანკეიქები',
    titleEn: 'Spinach and Cheese Pancakes',
    descriptionKa: 'ისპანახი ბლენდერით ან წვრილად დაჭერით. კვერცხი, ყველი და ისპანახი შეურიეთ. ბლინები გამოაცხვეთ. მიეცით ახლადმომზადებული.',
    descriptionEn: 'Blend or finely chop spinach. Mix egg, cheese and spinach. Cook pancakes. Serve freshly made.',
    ingredientsKa: ['ისპანახი - 35 გ', 'ყველი - 25 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Spinach - 35g', 'Cheese - 25g', 'Egg - 1'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 186, proteinGrams: 14, fatGrams: 13.8, carbsGrams: 2.2, fiberGrams: 0.8,
    ironMg: 2.12, calciumMg: 256, vitaminCmg: 3.4, vitaminAmcg: 330, vitaminDmcg: 1,
    vitaminKmcg: 172.6, vitaminB12mcg: 0.85, folateMcg: 75, zincMg: 1.43,
    potassiumMg: 163, magnesiumMg: 30, phosphorusMg: 227, sodiumMg: 155,
    allergens: ['dairy', 'egg'],
  },
  {
    titleKa: 'ენერგეტიკული საუზმის თეფში',
    titleEn: 'Energy Breakfast Plate',
    descriptionKa: 'კვერცხი მოჩლუნგებულ სახით მოხარშეთ. ავოკადო ნაჭრებად დაჭერით. ბანანი დაამატეთ. ტოსტი ნაჭრებად დაჭერით. ყველა ერთ თეფშზე მოაწყვეთ.',
    descriptionEn: 'Cook egg scrambled. Cut avocado into pieces. Add banana. Cut toast into pieces. Arrange everything on one plate.',
    ingredientsKa: ['კვერცხი - 1-2 ცალი (75 გ)', 'ავოკადო - 40 გ', 'ბანანი - 45 გ', 'მთლიანი მარცვლის ტოსტი - 1 ნაჭერი (30 გ)'],
    ingredientsEn: ['Egg - 1-2 (75g)', 'Avocado - 40g', 'Banana - 45g', 'Whole grain toast - 1 slice (30g)'],
    ageGroups: ['FROM_24'],
    mealType: 'BREAKFAST',
    calories: 294, proteinGrams: 15, fatGrams: 15.3, carbsGrams: 26.8, fiberGrams: 5.9,
    ironMg: 2.18, calciumMg: 42, vitaminCmg: 7.9, vitaminAmcg: 120, vitaminDmcg: 1.5,
    vitaminEmg: 0.83, vitaminKmcg: 8.4, vitaminB6mg: 0.34, vitaminB12mcg: 0.97,
    folateMcg: 89, zincMg: 0.98, potassiumMg: 355, magnesiumMg: 48, phosphorusMg: 149,
    allergens: ['egg', 'gluten'],
  },
];

async function main() {
  console.log('🌱 Seeding 40 breakfast recipes...');

  let created = 0;
  let skipped = 0;

  for (const r of recipes) {
    const existing = await prisma.dish.findFirst({
      where: { titleKa: r.titleKa, mealType: 'BREAKFAST', ageGroups: { equals: r.ageGroups as any } },
    });

    if (existing) {
      skipped++;
      console.log(`  ⏭  Already exists: ${r.titleKa}`);
      continue;
    }

    await prisma.dish.create({
      data: {
        titleKa: r.titleKa,
        titleEn: r.titleEn,
        descriptionKa: r.descriptionKa,
        descriptionEn: r.descriptionEn,
        ingredientsKa: r.ingredientsKa,
        ingredientsEn: r.ingredientsEn,
        ageGroups: r.ageGroups as any,
        mealType: r.mealType as any,
        allergens: r.allergens || [],
        calories: (r as any).calories ?? null,
        proteinGrams: (r as any).proteinGrams ?? null,
        fatGrams: (r as any).fatGrams ?? null,
        carbsGrams: (r as any).carbsGrams ?? null,
        fiberGrams: (r as any).fiberGrams ?? null,
        ironMg: (r as any).ironMg ?? null,
        calciumMg: (r as any).calciumMg ?? null,
        vitaminCmg: (r as any).vitaminCmg ?? null,
        vitaminAmcg: (r as any).vitaminAmcg ?? null,
        vitaminDmcg: (r as any).vitaminDmcg ?? null,
        vitaminEmg: (r as any).vitaminEmg ?? null,
        vitaminKmcg: (r as any).vitaminKmcg ?? null,
        vitaminB6mg: (r as any).vitaminB6mg ?? null,
        vitaminB12mcg: (r as any).vitaminB12mcg ?? null,
        folateMcg: (r as any).folateMcg ?? null,
        zincMg: (r as any).zincMg ?? null,
        potassiumMg: (r as any).potassiumMg ?? null,
        magnesiumMg: (r as any).magnesiumMg ?? null,
        phosphorusMg: (r as any).phosphorusMg ?? null,
        sodiumMg: (r as any).sodiumMg ?? null,
        omega3Mg: (r as any).omega3Mg ?? null,
        blwNoteKa: (r as any).blwNoteKa ?? null,
        blwNoteEn: (r as any).blwNoteEn ?? null,
        pureeNoteKa: (r as any).pureeNoteKa ?? null,
        pureeNoteEn: (r as any).pureeNoteEn ?? null,
      },
    });
    created++;
    console.log(`  ✓  ${r.titleKa}`);
  }

  console.log(`\n✅ Done: ${created} created, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
