import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Recipes below are original Georgian writing, built around common, widely-known
// infant/toddler feeding combinations (age-appropriate purees, finger foods, and family
// dishes) that appear across baby-feeding guidance worldwide and are not the copyrightable
// expression of any single source. Nutrient values are computed from a reusable per-100g
// reference table built from USDA FoodData Central figures (public domain / CC0).
const recipes = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 6-8 MONTHS (FROM_6) — LUNCH
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ქათამი და ტკბილი კარტოფილი',
    titleEn: 'Chicken and Sweet Potato',
    descriptionKa: 'ქათმის ფილე და ტკბილი კარტოფილი ორთქლზე ან წყალში მოხარშეთ სრულ დარბილებამდე. დააბლენდერეთ გლუვ პიურედ. გაათხელეთ საჭიროების შემთხვევაში მოხარშვის წყლით.',
    descriptionEn: 'Steam or boil chicken fillet and sweet potato until fully soft. Blend into a smooth puree. Thin with cooking water if needed.',
    ingredientsKa: ['ქათმის ფილე - 55 გ', 'ტკბილი კარტოფილი - 70 გ'],
    ingredientsEn: ['Chicken fillet - 55g', 'Sweet potato - 70g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 154, proteinGrams: 18, fatGrams: 2.1, carbsGrams: 14.5, fiberGrams: 2.3,
    ironMg: 0.98, calciumMg: 27, vitaminCmg: 13.7, vitaminAmcg: 673, vitaminB6mg: 0.53,
    vitaminB12mcg: 0.17, zincMg: 0.55, potassiumMg: 473, magnesiumMg: 19, phosphorusMg: 121,
    blwNoteKa: 'ქათმის ხორცი ბოჭკოებად დაშალეთ, ტკბილი კარტოფილი რბილ ზოლებად — ორივე ცალკე შეიძლება ხელით.',
    blwNoteEn: 'Shred chicken into fibers, cut sweet potato into soft strips — both can be offered separately by hand.',
    pureeNoteKa: 'ბლენდერით სრულად გლუვ მასად აქციეთ.',
    pureeNoteEn: 'Blend into a completely smooth puree.',
  },
  {
    titleKa: 'ქათამი და გოგრა',
    titleEn: 'Chicken and Pumpkin',
    descriptionKa: 'ქათმის ფილე და გოგრა ორთქლზე ან წყალში მოხარშეთ. დააბლენდერეთ ერთგვაროვან, გლუვ მასად. ასაკის შესაბამისი ტექსტურით მიეცით.',
    descriptionEn: 'Steam or boil chicken fillet and pumpkin. Blend into a smooth, uniform mass. Serve with age-appropriate texture.',
    ingredientsKa: ['ქათმის ფილე - 55 გ', 'გოგრა - 75 გ'],
    ingredientsEn: ['Chicken fillet - 55g', 'Pumpkin - 75g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 106, proteinGrams: 18, fatGrams: 2.1, carbsGrams: 3.7, fiberGrams: 0.8,
    ironMg: 0.5, vitaminCmg: 3.5, vitaminAmcg: 419, vitaminB6mg: 0.33,
    vitaminB12mcg: 0.17, zincMg: 0.55, potassiumMg: 313, phosphorusMg: 121,
    blwNoteKa: 'ქათმის ხორცი ბოჭკოებად, გოგრა რბილ კუბიკებად — ცალკე შესთავაზეთ.',
    blwNoteEn: 'Chicken shredded into fibers, pumpkin in soft cubes — offer separately.',
    pureeNoteKa: 'ბლენდერით ერთგვაროვან პიურედ აქციეთ.',
    pureeNoteEn: 'Blend into a uniform puree.',
  },
  {
    titleKa: 'ინდაური და სტაფილო',
    titleEn: 'Turkey and Carrot',
    descriptionKa: 'ინდაურის ხორცი და სტაფილო ორთქლზე ან წყალში მოხარშეთ. ბლენდერით გლუვ პიურედ აქციეთ. სტაფილო ინდაურს ბუნებრივ სიტკბოს მატებს.',
    descriptionEn: 'Steam or boil turkey meat and carrot. Blend into a smooth puree. Carrot adds natural sweetness to the turkey.',
    ingredientsKa: ['ინდაურის ხორცი - 55 გ', 'სტაფილო - 55 გ'],
    ingredientsEn: ['Turkey meat - 55g', 'Carrot - 55g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 94, proteinGrams: 17, fatGrams: 0.5, carbsGrams: 4.5, fiberGrams: 1.7,
    ironMg: 0.77, vitaminCmg: 1.7, vitaminAmcg: 469, vitaminKmcg: 4.7, vitaminB6mg: 0.28,
    vitaminB12mcg: 0.17, zincMg: 0.83, potassiumMg: 261, phosphorusMg: 118,
    blwNoteKa: 'ინდაური ბოჭკოებად დაშალეთ, სტაფილო რბილ ჩხირებად ორთქლზე დაარბილეთ.',
    blwNoteEn: 'Shred turkey into fibers, steam carrot into soft sticks.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ აქციეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'წითელი ოსპი ბოსტნეულით',
    titleEn: 'Red Lentils with Vegetables',
    descriptionKa: 'წითელი ოსპი კარგად გარეცხეთ. სტაფილო და ყაბაყი დაჭერით. ყველა ერთად წყალში მოხარშეთ 15-20 წუთი. ბლენდერით გლუვ სუპ-პიურედ დამუშავეთ.',
    descriptionEn: 'Rinse red lentils well. Chop carrot and zucchini. Cook everything in water for 15-20 minutes. Blend into a smooth soup-puree.',
    ingredientsKa: ['წითელი ოსპი, მოხარშული - 80 გ', 'სტაფილო - 40 გ', 'ყაბაყი - 40 გ'],
    ingredientsEn: ['Red lentils, cooked - 80g', 'Carrot - 40g', 'Zucchini - 40g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 114, proteinGrams: 8, fatGrams: 0.5, carbsGrams: 20.6, fiberGrams: 7.9,
    ironMg: 2.64, vitaminCmg: 3, vitaminAmcg: 345, vitaminKmcg: 3.4, folateMcg: 153,
    zincMg: 1.04, potassiumMg: 494, magnesiumMg: 29, phosphorusMg: 144,
    blwNoteKa: 'ოსპი ჩვეულებრივ ცალკე მარცვლებად რთული გასაკონტროლებელია — შესთავაზეთ სქელი მასა კოვზზე.',
    blwNoteEn: 'Lentils are hard to control loose, so offer the thick mixture pre-loaded on a spoon.',
    pureeNoteKa: 'ბლენდერით გლუვ სუპ-პიურედ აქციეთ.',
    pureeNoteEn: 'Blend into a smooth soup-puree.',
  },
  {
    titleKa: 'ბროკოლი და კარტოფილი',
    titleEn: 'Broccoli and Potato',
    descriptionKa: 'კარტოფილი გაფცქვენით და ბროკოლთან ერთად ორთქლზე მოხარშეთ. ბლენდერით გლუვ პიურედ დამუშავეთ. საჭიროების შემთხვევაში გაათხელეთ.',
    descriptionEn: 'Peel potato and steam with broccoli until soft. Blend into a smooth puree. Thin with water if needed.',
    ingredientsKa: ['ბროკოლი - 60 გ', 'კარტოფილი - 60 გ'],
    ingredientsEn: ['Broccoli - 60g', 'Potato - 60g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 73, proteinGrams: 3, fatGrams: 0.3, carbsGrams: 16.4, fiberGrams: 3.1,
    calciumMg: 24, vitaminCmg: 46.7, vitaminAmcg: 19, vitaminKmcg: 84.7, vitaminB6mg: 0.16,
    folateMcg: 65, potassiumMg: 403, magnesiumMg: 13,
    blwNoteKa: 'ბროკოლის რბილი ყვავილები და კარტოფილის რბილი ჩხირები ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer soft broccoli florets and soft potato sticks separately.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ დამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },
  {
    titleKa: 'ყაბაყი და ქათამი',
    titleEn: 'Zucchini and Chicken',
    descriptionKa: 'ქათმის ფილე და ყაბაყი ორთქლზე ან წყალში მოხარშეთ. ბლენდერით ერთგვაროვნად დამუშავეთ. მსუბუქი, ადვილად მოსანელებელი კომბინაციაა.',
    descriptionEn: 'Steam or boil chicken fillet and zucchini. Blend until uniform. A light, easily digestible combination.',
    ingredientsKa: ['ყაბაყი - 70 გ', 'ქათმის ფილე - 50 გ'],
    ingredientsEn: ['Zucchini - 70g', 'Chicken fillet - 50g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 94, proteinGrams: 16, fatGrams: 2, carbsGrams: 2.2, fiberGrams: 0.7,
    ironMg: 0.45, vitaminCmg: 3.2, vitaminAmcg: 7, vitaminB6mg: 0.3, vitaminB12mcg: 0.15,
    folateMcg: 15, zincMg: 0.5, potassiumMg: 311, phosphorusMg: 110,
    blwNoteKa: 'ქათამი ბოჭკოებად, ყაბაყი რბილ ჩხირებად — ორივე ცალკე ხელით.',
    blwNoteEn: 'Chicken in fibers, zucchini in soft sticks — both by hand separately.',
    pureeNoteKa: 'ბლენდერით ერთგვაროვნად დამუშავეთ.',
    pureeNoteEn: 'Blend until uniform.',
  },
  {
    titleKa: 'ყვავილოვანი კომბოსტო და კარტოფილი',
    titleEn: 'Cauliflower and Potato',
    descriptionKa: 'ყვავილოვანი კომბოსტო და კარტოფილი ორთქლზე მოხარშეთ. ბლენდერით გლუვ, კრემისებრ პიურედ დამუშავეთ. ზეითუნის ზეთის ერთი წვეთი შეგიძლიათ დაუმატოთ.',
    descriptionEn: 'Steam cauliflower and potato. Blend into a smooth, creamy puree. You can add a drop of olive oil.',
    ingredientsKa: ['ყვავილოვანი კომბოსტო - 70 გ', 'კარტოფილი - 60 გ'],
    ingredientsEn: ['Cauliflower - 70g', 'Potato - 60g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 68, proteinGrams: 2, fatGrams: 0.4, carbsGrams: 14.9, fiberGrams: 2.7,
    vitaminCmg: 38.8, vitaminKmcg: 10.9, vitaminB6mg: 0.16, folateMcg: 31,
    potassiumMg: 327, magnesiumMg: 13,
    blwNoteKa: 'ყვავილოვანი კომბოსტოს რბილი ყვავილები და კარტოფილის ჩხირები ცალკე შესთავაზეთ.',
    blwNoteEn: 'Offer soft cauliflower florets and potato sticks separately.',
    pureeNoteKa: 'ბლენდერით გლუვ, კრემისებრ პიურედ დამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth, creamy puree.',
  },
  {
    titleKa: 'საქონლის ხორცი და ტკბილი კარტოფილი',
    titleEn: 'Beef and Sweet Potato',
    descriptionKa: 'საქონლის ხორცი კარგად მოხარშეთ. ტკბილი კარტოფილი ორთქლზე მოამზადეთ. ერთად ბლენდერით გლუვ პიურედ დამუშავეთ. საჭიროების შემთხვევაში გაათხელეთ.',
    descriptionEn: 'Cook beef well. Steam sweet potato. Blend together into a smooth puree. Thin with water if needed.',
    ingredientsKa: ['საქონლის ხორცი, მჭლე - 55 გ', 'ტკბილი კარტოფილი - 70 გ'],
    ingredientsEn: ['Lean beef - 55g', 'Sweet potato - 70g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 164, proteinGrams: 18, fatGrams: 3.7, carbsGrams: 14.5, fiberGrams: 2.3,
    ironMg: 1.91, calciumMg: 27, vitaminCmg: 13.7, vitaminAmcg: 673, vitaminB6mg: 0.2,
    vitaminB12mcg: 1.43, zincMg: 2.97, potassiumMg: 520, magnesiumMg: 19, phosphorusMg: 132,
    blwNoteKa: 'საქონლის ხორცი ძალიან წვრილ ბოჭკოებად დაშალეთ (რთული ღეჭვისთვის), ტკბილი კარტოფილი რბილ ზოლებად.',
    blwNoteEn: 'Shred beef into very fine fibers (hard to chew otherwise), cut sweet potato into soft strips.',
    pureeNoteKa: 'ერთად ბლენდერით გლუვ პიურედ დამუშავეთ.',
    pureeNoteEn: 'Blend together into a smooth puree.',
  },
  {
    titleKa: 'ოსპი და სტაფილო',
    titleEn: 'Lentils and Carrot',
    descriptionKa: 'ოსპი გარეცხეთ და სტაფილოსთან ერთად წყალში მოხარშეთ. ბლენდერით გლუვ სუპ-პიურედ დამუშავეთ. რკინითა და ცილით მდიდარი კომბინაციაა.',
    descriptionEn: 'Rinse lentils and cook with carrot in water. Blend into a smooth soup-puree. Rich in iron and protein.',
    ingredientsKa: ['ოსპი, მოხარშული - 80 გ', 'სტაფილო - 60 გ'],
    ingredientsEn: ['Lentils, cooked - 80g', 'Carrot - 60g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 114, proteinGrams: 8, fatGrams: 0.4, carbsGrams: 21, fiberGrams: 8.1,
    ironMg: 2.64, vitaminCmg: 1.8, vitaminAmcg: 511, vitaminKmcg: 5.2, folateMcg: 145,
    zincMg: 1.04, potassiumMg: 436, magnesiumMg: 29, phosphorusMg: 144,
    blwNoteKa: 'შესთავაზეთ სქელი მასა კოვზზე, ცალკე ოსპი ადვილად იფანტება ხელში.',
    blwNoteEn: 'Offer the thick mixture pre-loaded on a spoon — loose lentils scatter in tiny hands.',
    pureeNoteKa: 'ბლენდერით გლუვ სუპ-პიურედ დამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth soup-puree.',
  },
  {
    titleKa: 'ქათამი და ბროკოლი',
    titleEn: 'Chicken and Broccoli',
    descriptionKa: 'ქათმის ფილე და ბროკოლი ორთქლზე ან წყალში მოხარშეთ. ბლენდერით გლუვ პიურედ დამუშავეთ. ვიტამინებით მდიდარი, დაბალანსებული სადილია.',
    descriptionEn: 'Steam or boil chicken fillet and broccoli. Blend into a smooth puree. A balanced, vitamin-rich lunch.',
    ingredientsKa: ['ქათმის ფილე - 55 გ', 'ბროკოლი - 60 გ'],
    ingredientsEn: ['Chicken fillet - 55g', 'Broccoli - 60g'],
    ageGroups: ['FROM_6'], mealType: 'LUNCH', allergens: [],
    calories: 112, proteinGrams: 18, fatGrams: 2.2, carbsGrams: 4.3, fiberGrams: 2,
    ironMg: 0.93, calciumMg: 24, vitaminCmg: 38.9, vitaminAmcg: 19, vitaminKmcg: 84.7,
    vitaminB6mg: 0.33, vitaminB12mcg: 0.17, folateMcg: 65, zincMg: 0.55, potassiumMg: 317, phosphorusMg: 121,
    blwNoteKa: 'ქათამი ბოჭკოებად დაშალეთ, ბროკოლის რბილი ყვავილები ცალკე შესთავაზეთ.',
    blwNoteEn: 'Shred chicken into fibers, offer soft broccoli florets separately.',
    pureeNoteKa: 'ბლენდერით გლუვ პიურედ დამუშავეთ.',
    pureeNoteEn: 'Blend into a smooth puree.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 9-11 MONTHS (FROM_9) — LUNCH
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ქათმის ხორცის ბურთულები',
    titleEn: 'Chicken Meatballs',
    descriptionKa: 'ქათმის ფილე და სტაფილო ბლენდერით დაამუშავეთ. პატარა ბურთულები ჩამოაყალიბეთ და ორთქლზე ან წყალში მოხარშეთ 15-20 წუთი. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Process chicken fillet and carrot in a blender. Shape into small balls and steam or boil for 15-20 minutes. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ქათმის ფილე - 75 გ', 'სტაფილო - 35 გ'],
    ingredientsEn: ['Chicken fillet - 75g', 'Carrot - 35g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 136, proteinGrams: 24, fatGrams: 2.8, carbsGrams: 2.9, fiberGrams: 1.1,
    ironMg: 0.68, vitaminCmg: 1.1, vitaminAmcg: 298, vitaminKmcg: 3, vitaminB6mg: 0.45,
    vitaminB12mcg: 0.23, zincMg: 0.75, potassiumMg: 274, phosphorusMg: 165,
    blwNoteKa: 'ბურთულები ცოტა გაბრტყელებული ფორმით გააკეთეთ, რომ ბავშვმა ხელით მარტივად აიღოს.',
    blwNoteEn: 'Shape balls slightly flattened so baby can grip them easily by hand.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით ოდნავ დაამსხვილეთ.',
    pureeNoteEn: 'Mash with a fork or lightly blend.',
  },
  {
    titleKa: 'ინდაურის კატლეტი',
    titleEn: 'Turkey Patty',
    descriptionKa: 'ინდაურის ხორცი და ყაბაყი ბლენდერით დაამუშავეთ. პატარა კატლეტები ჩამოაყალიბეთ. ზეთის მინიმალური რაოდენობით ან ორთქლზე მოხარშეთ. რბილი ტექსტურით მიეცით.',
    descriptionEn: 'Process turkey meat and zucchini in a blender. Shape into small patties. Cook with minimal oil or steam. Serve with soft texture.',
    ingredientsKa: ['ინდაური - 75 გ', 'ყაბაყი - 45 გ'],
    ingredientsEn: ['Turkey - 75g', 'Zucchini - 45g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 109, proteinGrams: 23, fatGrams: 0.7, carbsGrams: 1.4, fiberGrams: 0.5,
    ironMg: 1.05, vitaminCmg: 2.1, vitaminAmcg: 5, vitaminB6mg: 0.38, vitaminB12mcg: 0.23,
    folateMcg: 9, zincMg: 1.13, potassiumMg: 297, phosphorusMg: 161,
    blwNoteKa: 'კატლეტები თითის ზომის ჩამოაყალიბეთ ხელით აღების გასაადვილებლად.',
    blwNoteEn: 'Shape patties finger-sized to make gripping easier.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash with a fork.',
  },
  {
    titleKa: 'საქონლის ხორცი და წიწიბურა',
    titleEn: 'Beef and Buckwheat',
    descriptionKa: 'საქონლის ხორცი კარგად მოხარშეთ და წვრილად დაჭერით. წიწიბურა ცალკე მოხარშეთ სრულ დარბილებამდე. ერთად შეურიეთ. რბილი ტექსტურით მიეცით.',
    descriptionEn: 'Cook beef well and finely chop. Cook buckwheat separately until fully soft. Mix together. Serve with soft texture.',
    ingredientsKa: ['საქონლის ხორცი, მჭლე - 65 გ', 'წიწიბურა, მოხარშული - 90 გ'],
    ingredientsEn: ['Lean beef - 65g', 'Buckwheat, cooked - 90g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 202, proteinGrams: 23, fatGrams: 4.8, carbsGrams: 17.9, fiberGrams: 2.4,
    ironMg: 2.68, vitaminB12mcg: 1.69, folateMcg: 13, zincMg: 4.14, potassiumMg: 300,
    magnesiumMg: 46, phosphorusMg: 219,
    blwNoteKa: 'ხორცი ძალიან წვრილ ბოჭკოებად დაშალეთ, წიწიბურა სქელ გუნდებად ჩამოაყალიბეთ.',
    blwNoteEn: 'Shred beef into very fine fibers, shape buckwheat into thick soft clumps.',
    pureeNoteKa: 'ერთად ჩანგლით ან ბლენდერით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash or blend together.',
  },
  {
    titleKa: 'ორაგული და კარტოფილი',
    titleEn: 'Salmon and Potato',
    descriptionKa: 'ორაგული ორთქლზე მოხარშეთ და ეკლები ფრთხილად მოაშორეთ. კარტოფილი ორთქლზე მოხარშეთ. ჩანგლით ერთად დაჭყლიტეთ. ომეგა-3-ით მდიდარი სადილია.',
    descriptionEn: 'Steam salmon and carefully remove bones. Steam potato. Mash together with a fork. A lunch rich in omega-3.',
    ingredientsKa: ['ორაგული - 55 გ', 'კარტოფილი - 70 გ'],
    ingredientsEn: ['Salmon - 55g', 'Potato - 70g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: ['fish'],
    calories: 174, proteinGrams: 13, fatGrams: 6.9, carbsGrams: 14.1, fiberGrams: 1.3,
    vitaminCmg: 9.1, vitaminDmcg: 7.2, vitaminB6mg: 0.19, vitaminB12mcg: 1.54,
    potassiumMg: 477, magnesiumMg: 15, phosphorusMg: 132, omega3Mg: 1183,
    blwNoteKa: 'ორაგული დიდი, რბილი ნაჭრებით შესთავაზეთ (ეკლების გარეშე), კარტოფილი ჩხირებად.',
    blwNoteEn: 'Offer salmon in large, soft flakes (bone-free), potato in sticks.',
    pureeNoteKa: 'ჩანგლით ერთად კარგად დაჭყლიტეთ.',
    pureeNoteEn: 'Mash together well with a fork.',
  },
  {
    titleKa: 'ქათამი და მაკარონი',
    titleEn: 'Chicken and Pasta',
    descriptionKa: 'საბავშვო მაკარონი კარგად მოხარშეთ. ქათმის ფილე ორთქლზე მოხარშეთ და წვრილ ნაჭრებად დაჭერით. ერთად შეურიეთ. რბილ ტექსტურად მიეცით.',
    descriptionEn: 'Cook baby pasta well. Steam chicken fillet and cut into small pieces. Mix together. Serve with soft texture.',
    ingredientsKa: ['ქათმის ფილე - 65 გ', 'საბავშვო მაკარონი, მოხარშული - 90 გ'],
    ingredientsEn: ['Chicken fillet - 65g', 'Baby pasta, cooked - 90g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: ['gluten'],
    calories: 225, proteinGrams: 25, fatGrams: 3.3, carbsGrams: 22.5, fiberGrams: 1.6,
    ironMg: 1.4, vitaminB6mg: 0.39, vitaminB12mcg: 0.2, folateMcg: 18, zincMg: 0.65,
    potassiumMg: 166, magnesiumMg: 16, phosphorusMg: 143,
    blwNoteKa: 'მოხარშული მაკარონის დიდი ფორმები (მაგ. ფუზილი) ბავშვისთვის ხელით ადვილად საჭერია.',
    blwNoteEn: 'Large cooked pasta shapes (e.g. fusilli) are easy for baby to grip by hand.',
    pureeNoteKa: 'ერთად ჩანგლით ან ბლენდერით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash or blend together.',
  },
  {
    titleKa: 'ოსპის სუპი',
    titleEn: 'Lentil Soup',
    descriptionKa: 'წითელი ოსპი გარეცხეთ. ბოსტნეული (სტაფილო, ყაბაყი) დაჭერით. ყველა ერთად წყალში მოხარშეთ. ბლენდერით ან ჩანგლით ოდნავ დაჭყლიტეთ — ტექსტურა უნდა დარჩეს.',
    descriptionEn: 'Rinse red lentils. Chop vegetables (carrot, zucchini). Cook everything in water. Slightly blend or mash with fork — some texture should remain.',
    ingredientsKa: ['წითელი ოსპი, მოხარშული - 90 გ', 'ბოსტნეული (სტაფილო, ყაბაყი) - 80 გ'],
    ingredientsEn: ['Red lentils, cooked - 90g', 'Vegetables (carrot, zucchini) - 80g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 125, proteinGrams: 9, fatGrams: 0.6, carbsGrams: 22.6, fiberGrams: 8.7,
    ironMg: 2.97, vitaminCmg: 3, vitaminAmcg: 345, vitaminKmcg: 3.4, folateMcg: 171,
    zincMg: 1.17, potassiumMg: 531, magnesiumMg: 32, phosphorusMg: 162,
    blwNoteKa: 'დატოვეთ ოდნავ სქელი, ტექსტურიანი — კოვზზე წინასწარ დატვირთული შესთავაზეთ.',
    blwNoteEn: 'Leave slightly thick and textured — offer pre-loaded on a spoon.',
    pureeNoteKa: 'ბლენდერით უფრო გლუვ მასად აქციეთ.',
    pureeNoteEn: 'Blend into a smoother mass.',
  },
  {
    titleKa: 'ბოსტნეულის რიზოტო',
    titleEn: 'Vegetable Risotto',
    descriptionKa: 'ბრინჯი ბოსტნეულთან ერთად წყალში მოხარშეთ. ხშირ-ხშირად ურიეთ. ბრინჯი კარგად დარბილდება და კრემისებრ კონსისტენციას მიიღებს. ასაკის შესაბამისი ტექსტურით მიეცით.',
    descriptionEn: 'Cook rice with vegetables in water. Stir frequently. Rice softens well and develops a creamy consistency. Serve with age-appropriate texture.',
    ingredientsKa: ['ბრინჯი, მოხარშული - 100 გ', 'ბოსტნეული (სტაფილო, ყაბაყი, ბროკოლი) - 80 გ'],
    ingredientsEn: ['Rice, cooked - 100g', 'Vegetables (carrot, zucchini, broccoli) - 80g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 153, proteinGrams: 3, fatGrams: 0.5, carbsGrams: 33, fiberGrams: 2.3,
    ironMg: 0.35, calciumMg: 8, vitaminCmg: 15.3, vitaminAmcg: 265, vitaminKmcg: 30.8,
    folateMcg: 28, potassiumMg: 207, magnesiumMg: 12, phosphorusMg: 43,
    blwNoteKa: 'შესთავაზეთ სქელი, წებოვანი კონსისტენციით — ადვილად კვრებადია ხელისთვისაც.',
    blwNoteEn: 'Serve with a thick, sticky consistency — it clumps easily for little hands too.',
    pureeNoteKa: 'ბლენდერით საჭირო ტექსტურამდე დაამუშავეთ.',
    pureeNoteEn: 'Blend to desired texture.',
  },
  {
    titleKa: 'ქათამი და ბრინჯი',
    titleEn: 'Chicken and Rice',
    descriptionKa: 'ქათამი და ბრინჯი ცალ-ცალკე ან ერთად მოხარშეთ. ქათამი წვრილ ნაჭრებად დაჭერით. ბრინჯი კარგად დარბილდება. ერთად შეურიეთ და ასაკის შესაბამისი ტექსტურით მიეცით.',
    descriptionEn: 'Cook chicken and rice separately or together. Cut chicken into small pieces. Rice softens well. Mix together and serve with age-appropriate texture.',
    ingredientsKa: ['ქათამი - 65 გ', 'ბრინჯი, მოხარშული - 90 გ'],
    ingredientsEn: ['Chicken - 65g', 'Rice, cooked - 90g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 224, proteinGrams: 22, fatGrams: 2.6, carbsGrams: 25.4, fiberGrams: 0.4,
    ironMg: 0.76, vitaminB6mg: 0.39, vitaminB12mcg: 0.2, zincMg: 0.65, potassiumMg: 166,
    magnesiumMg: 11, phosphorusMg: 182,
    blwNoteKa: 'ქათამი ბოჭკოებად, ბრინჯი სქელ გუნდებად — ორივე ხელით საჭერია.',
    blwNoteEn: 'Chicken in fibers, rice in thick clumps — both grippable by hand.',
    pureeNoteKa: 'ერთად ჩანგლით ან ბლენდერით დაჭყლიტეთ.',
    pureeNoteEn: 'Mash or blend together.',
  },
  {
    titleKa: 'ლობიო და ბოსტნეული',
    titleEn: 'Beans and Vegetables',
    descriptionKa: 'თეთრი ლობიო წინასწარ გაჟღენთეთ და კარგად მოხარშეთ. ბოსტნეული ცალკე მოხარშეთ. ჩანგლით ოდნავ დაჭყლიტეთ. ცილით მდიდარი, მაძღრობი სადილია.',
    descriptionEn: 'Soak white beans in advance and cook well. Cook vegetables separately. Mash slightly with a fork. A protein-rich, filling lunch.',
    ingredientsKa: ['თეთრი ლობიო, მოხარშული - 90 გ', 'ბოსტნეული (სტაფილო, ყაბაყი) - 80 გ'],
    ingredientsEn: ['White beans, cooked - 90g', 'Vegetables (carrot, zucchini) - 80g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: [],
    calories: 146, proteinGrams: 10, fatGrams: 0.5, carbsGrams: 27.1, fiberGrams: 7.3,
    ironMg: 2.43, calciumMg: 81, vitaminCmg: 3, vitaminAmcg: 345, vitaminKmcg: 3.4,
    folateMcg: 98, potassiumMg: 703, magnesiumMg: 57,
    blwNoteKa: 'ლობიო ჩანგლით ოდნავ დაჭყლიტეთ, რომ არ იყოს ცალკეული მთლიანი მარცვლები.',
    blwNoteEn: 'Lightly mash the beans with a fork so they are not whole loose pieces.',
    pureeNoteKa: 'ბლენდერით გლუვ მასად აქციეთ.',
    pureeNoteEn: 'Blend into a smooth mass.',
  },
  {
    titleKa: 'ბოსტნეულის ომლეტი',
    titleEn: 'Vegetable Omelette',
    descriptionKa: 'ბროკოლი და სტაფილო მოხარშეთ და წვრილად დაჭერით. კვერცხი ავურიეთ. ზეთის მინიმალური რაოდენობით გამოაცხვეთ ომლეტი. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Cook and finely chop broccoli and carrot. Beat egg. Cook omelette with minimal oil. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['კვერცხი - 1 ცალი', 'ბროკოლი - 30 გ', 'სტაფილო - 30 გ'],
    ingredientsEn: ['Egg - 1', 'Broccoli - 30g', 'Carrot - 30g'],
    ageGroups: ['FROM_9'], mealType: 'LUNCH', allergens: ['egg'],
    calories: 99, proteinGrams: 7, fatGrams: 5.7, carbsGrams: 5.2, fiberGrams: 1.9,
    ironMg: 1.09, calciumMg: 40, vitaminCmg: 20.4, vitaminAmcg: 345, vitaminDmcg: 1,
    vitaminKmcg: 44.9, vitaminB12mcg: 0.65, folateMcg: 56, zincMg: 0.65, potassiumMg: 158, phosphorusMg: 99,
    blwNoteKa: 'ომლეტი პატარა ნაჭრებად დაჭერით ხელით კვებისთვის.',
    blwNoteEn: 'Cut omelette into small pieces for self-feeding.',
    pureeNoteKa: 'ჩანგლით დაჭყლიტეთ ან ბლენდერით დაამუშავეთ.',
    pureeNoteEn: 'Mash with a fork or process in a blender.',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 12-18 MONTHS (FROM_12) — LUNCH — standard toddler lunches (chicken/rice/
  // vegetable, bean, and salmon dishes)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ქათმის გუფთა',
    titleEn: 'Chicken Meatballs with Rice',
    descriptionKa: 'ქათმის ხორცი ბლენდერით დაამუშავეთ. ბრინჯი ოდნავ მოხარშეთ და ქათამს შეუმატეთ. გუფთები ჩამოაყალიბეთ. ორთქლზე ან წყალში 20 წუთი მოხარშეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Process chicken meat in a blender. Slightly cook rice and add to chicken. Shape meatballs. Steam or boil for 20 minutes. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ქათმის ხორცი - 85 გ', 'ბრინჯი, მოხარშული - 60 გ'],
    ingredientsEn: ['Chicken meat - 85g', 'Rice, cooked - 60g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 218, proteinGrams: 28, fatGrams: 3.2, carbsGrams: 16.9, fiberGrams: 0.2,
    ironMg: 0.89, vitaminB6mg: 0.51, vitaminB12mcg: 0.26, zincMg: 0.85, potassiumMg: 218,
    magnesiumMg: 7, phosphorusMg: 213,
  },
  {
    titleKa: 'საქონლის ხორცის გუფთა',
    titleEn: 'Beef Meatballs',
    descriptionKa: 'საქონლის ხორცი ბლენდერით დაამუშავეთ. ბოსტნეული (ყაბაყი, სტაფილო) გაატარეთ სახეხელაზე და შეუმატეთ. გუფთები ჩამოაყალიბეთ. ორთქლზე 20-25 წუთი მოხარშეთ.',
    descriptionEn: 'Process beef in a blender. Grate vegetables (zucchini, carrot) and add. Shape meatballs. Steam for 20-25 minutes.',
    ingredientsKa: ['საქონლის ხორცი, მჭლე - 85 გ', 'ბოსტნეული (ყაბაყი, სტაფილო) - 60 გ'],
    ingredientsEn: ['Lean beef - 85g', 'Vegetables (zucchini, carrot) - 60g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 172, proteinGrams: 26, fatGrams: 5.7, carbsGrams: 3.4, fiberGrams: 1.2,
    ironMg: 2.21, vitaminCmg: 2.3, vitaminAmcg: 259, vitaminKmcg: 2.6, vitaminB12mcg: 2.21,
    folateMcg: 6, zincMg: 4.59, potassiumMg: 438, phosphorusMg: 204,
  },
  {
    titleKa: 'ორაგული ბოსტნეულით',
    titleEn: 'Salmon with Vegetables',
    descriptionKa: 'ორაგული ორთქლზე მოხარშეთ. ეკლები ფრთხილად მოაშორეთ. ბროკოლი და სტაფილო ორთქლზე მოხარშეთ. ჩანგლით ოდნავ დაჭყლიტეთ. ომეგა-3-ით და ვიტამინებით მდიდარი.',
    descriptionEn: 'Steam salmon. Carefully remove bones. Steam broccoli and carrot. Mash slightly with a fork. Rich in omega-3 and vitamins.',
    ingredientsKa: ['ორაგული - 75 გ', 'ბროკოლი - 45 გ', 'სტაფილო - 45 გ'],
    ingredientsEn: ['Salmon - 75g', 'Broccoli - 45g', 'Carrot - 45g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: ['fish'],
    calories: 186, proteinGrams: 18, fatGrams: 9.6, carbsGrams: 6.9, fiberGrams: 2.8,
    ironMg: 0.33, calciumMg: 18, vitaminCmg: 30.6, vitaminAmcg: 397, vitaminDmcg: 9.8,
    vitaminKmcg: 67.4, vitaminB12mcg: 2.1, folateMcg: 49, potassiumMg: 526, phosphorusMg: 180, omega3Mg: 1613,
  },
  {
    titleKa: 'ქათმის სტიუ',
    titleEn: 'Chicken Stew',
    descriptionKa: 'ქათამი, კარტოფილი და სტაფილო წვრილ ნაჭრებად დაჭერით. ნებისმიერ ზეთში ოდნავ შეაცხვეთ, შემდეგ წყალი დაუმატეთ და დაახლოებით 25-30 წუთი ჩაშუშეთ. ასაკის შესაბამისი ტექსტურით მიეცით.',
    descriptionEn: 'Cut chicken, potato and carrot into small pieces. Lightly sauté in oil, then add water and stew for about 25-30 minutes. Serve with age-appropriate texture.',
    ingredientsKa: ['ქათამი - 75 გ', 'კარტოფილი - 55 გ', 'სტაფილო - 40 გ'],
    ingredientsEn: ['Chicken - 75g', 'Potato - 55g', 'Carrot - 40g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 186, proteinGrams: 25, fatGrams: 2.8, carbsGrams: 14.3, fiberGrams: 2.2,
    ironMg: 0.68, vitaminCmg: 8.4, vitaminAmcg: 341, vitaminKmcg: 3.4, vitaminB6mg: 0.6,
    vitaminB12mcg: 0.23, zincMg: 0.75, potassiumMg: 494, magnesiumMg: 12, phosphorusMg: 165,
  },
  {
    titleKa: 'მაკარონი ტომატის სოუსით',
    titleEn: 'Pasta with Tomato Sauce',
    descriptionKa: 'მაკარონი კარგად მოხარშეთ. პომიდორი გაფცქვენით, ჩამოაფშეკით და ოდნავ ჩაშუშეთ. მაკარონი სოუსს შეუმატეთ. ყოველგვარი მარილისა და შაქრის გარეშე.',
    descriptionEn: 'Cook pasta well. Peel tomatoes, blend and simmer slightly. Add pasta to sauce. Without any salt or sugar.',
    ingredientsKa: ['მაკარონი, მოხარშული - 130 გ', 'პომიდორი - 75 გ'],
    ingredientsEn: ['Pasta, cooked - 130g', 'Tomato - 75g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: ['gluten'],
    calories: 184, proteinGrams: 7, fatGrams: 1.6, carbsGrams: 35.4, fiberGrams: 3.2,
    ironMg: 1.17, vitaminCmg: 10.3, vitaminAmcg: 32, folateMcg: 37, potassiumMg: 178, magnesiumMg: 23,
  },
  {
    titleKa: 'ბოსტნეულის პილაფი',
    titleEn: 'Vegetable Pilaf',
    descriptionKa: 'ბრინჯი ბოსტნეულთან ერთად ზეთში ოდნავ შეაცხვეთ. წყალი დაუმატეთ და კარგად მოხარშეთ. ყველა ბოსტნეული კარგად დარბილდება. ასაკის შესაბამისი ტექსტურით მიეცით.',
    descriptionEn: 'Lightly sauté rice with vegetables in oil. Add water and cook well. All vegetables soften well. Serve with age-appropriate texture.',
    ingredientsKa: ['ბრინჯი, მოხარშული - 110 გ', 'ბოსტნეული (სტაფილო, ყაბაყი, ბროკოლი) - 90 გ'],
    ingredientsEn: ['Rice, cooked - 110g', 'Vegetables (carrot, zucchini, broccoli) - 90g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 169, proteinGrams: 4, fatGrams: 0.6, carbsGrams: 36.6, fiberGrams: 2.6,
    ironMg: 0.44, calciumMg: 12, vitaminCmg: 21.8, vitaminAmcg: 268, vitaminKmcg: 44.9,
    folateMcg: 39, potassiumMg: 237, magnesiumMg: 13, phosphorusMg: 47,
  },
  {
    titleKa: 'ლობიოს ჩაშუშული',
    titleEn: 'Bean Stew',
    descriptionKa: 'ლობიო წინასწარ გაჟღენთეთ და მოხარშეთ. სტაფილო წვრილად დაჭერით. ოდნავ შეაცხვეთ, ლობიო და წყალი დაუმატეთ. 15-20 წუთი ჩაშუშეთ. რბილი ტექსტურით მიეცით.',
    descriptionEn: 'Soak and cook beans in advance. Finely chop carrot. Lightly sauté, add beans and water. Stew for 15-20 minutes. Serve with soft texture.',
    ingredientsKa: ['ლობიო, მოხარშული - 100 გ', 'სტაფილო - 45 გ'],
    ingredientsEn: ['Beans, cooked - 100g', 'Carrot - 45g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 155, proteinGrams: 10, fatGrams: 0.4, carbsGrams: 28.8, fiberGrams: 7.7,
    ironMg: 2.7, calciumMg: 90, vitaminCmg: 1.4, vitaminAmcg: 383, vitaminKmcg: 3.9,
    folateMcg: 100, potassiumMg: 667, magnesiumMg: 63,
  },
  {
    titleKa: 'ინდაური და ბრინჯი',
    titleEn: 'Turkey and Rice',
    descriptionKa: 'ინდაური წვრილ ნაჭრებად დაჭერით და მოხარშეთ. ბრინჯი ცალკე მოხარშეთ. ერთად შეურიეთ. ასაკის შესაბამის ზომებად მიეცით. მსუბუქი, ადვილად მოსანელებელი სადილია.',
    descriptionEn: 'Cut turkey into small pieces and cook. Cook rice separately. Mix together. Serve in age-appropriate sized pieces. A light, easily digestible lunch.',
    ingredientsKa: ['ინდაური - 75 გ', 'ბრინჯი, მოხარშული - 100 გ'],
    ingredientsEn: ['Turkey - 75g', 'Rice, cooked - 100g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 231, proteinGrams: 25, fatGrams: 0.8, carbsGrams: 28.2, fiberGrams: 0.4,
    ironMg: 1.25, vitaminB6mg: 0.38, vitaminB12mcg: 0.23, zincMg: 1.13, potassiumMg: 179,
    magnesiumMg: 12, phosphorusMg: 204,
  },
  {
    titleKa: 'ოსპის კატლეტები',
    titleEn: 'Lentil Patties',
    descriptionKa: 'ოსპი კარგად მოხარშეთ და გლუვ მასად დაჭყლიტეთ. კვერცხი შეუმატეთ. პატარა კატლეტები ჩამოაყალიბეთ. ზეთის მინიმალური რაოდენობით გამოაცხვეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Cook lentils well and mash into a smooth mass. Add egg. Shape into small patties. Cook with minimal oil. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ოსპი, მოხარშული - 130 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Lentils, cooked - 130g', 'Egg - 1'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: ['egg'],
    calories: 228, proteinGrams: 18, fatGrams: 6, carbsGrams: 26.7, fiberGrams: 10.3,
    ironMg: 5.17, calciumMg: 28, vitaminAmcg: 80, vitaminDmcg: 1, vitaminB12mcg: 0.65,
    folateMcg: 259, zincMg: 2.34, potassiumMg: 480, magnesiumMg: 47, phosphorusMg: 333,
  },
  {
    titleKa: 'ქათმის კოტლეტი',
    titleEn: 'Chicken Cutlet',
    descriptionKa: 'ქათმის ფილე ბლენდერით დაამუშავეთ. ყაბაყი გაატარეთ სახეხელაზე და შეუმატეთ. კოტლეტები ჩამოაყალიბეთ. ორთქლზე ან ზეთის მინიმალური რაოდენობით გამოაცხვეთ. ასაკის შესაბამის ზომებად მიეცით.',
    descriptionEn: 'Process chicken fillet in blender. Grate zucchini and add. Shape cutlets. Steam or cook with minimal oil. Serve in age-appropriate sized pieces.',
    ingredientsKa: ['ქათმის ფილე - 85 გ', 'ყაბაყი - 45 გ'],
    ingredientsEn: ['Chicken fillet - 85g', 'Zucchini - 45g'],
    ageGroups: ['FROM_12'], mealType: 'LUNCH', allergens: [],
    calories: 148, proteinGrams: 27, fatGrams: 3.2, carbsGrams: 1.4, fiberGrams: 0.5,
    ironMg: 0.77, vitaminCmg: 2.1, vitaminAmcg: 5, vitaminB6mg: 0.51, vitaminB12mcg: 0.26,
    folateMcg: 9, zincMg: 0.85, potassiumMg: 335, phosphorusMg: 187,
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 18-36 MONTHS (FROM_24) — LUNCH — family-style lunches (chicken/rice,
  // beef/pasta, salmon, bean, and lasagna-style dishes)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    titleKa: 'ქათმის შნიცელი',
    titleEn: 'Chicken Schnitzel',
    descriptionKa: 'ქათმის ფილე გაბრტყელეთ. კვერცხში ჩაასველეთ. ზეთში ოქროსფრამდე გამოაცხვეთ. სასურველ ზომებად დაჭერით. ახლადმომზადებული მიეცით ბოსტნეულის გარნირთან ერთად.',
    descriptionEn: 'Flatten chicken fillet. Dip in egg. Cook in oil until golden. Cut into desired sized pieces. Serve freshly made with a vegetable side.',
    ingredientsKa: ['ქათმის ფილე - 95 გ', 'კვერცხი - 1 ცალი'],
    ingredientsEn: ['Chicken fillet - 95g', 'Egg - 1'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: ['egg'],
    calories: 234, proteinGrams: 36, fatGrams: 8.9, carbsGrams: 0.6,
    ironMg: 1.73, calciumMg: 28, vitaminAmcg: 80, vitaminDmcg: 1, vitaminB6mg: 0.57,
    vitaminB12mcg: 0.93, folateMcg: 24, zincMg: 1.6, potassiumMg: 243, phosphorusMg: 308,
  },
  {
    titleKa: 'საქონლის ხორცის გუფთა ბრინჯით',
    titleEn: 'Beef Meatballs with Rice',
    descriptionKa: 'საქონლის ხორცი დაახვიეთ. ბრინჯი ოდნავ მოხარშეთ და ხორცს შეუმატეთ. ბურთულები ჩამოაყალიბეთ. ორთქლზე ან ტომატის სოუსში 25-30 წუთი ჩაშუშეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Mince beef. Slightly cook rice and add to meat. Shape meatballs. Steam or stew in tomato sauce for 25-30 minutes. Serve freshly made.',
    ingredientsKa: ['საქონლის ხორცი, მჭლე - 95 გ', 'ბრინჯი, მოხარშული - 70 გ'],
    ingredientsEn: ['Lean beef - 95g', 'Rice, cooked - 70g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: [],
    calories: 266, proteinGrams: 30, fatGrams: 6.4, carbsGrams: 19.7, fiberGrams: 0.3,
    ironMg: 2.61, vitaminB12mcg: 2.47, zincMg: 5.13, potassiumMg: 323, magnesiumMg: 8, phosphorusMg: 258,
  },
  {
    titleKa: 'ორაგული ბრინჯით',
    titleEn: 'Salmon with Rice',
    descriptionKa: 'ორაგული ორთქლზე ან ზეთის მინიმალური რაოდენობით გამოაცხვეთ. ეკლები ფრთხილად მოაშორეთ. ბრინჯი ცალკე მოხარშეთ. ახლადმომზადებული მიეცით. ომეგა-3-ით მდიდარი სადილია.',
    descriptionEn: 'Steam or cook salmon with minimal oil. Carefully remove bones. Cook rice separately. Serve freshly made. A lunch rich in omega-3.',
    ingredientsKa: ['ორაგული - 85 გ', 'ბრინჯი, მოხარშული - 110 გ'],
    ingredientsEn: ['Salmon - 85g', 'Rice, cooked - 110g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: ['fish'],
    calories: 318, proteinGrams: 21, fatGrams: 10.9, carbsGrams: 31, fiberGrams: 0.4,
    ironMg: 0.22, vitaminDmcg: 11.1, vitaminB12mcg: 2.38, potassiumMg: 326, magnesiumMg: 13,
    phosphorusMg: 251, omega3Mg: 1828,
  },
  {
    titleKa: 'პასტა ბოლონეზე',
    titleEn: 'Pasta Bolognese',
    descriptionKa: 'საქონლის ხორცი ოდნავ შეაცხვეთ. პომიდვრი გაფცქვენით და დაუმატეთ. 20-25 წუთი ჩაშუშეთ. მაკარონი ცალკე მოხარშეთ. სოუსი მაკარონს შეუმატეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Lightly sauté beef. Peel tomatoes and add. Stew for 20-25 minutes. Cook pasta separately. Add sauce to pasta. Serve freshly made.',
    ingredientsKa: ['საქონლის ხორცი, მჭლე - 85 გ', 'მაკარონი, მოხარშული - 130 გ', 'პომიდვრი - 75 გ'],
    ingredientsEn: ['Lean beef - 85g', 'Pasta, cooked - 130g', 'Tomato - 75g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: ['gluten'],
    calories: 340, proteinGrams: 33, fatGrams: 7.1, carbsGrams: 35.4, fiberGrams: 3.2,
    ironMg: 3.38, vitaminCmg: 10.3, vitaminAmcg: 32, vitaminB12mcg: 2.21, folateMcg: 37,
    zincMg: 4.59, potassiumMg: 467, magnesiumMg: 23, phosphorusMg: 204,
  },
  {
    titleKa: 'ქათმის პილაფი',
    titleEn: 'Chicken Pilaf',
    descriptionKa: 'ქათამი წვრილ ნაჭრებად დაჭერით. სტაფილო გაატარეთ სახეხელაზე. ზეთში შეაცხვეთ. ბრინჯი დაუმატეთ და წყალი. დახურული სახურავით 20 წუთი მოხარშეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Cut chicken into small pieces. Grate carrot. Sauté in oil. Add rice and water. Cook covered for 20 minutes. Serve freshly made.',
    ingredientsKa: ['ქათამი - 85 გ', 'ბრინჯი, მოხარშული - 110 გ', 'სტაფილო - 45 გ'],
    ingredientsEn: ['Chicken - 85g', 'Rice, cooked - 110g', 'Carrot - 45g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: [],
    calories: 299, proteinGrams: 29, fatGrams: 3.5, carbsGrams: 34.7, fiberGrams: 1.8,
    ironMg: 0.99, vitaminCmg: 1.4, vitaminAmcg: 383, vitaminKmcg: 3.9, vitaminB6mg: 0.51,
    vitaminB12mcg: 0.26, zincMg: 0.85, potassiumMg: 323, magnesiumMg: 13, phosphorusMg: 234,
  },
  {
    titleKa: 'ბოსტნეულის ლაზანია',
    titleEn: 'Vegetable Lasagna',
    descriptionKa: 'ბოსტნეული ოდნავ შეაცხვეთ. ლაზანიას ფირფიტები, ბოსტნეული და ყველი ფენებად დაალაგეთ. 180°C-ზე 25-30 წუთი გამოაცხვეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Lightly sauté vegetables. Layer lasagna sheets, vegetables and cheese. Bake at 180°C for 25-30 minutes. Serve freshly made.',
    ingredientsKa: ['ლაზანიას ფირფიტები, მოხარშული - 100 გ', 'ყველი - 45 გ', 'ბოსტნეული (ყაბაყი, სტაფილო) - 140 გ'],
    ingredientsEn: ['Lasagna sheets, cooked - 100g', 'Cheese - 45g', 'Vegetables (zucchini, carrot) - 140g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: ['gluten', 'dairy'],
    calories: 348, proteinGrams: 18, fatGrams: 16.3, carbsGrams: 33.5, fiberGrams: 4.6,
    ironMg: 0.9, calciumMg: 324, vitaminCmg: 5.3, vitaminAmcg: 723, vitaminKmcg: 6,
    vitaminB12mcg: 0.37, folateMcg: 35, zincMg: 1.4, potassiumMg: 347, magnesiumMg: 18, phosphorusMg: 230, sodiumMg: 279,
  },
  {
    titleKa: 'ინდაურის კატლეტი',
    titleEn: 'Turkey Patty',
    descriptionKa: 'ინდაური ბლენდერით დაამუშავეთ. ყაბაყი გაატარეთ სახეხელაზე და შეუმატეთ. კატლეტები ჩამოაყალიბეთ. ზეთის მინიმალური რაოდენობით ოქროსფრამდე გამოაცხვეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Process turkey in a blender. Grate zucchini and add. Shape patties. Cook with minimal oil until golden. Serve freshly made.',
    ingredientsKa: ['ინდაური - 95 გ', 'ყაბაყი - 45 გ'],
    ingredientsEn: ['Turkey - 95g', 'Zucchini - 45g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: [],
    calories: 136, proteinGrams: 29, fatGrams: 0.8, carbsGrams: 1.4, fiberGrams: 0.5,
    ironMg: 1.33, vitaminCmg: 2.1, vitaminAmcg: 5, vitaminB6mg: 0.48, vitaminB12mcg: 0.28,
    folateMcg: 9, zincMg: 1.43, potassiumMg: 345, phosphorusMg: 203,
  },
  {
    titleKa: 'ლობიოს ჩაშუშული',
    titleEn: 'Bean Stew',
    descriptionKa: 'ლობიო წინასწარ გაჟღენთეთ და მოხარშეთ. ბოსტნეული წვრილად დაჭერით. ოდნავ შეაცხვეთ, ლობიო და წყალი დაუმატეთ. 20-25 წუთი ჩაშუშეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Soak and cook beans in advance. Finely chop vegetables. Lightly sauté, add beans and water. Stew for 20-25 minutes. Serve freshly made.',
    ingredientsKa: ['ლობიო, მოხარშული - 110 გ', 'ბოსტნეული (სტაფილო, ყაბაყი) - 80 გ'],
    ingredientsEn: ['Beans, cooked - 110g', 'Vegetables (carrot, zucchini) - 80g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: [],
    calories: 174, proteinGrams: 11, fatGrams: 0.6, carbsGrams: 32.1, fiberGrams: 8.5,
    ironMg: 2.97, calciumMg: 99, vitaminCmg: 3, vitaminAmcg: 345, vitaminKmcg: 3.4,
    folateMcg: 118, potassiumMg: 816, magnesiumMg: 69,
  },
  {
    titleKa: 'ბოსტნეულის სუპი',
    titleEn: 'Vegetable Soup',
    descriptionKa: 'კარტოფილი, სტაფილო და ბროკოლი წვრილ ნაჭრებად დაჭერით. წყალში 20-25 წუთი მოხარშეთ. ნახევარი ბლენდერით დამუშავეთ, ნახევარი ნაჭრებად დატოვეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Cut potato, carrot and broccoli into small pieces. Cook in water for 20-25 minutes. Blend half, leave half as pieces. Serve freshly made.',
    ingredientsKa: ['კარტოფილი - 60 გ', 'სტაფილო - 50 გ', 'ბროკოლი - 50 გ'],
    ingredientsEn: ['Potato - 60g', 'Carrot - 50g', 'Broccoli - 50g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: [],
    calories: 87, proteinGrams: 3, fatGrams: 0.4, carbsGrams: 19.8, fiberGrams: 4.2,
    ironMg: 0.37, calciumMg: 20, vitaminCmg: 41.8, vitaminAmcg: 442, vitaminKmcg: 74.9,
    vitaminB6mg: 0.16, folateMcg: 54, potassiumMg: 491, magnesiumMg: 13,
  },
  {
    titleKa: 'ოჯახური სადილის თეფში',
    titleEn: 'Family Lunch Plate',
    descriptionKa: 'ცილა (ქათამი, კვერცხი ან ლობიო), მარცვლეული (ბრინჯი ან მაკარონი) და ბოსტნეული (სასეზონო) ერთ თეფშზე მოაწყვეთ. ყოველი კომპონენტი ცალ-ცალკე მოამზადეთ. ახლადმომზადებული მიეცით.',
    descriptionEn: 'Arrange protein (chicken, egg or beans), grain (rice or pasta) and vegetables (seasonal) on one plate. Prepare each component separately. Serve freshly made.',
    ingredientsKa: ['ქათმის ფილე - 75 გ', 'ბრინჯი, მოხარშული - 45 გ', 'ბროკოლი - 65 გ'],
    ingredientsEn: ['Chicken fillet - 75g', 'Rice, cooked - 45g', 'Broccoli - 65g'],
    ageGroups: ['FROM_24'], mealType: 'LUNCH', allergens: [],
    calories: 205, proteinGrams: 26, fatGrams: 3.1, carbsGrams: 17.4, fiberGrams: 2.3,
    ironMg: 1.24, calciumMg: 26, vitaminCmg: 42.2, vitaminAmcg: 20, vitaminKmcg: 91.7,
    vitaminB6mg: 0.45, vitaminB12mcg: 0.23, folateMcg: 70, zincMg: 0.75, potassiumMg: 382, magnesiumMg: 5, phosphorusMg: 184,
  },
];

async function main() {
  console.log('🌱 Seeding 40 lunch recipes...');

  let created = 0;
  let skipped = 0;

  for (const r of recipes) {
    const existing = await prisma.dish.findFirst({
      where: { titleKa: r.titleKa, mealType: 'LUNCH', ageGroups: { equals: r.ageGroups as any } },
    });

    if (existing) {
      skipped++;
      console.log(`  ⏭  Already exists: ${r.titleKa}`);
      continue;
    }

    await prisma.dish.create({
      data: {
        titleKa: r.titleKa,
        titleEn: r.titleEn,
        descriptionKa: r.descriptionKa,
        descriptionEn: r.descriptionEn,
        ingredientsKa: r.ingredientsKa,
        ingredientsEn: r.ingredientsEn,
        ageGroups: r.ageGroups as any,
        mealType: r.mealType as any,
        allergens: r.allergens || [],
        calories: (r as any).calories ?? null,
        proteinGrams: (r as any).proteinGrams ?? null,
        fatGrams: (r as any).fatGrams ?? null,
        carbsGrams: (r as any).carbsGrams ?? null,
        fiberGrams: (r as any).fiberGrams ?? null,
        ironMg: (r as any).ironMg ?? null,
        calciumMg: (r as any).calciumMg ?? null,
        vitaminCmg: (r as any).vitaminCmg ?? null,
        vitaminAmcg: (r as any).vitaminAmcg ?? null,
        vitaminDmcg: (r as any).vitaminDmcg ?? null,
        vitaminEmg: (r as any).vitaminEmg ?? null,
        vitaminKmcg: (r as any).vitaminKmcg ?? null,
        vitaminB6mg: (r as any).vitaminB6mg ?? null,
        vitaminB12mcg: (r as any).vitaminB12mcg ?? null,
        folateMcg: (r as any).folateMcg ?? null,
        zincMg: (r as any).zincMg ?? null,
        potassiumMg: (r as any).potassiumMg ?? null,
        magnesiumMg: (r as any).magnesiumMg ?? null,
        phosphorusMg: (r as any).phosphorusMg ?? null,
        sodiumMg: (r as any).sodiumMg ?? null,
        omega3Mg: (r as any).omega3Mg ?? null,
        blwNoteKa: (r as any).blwNoteKa ?? null,
        blwNoteEn: (r as any).blwNoteEn ?? null,
        pureeNoteKa: (r as any).pureeNoteKa ?? null,
        pureeNoteEn: (r as any).pureeNoteEn ?? null,
      },
    });
    created++;
    console.log(`  ✓  ${r.titleKa}`);
  }

  console.log(`\n✅ Done: ${created} created, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
