const button = (label: string, href: string) => `<p style="margin:28px 0"><a style="display:inline-block;background:#465940;color:#fff;padding:14px 28px;border-radius:28px;text-decoration:none" href="${href}">${label}</a></p>`;
const code = '<p style="font-size:36px;font-weight:bold;letter-spacing:8px">{{code}}</p>';
export const ENGLISH_EMAILS: Record<string, { subject: string; body: string }> = {
  welcome: { subject: 'Welcome to Mommenu', body: '<h2>Welcome, {{name}}!</h2><p>We’re here to make feeding your little one easier. Add your child’s profile to explore age-appropriate recipes and meal plans.</p>' + button('Open Mommenu', '{{appUrl}}/dashboard?lang=en') },
  email_verify: { subject: 'Verify your Mommenu email address', body: '<h2>Hello, {{name}}!</h2><p>Use this code to finish creating your Mommenu account:</p>' + code + '<p>This code expires in 15 minutes. If you didn’t request it, you can ignore this email.</p>' },
  email_change: { subject: 'Confirm your new Mommenu email address', body: '<h2>Hello, {{name}}!</h2><p>Confirm this address to update the email on your Mommenu account.</p>' + button('Confirm email address', '{{link}}') + '<p>If you didn’t request this change, ignore this email. Your account’s email address will stay unchanged.</p>' },
  password_reset: { subject: 'Reset your Mommenu password', body: '<h2>Reset your password</h2><p>Enter this code in Mommenu to choose a new password:</p>' + code + '<p>This code expires in 5 minutes. If you didn’t request a reset, ignore this email.</p>' },
  password_changed: { subject: 'Your Mommenu password has changed', body: '<h2>Hello, {{name}}!</h2><p>Your password has been updated. If you didn’t make this change, reset your password and contact info@mommenu.ge.</p>' + button('Reset password', '{{appUrl}}/forgot-password?lang=en') },
  subscription_confirmed: { subject: 'Your Mommenu subscription is active', body: '<h2>Thank you, {{name}}!</h2><p>Your {{planName}} is active.</p><p>Plan price: <strong>{{amount}}</strong><br>Period starts: {{startDate}}<br>Access until: {{endDate}}</p><p>For a promotional trial, this is your plan’s price after the trial, rather than a confirmation of a charge today.</p>' + button('Manage subscription', '{{appUrl}}/dashboard?lang=en') },
  subscription_expiring: { subject: 'Your Mommenu plan is ending soon', body: '<h2>Hello, {{name}}!</h2><p>Your current Mommenu period is ending soon. Open your account to review your subscription and keep access to your recipes and meal plans.</p>' + button('Manage subscription', '{{appUrl}}/dashboard?lang=en') },
  weekly_menu: { subject: 'Your weekly Mommenu plan is ready', body: '<h2>Hello, {{name}}!</h2><p>Explore this week’s meal plan, recipes and shopping list for your little one.</p>' + button('View meal plan', '{{appUrl}}/dashboard?lang=en') },
  birthday_wish: { subject: 'Happy birthday to your little one!', body: '<h2>A little celebration from Mommenu</h2><p>Wishing your family a wonderful birthday filled with happy moments and new discoveries.</p>' + button('Open Mommenu', '{{appUrl}}/dashboard?lang=en') },
  new_blog: { subject: 'A new article from Mommenu', body: '<h2>Hello, {{name}}!</h2><p>A new article is ready for you: <strong>{{blogTitle}}</strong></p>' + button('Read the article', '{{blogUrl}}') },
};

export function englishEmailLayout(body: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head><body style="margin:0;background:#FDFBF0;font-family:Arial,sans-serif;color:#465940"><main style="max-width:560px;margin:32px auto;padding:32px;background:white;border-radius:20px"><h1 style="font-size:24px">mommenu</h1>${body}<hr style="border:0;border-top:1px solid #eee;margin:28px 0"><p style="font-size:12px;color:#777">Mommenu · Meals made easier for growing families.<br>Need help? <a href="mailto:info@mommenu.ge">info@mommenu.ge</a></p></main></body></html>`;
}
